var posts = [
'angularjs - custom directive',
'angularjs - form validation',
'angularjs - get started',
'angularjs - my code',
'angularjs - my own repeat directive',
'angularjs - route',
'angularjs - sort and filter a table',
'angularjs - spa folder structure',
'animation - animal farm page turner',
'animation - aquarelle animation',
'animation - atom',
'animation - blood dripping',
'animation - box of snakes',
'animation - clock',
'animation - clockface counter',
'animation - comic',
'animation - css loader circle ball',
'animation - dandelion field',
'animation - delicate fabric',
'animation - draw galaxy',
'animation - exploding bubble text',
'animation - falling',
'animation - firework happy lunar new year 2017',
'animation - firework happy new year',
'animation - flipping coin',
'animation - flower box',
'animation - ghost path',
'animation - image sprite play',
'animation - interactive canvas',
'animation - kelp (sass for)',
'animation - laser to text',
'animation - lissajous curves',
'animation - matrix code rain',
'animation - meteor',
'animation - ocean current',
'animation - orange clock',
'animation - particle animation pure css no js',
'animation - pattern animation',
'animation - sand simulator',
'animation - snow css',
'animation - sound lines',
'animation - sparks',
'animation - speed lines',
'animation - thunder to text',
'animation - tower wave',
'animation - verlet rag doll',
'animation - water effect',
'animation - wormhole effect',
'apache - virtual host',
'bootstrap - badge',
'bootstrap - basic form',
'bootstrap - button',
'bootstrap - button group',
'bootstrap - carousel',
'bootstrap - checkbox and radio',
'bootstrap - color',
'bootstrap - compile with koala',
'bootstrap - custom checkbox and radio',
'bootstrap - custom file upload',
'bootstrap - custom range',
'bootstrap - custom select',
'bootstrap - dropdown',
'bootstrap - flex',
'bootstrap - form',
'bootstrap - get started',
'bootstrap - inline form',
'bootstrap - input',
'bootstrap - input group',
'bootstrap - media',
'bootstrap - modal',
'bootstrap - navigator',
'bootstrap - popover',
'bootstrap - progress bar',
'bootstrap - select',
'bootstrap - textarea',
'bootstrap - tooltip',
'bootstrap - typography',
'bootstrap - utility border',
'bootstrap - utility float',
'bootstrap - utility sizing',
'bootstrap - utility spacing',
'cassandra - add remove nodes',
'cassandra - backup and restore',
'cassandra - big data demo',
'cassandra - configuration file',
'cassandra - copy function',
'cassandra - data model',
'cassandra - data types',
'cassandra - get started',
'cassandra - java',
'cassandra - keyspace',
'cassandra - multiple nodes',
'cassandra - nodetool utility',
'cassandra - php',
'cassandra - replication',
'cassandra - spring boot',
'cassandra - table',
'ckeditor - ckeditor 5 demo',
'ckeditor - get started',
'ckeditor - server side',
'css - animate.css',
'css - arrows',
'css - aspect ratio',
'css - border-collapse',
'css - circular progress bar',
'css - circular progress bar 2',
'css - coding conventions',
'css - css selector',
'css - faux web font',
'css - filters',
'css - flexbox introduction',
'css - focus-within',
'css - font-weight',
'css - fontawesome',
'css - get web font',
'css - google font',
'css - grid',
'css - multi-level menu',
'css - object-fit',
'css - perspective',
'css - placeholder-shown',
'css - position sticky',
'css - precedence',
'css - real layout examples with flexbox',
'css - shapes',
'css - slide in',
'css - style input type range',
'css - text-overflow',
'css - vertical align',
'css - web font averta',
'css - web font opensans',
'css - web font proxima nova',
'css - web font roboto',
'django - get started',
'docker - build image form container',
'docker - common commands',
'docker - deploy spring boot',
'docker - docker compose',
'docker - docker hub',
'docker - docker toolbox, windows 7, shared volume',
'docker - dockerfile',
'docker - get started',
'docker - install docker on ubuntu',
'docker - install docker on windows 10',
'docker - install docker on windows 7',
'docker - laradock',
'docker - laravel container',
'docker - push image',
'docker - use composer',
'docker - use mysql',
'docker - use nginx',
'docker - use php',
'docker - use redis',
'docker - video course',
'docker - when and why',
'eclipse - code formatter',
'eclipse - disable join comment lines',
'eclipse - maven',
'eclipse - shortcuts',
'eclipse - tomcat',
'elasticsearch - api index',
'elasticsearch - api mapping',
'elasticsearch - api node',
'elasticsearch - api search',
'elasticsearch - configuration',
'elasticsearch - crud',
'elasticsearch - export and import',
'elasticsearch - get started',
'elasticsearch - installation on linux',
'elasticsearch - installation on windows',
'elasticsearch - introduction',
'elasticsearch - mongodb and elasticsearch with transporter',
'elasticsearch - mongodb to elasticsearch with monstache',
'elasticsearch - web extension elasticsearch head',
'game - 2048',
'game - card matching halloween',
'game - feed the frog',
'game - flip card pair',
'game - html5 pacman',
'game - interactive-snake',
'game - tetris',
'game - x-o online',
'git - beginner\'s guide for dummies',
'git - compare revisions',
'git - disable crlf warning',
'git - external merge and diff tools',
'git - get started',
'git - git-chain',
'git - github repo size',
'git - gitignore',
'git - proxy',
'git - remove files',
'git - save git password',
'git - use ssh key',
'gulp - auto refresh browser',
'gulp - compile css',
'gulp - concat files',
'gulp - get started',
'gulp - minify js css',
'gulp - prevent gulp stop',
'gulp - snippets',
'heroku - get started',
'highcharts - datetime axis formatting',
'highcharts - examples version 6.1.3',
'highcharts - get started',
'highcharts - highcharts vs chart.js',
'highcharts - legend',
'highcharts - tooltip',
'it - auto deploy',
'it - buy hdplayer',
'it - buy pc',
'it - check application alive',
'it - cloud database',
'it - convert html to epub',
'it - create markdown document',
'it - create subtitle (lyric) file',
'it - data category',
'it - delete google history',
'it - delete private data',
'it - don dep noi that may tinh',
'it - epub format',
'it - full-stack web developer',
'it - get favicon',
'it - get lyric file from nhaccuatui',
'it - google analytics',
'it - how to learn new programming language',
'it - install os and softwares',
'it - it companies in vietnam',
'it - languages comparison',
'it - line stickers (brown & cony\'s secret date!)',
'it - lunar calendar',
'it - maze path finder',
'it - my cv',
'it - my cv (old)',
'it - nosql',
'it - programming quotes',
'it - qua chau chuot code la tu hai minh',
'it - screencast',
'it - selenium',
'it - simple web server',
'it - video streaming',
'java - annotation',
'java - apk to jar',
'java - bcrypt',
'java - compress',
'java - concise code',
'java - connect ssl',
'java - create thumbnail',
'java - datetime',
'java - deploy tomcat',
'java - drm',
'java - execute concurrent functions',
'java - execute external command',
'java - file filter',
'java - fix smtps error when sending mail',
'java - image resizer',
'java - jar file',
'java - java 8 features',
'java - java 8 stream',
'java - java-demo',
'java - jep',
'java - json',
'java - jsoup',
'java - logging',
'java - multithread',
'java - notes',
'java - quartz',
'java - read file',
'java - regex extractor',
'java - rename',
'java - rest',
'java - system.setproperties scope',
'java - unit test',
'java - use font',
'java - xml',
'javascript - ajax submit',
'javascript - arrays',
'javascript - async await',
'javascript - audio and microphone visualizer',
'javascript - breadth first search algorithm',
'javascript - browser console',
'javascript - calculating week number',
'javascript - canvas grid',
'javascript - cookie',
'javascript - copy text',
'javascript - datatable',
'javascript - dijkstra algorithm',
'javascript - dom to canvas animation',
'javascript - epub reader',
'javascript - es6',
'javascript - es6 (oop)',
'javascript - event delegation',
'javascript - events',
'javascript - exception',
'javascript - file api',
'javascript - file saver',
'javascript - filter array function',
'javascript - find array function',
'javascript - frameworks and libraries',
'javascript - fullpage.js',
'javascript - fullpage.js with animate.css',
'javascript - fullpage.js with wow.js',
'javascript - function',
'javascript - functional programming',
'javascript - get parameter',
'javascript - google sheet api',
'javascript - history api',
'javascript - infinite scroll',
'javascript - insertadjacenthtml',
'javascript - isHtmlCode',
'javascript - javascript 2016',
'javascript - json form binding',
'javascript - justified.js',
'javascript - key sequence detection',
'javascript - keyboard input',
'javascript - manipulating pixels with canvas',
'javascript - map array function',
'javascript - mobile number',
'javascript - monitering dom changes',
'javascript - multi-language',
'javascript - notification api',
'javascript - onbeforeunload',
'javascript - onmousedown',
'javascript - output pretty json',
'javascript - page scroll',
'javascript - page visibility api',
'javascript - password generator',
'javascript - promise',
'javascript - pure javascript ajax',
'javascript - reduce array function',
'javascript - refer to parent from iframe',
'javascript - relative mouse coordinate',
'javascript - replace function',
'javascript - requestanimationframe',
'javascript - say numbers',
'javascript - screen size',
'javascript - show hide passwords',
'javascript - simple multi-language translation',
'javascript - slide up down',
'javascript - speech recognition',
'javascript - spread syntax',
'javascript - summernote - a simple editor',
'javascript - table sorter',
'javascript - tag inputs',
'javascript - toc',
'javascript - typescript',
'javascript - wavesurfer',
'javascript - window open function',
'javascript - wow.js',
'jquery - ajax setup',
'jquery - get started',
'jquery - no need',
'knowledge - 4.0 revolution',
'knowledge - bake a potato in the microwave',
'knowledge - common learning mistakes',
'knowledge - nutrious food',
'knowledge - phan biet dinh chua',
'knowledge - tai khoan tiet kiem',
'laravel - add custom fields to register form',
'laravel - artisan',
'laravel - authentication',
'laravel - blade and javascript frameworks',
'laravel - blade template',
'laravel - blade template control structures',
'laravel - change login field',
'laravel - change users table name',
'laravel - cheat sheet',
'laravel - configuration',
'laravel - contract',
'laravel - controller',
'laravel - create helper functions',
'laravel - csrf',
'laravel - custom webpack configuration',
'laravel - database',
'laravel - deploy',
'laravel - eloquent',
'laravel - eloquent collections',
'laravel - eloquent fill method',
'laravel - eloquent mutators',
'laravel - eloquent relationships',
'laravel - eloquent serialization',
'laravel - email verification',
'laravel - encryption',
'laravel - error',
'laravel - events',
'laravel - excel',
'laravel - extending blade',
'laravel - facade',
'laravel - filesystem',
'laravel - folder structure',
'laravel - frontend',
'laravel - get started',
'laravel - hashing',
'laravel - helpers',
'laravel - i18n',
'laravel - installation',
'laravel - khoa pham course',
'laravel - logging',
'laravel - login active user',
'laravel - login throttle',
'laravel - mail',
'laravel - middleware',
'laravel - migrations',
'laravel - mix',
'laravel - mix browsersync',
'laravel - mix css',
'laravel - mix js',
'laravel - mix versioning',
'laravel - pagination',
'laravel - query builder',
'laravel - redis',
'laravel - remember login',
'laravel - request',
'laravel - reset password',
'laravel - response',
'laravel - route, url, asset',
'laravel - routing',
'laravel - scheduling',
'laravel - scout',
'laravel - seeding',
'laravel - service container',
'laravel - service provider',
'laravel - session',
'laravel - sharing data between views',
'laravel - socialite',
'laravel - starter project',
'laravel - upgrading to version 5.7 from 5.6',
'laravel - validation',
'laravel - validation display errors',
'laravel - validation rule object',
'laravel - validation strong password',
'laravel - view',
'laravel - view composer',
'lib - chart.js',
'lib - common validation',
'lib - noti',
'lib - pagi',
'linux - bash config',
'linux - change host name',
'linux - configure wallpaper',
'linux - create html5 greeter theme',
'linux - create shortcut',
'linux - crontab',
'linux - customize computer style',
'linux - customize shell prompt',
'linux - disable ipv6',
'linux - disk space',
'linux - extract folder permission',
'linux - force copy',
'linux - install apache (ubuntu)',
'linux - install composer',
'linux - install mysql (ubuntu)',
'linux - install nginx (ubuntu)',
'linux - install oracle jdk',
'linux - install php (ubuntu)',
'linux - install phpmyadmin (ubuntu)',
'linux - install wordpress',
'linux - installing php 7 on centos',
'linux - linux mint desklet',
'linux - linux mint theme',
'linux - noi video bang avidemux',
'linux - open jar file',
'linux - open nginx.conf error (permission denied)',
'linux - permission',
'linux - resize, convert and modify images',
'linux - rip template with wget',
'linux - run php with nginx',
'linux - service management',
'linux - setting path',
'linux - share file',
'linux - user and group',
'linux - vi basics',
'linux - vista drives',
'maven - application template',
'maven - build gz package',
'maven - build jar package',
'maven - get started',
'maven - latest maven repositories',
'maven - oracle jdbc library',
'maven - web template',
'memcached - get started',
'mongodb - get started',
'mongodb - mongodb (nodejs driver)',
'mongodb - mongoose (nodejs driver)',
'mongodb - tutorialpoint',
'mysql - create a new user and grant permissions',
'mysql - full text search',
'mysql - get version',
'mysql - import and export',
'mysql - install mysql on linux mint',
'mysql - type date',
'neo4j - get started',
'nginx - block',
'nginx - configuration',
'nginx - deploy with flask',
'nginx - load balancer',
'nginx - location configuration',
'nginx - reverse proxy',
'nginx - setup on windows',
'node - get started',
'node - http package',
'node - npm proxy',
'opencv - panel detection',
'oracle - ddl query',
'php - array',
'php - compact function',
'php - composer proxy',
'php - datetime',
'php - elvis operator',
'php - execute from cli',
'php - file',
'php - json',
'php - regular expression',
'php - sprintf function',
'php - string array conversion',
'php - string functions',
'php - trait',
'project - aff cup 2018',
'project - audio book',
'project - classmates',
'project - comic reader',
'project - comic reader (all links)',
'project - comic reader (dc)',
'project - comic reader (double page)',
'project - comic reader (half page)',
'project - comic reader (pulp 2)',
'project - comic reader (pulp-press 2)',
'project - comic split',
'project - comics manager',
'project - disable open new ad tab',
'project - doc truyen',
'project - download github folder',
'project - fast read (spritz-speed-reading-v2)',
'project - fast read 1',
'project - format css',
'project - get links',
'project - highlight syntax',
'project - homepage',
'project - lich cua toi',
'project - lien hoan hoa',
'project - manga rock image decoder',
'project - map',
'project - markdown preview',
'project - media player',
'project - media player wayou selected',
'project - money manager',
'project - my family',
'project - my notes',
'project - puzzle',
'project - short',
'project - subtitle',
'project - task manager',
'project - world cup 2018',
'pwa - a2hs',
'pwa - get started',
'pwa - push api',
'python - access command line arguments',
'python - access mysql',
'python - base64',
'python - basic python course',
'python - cgi',
'python - class',
'python - coding utf-8',
'python - datetime',
'python - decorator',
'python - dict type',
'python - download file',
'python - email',
'python - excel file',
'python - exception',
'python - file operations',
'python - http server',
'python - if expression',
'python - installation',
'python - jinja2 template',
'python - json processing',
'python - list type',
'python - logging',
'python - main function',
'python - make python script global',
'python - module',
'python - multithreading',
'python - package',
'python - pip',
'python - read and write file',
'python - regular expression',
'python - resize image',
'python - set type',
'python - setup proxy for pip',
'python - soap client',
'python - string type',
'python - tuple type',
'react js - get started',
'redis - cluster',
'redis - command references',
'redis - get started',
'regular expression - get started',
'sass - control directives expressions',
'sass - extend',
'sass - function',
'sass - get started',
'sass - global variables',
'sass - import',
'sass - mixin',
'sass - nested properties',
'sass - operations',
'sass - real example',
'sass - repsonsive',
'spring boot - get started',
'sql - database conventions',
'sql - tuning',
'story - 10 years of youtube',
'story - 2016 summary',
'story - all kills of dragon ball characters',
'story - barca',
'story - chu cho con',
'story - core values',
'story - first time in my life',
'story - football and life',
'story - hinh anh minh hoa sach tap doc xua',
'story - hoai niem cung nhung mon do co gan lien voi the he 8x',
'story - ideas',
'story - it\'s never too late',
'story - journey to the west',
'story - life as a sales engineer',
'story - life purpose',
'story - my idols',
'story - my plan',
'story - personal names',
'story - quotes',
'story - tay du ky',
'story - the story of life',
'story - truyen tranh viet nam',
'tomcat - serving static content from outside tomcat',
'ui - 3d css book covers',
'ui - 3d emoji town (pure css)',
'ui - 3d game box',
'ui - 3d layers',
'ui - 3d paralax',
'ui - add more',
'ui - aeros',
'ui - anagram animation',
'ui - attractive data form',
'ui - auto-complete dropdown',
'ui - autosize',
'ui - blend video background',
'ui - breadcrum arrow',
'ui - bubble animation',
'ui - button',
'ui - calendar',
'ui - call buttons',
'ui - canvas zoom and pan image',
'ui - cat click meme',
'ui - change image onhover',
'ui - chien tranh bien gioi viet trung',
'ui - chinhphucvumon.vn',
'ui - connector',
'ui - cover board',
'ui - cracked text effect',
'ui - crud layout',
'ui - css clip path hover effect',
'ui - css grid for getty images',
'ui - css grid gantt chart',
'ui - css grid zoom',
'ui - css rotation navigation',
'ui - customize scrollbar',
'ui - dark ui',
'ui - datepicker',
'ui - dropdown',
'ui - farm shop',
'ui - fit to width',
'ui - flame',
'ui - floating elements',
'ui - flower shop',
'ui - font awesome gradient',
'ui - football match',
'ui - football table',
'ui - form with previous values',
'ui - futuristic 3d hover effect',
'ui - gallery',
'ui - generate icon',
'ui - hacker',
'ui - hamburger menu',
'ui - happy birthday to my wife',
'ui - horizontal scroll',
'ui - image comparison slider',
'ui - image fading transition',
'ui - image magnifier glass',
'ui - image zoom',
'ui - inline edit',
'ui - interactive map',
'ui - jewelry shop',
'ui - justice league action',
'ui - karaoke',
'ui - light loader',
'ui - login v12',
'ui - login v15',
'ui - map 3d',
'ui - marquee',
'ui - marvel css series 1 - eye of agamotto',
'ui - masonry',
'ui - masonry grid',
'ui - matrix digital rain',
'ui - maxlength indicator',
'ui - metro card',
'ui - mobile app',
'ui - modal',
'ui - multi-steps form flow keyframers',
'ui - multi-steps registration form',
'ui - musical instruments',
'ui - neon sign checkbox',
'ui - news app concept with css variables',
'ui - one piece chapters',
'ui - organic paper',
'ui - paper',
'ui - parallax background',
'ui - parallax elements',
'ui - pattern lock',
'ui - periodic table',
'ui - pie chart',
'ui - pulse animation',
'ui - pure css dropdown menu',
'ui - pure css material checkbox',
'ui - pure css particle animation',
'ui - random girl image',
'ui - range slider',
'ui - reflection text',
'ui - refracted floating text effect',
'ui - responsive canvas',
'ui - responsive table',
'ui - resume',
'ui - select',
'ui - select box pure css with direction aware hover effect',
'ui - select country',
'ui - selectable',
'ui - shapes with css',
'ui - shimmering neon text',
'ui - shuffle animation',
'ui - sidebar dropdown',
'ui - sidebar search menu',
'ui - single element hamburger icons',
'ui - slide show',
'ui - smoky text',
'ui - somafm music player',
'ui - speed line',
'ui - split image',
'ui - spotlight',
'ui - sticky header with intersectionobserver',
'ui - sunburst chart',
'ui - swipe',
'ui - swipe animation',
'ui - swipe to delete',
'ui - tab simple and cute',
'ui - table',
'ui - tabs with sliding underline',
'ui - tearable cloth',
'ui - three.js snow globe',
'ui - timeline vertical',
'ui - toggle nav when scroll',
'ui - tooltip dictionary',
'ui - treasure hunters',
'ui - tree drawing',
'ui - tree fall',
'ui - tree generator',
'ui - user rating',
'ui - vanhoc.xitrum.net',
'ui - vtsoft1.portal',
'ui - wall-e',
'ui - water level',
'ui - wedding photos',
'ui - wesnoth.org',
'ui - windows 10 metro',
'ui - zoom',
'voyager - configuration',
'voyager - get started',
'vscode - developing java apps',
'vscode - open multiple windows',
'vscode - quick open file',
'vscode - tab size',
'vscode - use tab to indent',
'vue - class and style',
'vue - component (content distribution with slots)',
'vue - component (dom template parsing caveats)',
'vue - component (dynamic components)',
'vue - component (emit events up to parent)',
'vue - component (get started)',
'vue - component (html template)',
'vue - component (parse properties down to child)',
'vue - component (registration)',
'vue - component (single file)',
'vue - component (vue extend)',
'vue - computed',
'vue - conditional',
'vue - events',
'vue - filter',
'vue - filtered list',
'vue - form',
'vue - get started',
'vue - installation',
'vue - instance',
'vue - introduction',
'vue - list',
'vue - syntax',
'vue - transition',
'vue - transitioning state',
'vue - v-cloak',
'web - add css dynamically',
'web - admin packages',
'web - bread, not crud',
'web - details element',
'web - display chrome bookmarks',
'web - drag and drop',
'web - emmet',
'web - epub viewer (bibi)',
'web - facebook comment',
'web - get computed css',
'web - highlightjs',
'web - icon on title',
'web - image loader',
'web - intro.js',
'web - jquery-comments',
'web - less',
'web - link to iframe',
'web - live chat',
'web - mathml',
'web - off-canvas menu',
'web - open source projects',
'web - pdf viewer (pdf.js)',
'web - personal website',
'web - popular cdn',
'web - prevent copy content',
'web - referrer',
'web - simple template',
'web - social share',
'web - string format function',
'web - text semantic tags',
'web - tts',
'web - video call with easyrtc',
'webext - batch downloader',
'webext - browse my repo',
'webext - live reload',
'webext - screenshot',
'webext - timestats',
'webext - youtube ads remover',
'webext - youtube subtitle downloader',
'webext - youtube video downloader'
];
var categories = [
{ name: 'ui', y: 139 },
{ name: 'laravel', y: 75 },
{ name: 'javascript', y: 74 },
{ name: 'animation', y: 40 },
{ name: 'project', y: 36 },
{ name: 'python', y: 36 },
{ name: 'linux', y: 36 },
{ name: 'java', y: 34 },
{ name: 'css', y: 33 },
{ name: 'it', y: 33 },
{ name: 'bootstrap', y: 32 },
{ name: 'web', y: 32 },
{ name: 'vue', y: 26 },
{ name: 'story', y: 22 },
{ name: 'docker', y: 21 },
{ name: 'cassandra', y: 16 },
{ name: 'elasticsearch', y: 14 },
{ name: 'php', y: 13 },
{ name: 'git', y: 12 },
{ name: 'sass', y: 11 },
{ name: 'webext', y: 8 },
{ name: 'angularjs', y: 8 },
{ name: 'game', y: 8 },
{ name: 'nginx', y: 7 },
{ name: 'maven', y: 7 },
{ name: 'gulp', y: 7 },
{ name: 'mysql', y: 6 },
{ name: 'knowledge', y: 6 },
{ name: 'highcharts', y: 6 },
{ name: 'eclipse', y: 5 },
{ name: 'vscode', y: 5 },
{ name: 'lib', y: 4 },
{ name: 'mongodb', y: 4 },
{ name: 'ckeditor', y: 3 },
{ name: 'redis', y: 3 },
{ name: 'node', y: 3 },
{ name: 'pwa', y: 3 },
{ name: 'jquery', y: 3 },
{ name: 'sql', y: 2 },
{ name: 'voyager', y: 2 },
{ name: 'tomcat', y: 1 },
{ name: 'apache', y: 1 },
{ name: 'oracle', y: 1 },
{ name: 'memcached', y: 1 },
{ name: 'react js', y: 1 },
{ name: 'regular expression', y: 1 },
{ name: 'heroku', y: 1 },
{ name: 'spring boot', y: 1 },
{ name: 'django', y: 1 },
{ name: 'neo4j', y: 1 },
{ name: 'opencv', y: 1 }
];
