var heroes = [
    {
        "rank": "1",
        "star": "Tiankui<br> (天魁);<br> Leader Star<br> (天魁星)",
        "name": "Song Jiang<br> (宋江; Sòng Jiāng; Sung Chiang)",
        "nickname": "\"Protector of Righteousness\"",
        "otherNames": "Gongming<br> (公明);<br> \"Timely Rain\"<br> (及時雨);<br> \"Filial and Righteous Dark Third Son\"<br> (孝義黑三郎);<br> \"Dark Song Jiang\"<br> (黑宋江)",
        "division": "Commander",
        "designation": "Leader",
        "origin": "Magistrate's clerk",
        "homePlace": "Yuncheng County, Heze, Shandong",
        "weapon": "<br> ",
        "starVietnamese": "Thiên Khôi Tinh",
        "nicknameVietnamese": "Hô Bảo Nghĩa (người kêu gọi bảo vệ chính nghĩa) <br> Cập Thời Vũ (mưa đúng lúc)",
        "nameVietnamese": "Tống Giang",
        "designationVietnamese": "Tổng Binh Đô Đầu lĩnh",
        "image": "001_thien khoi tinh_ho bao nghia_tong giang.jpg"
      },
      {
        "rank": "2",
        "star": "Tiangang<br> (天罡);<br> Strength Star<br> (天罡星)",
        "name": "Lu Junyi<br> (卢俊义; 盧俊義; Lú Jùnyì; Lu Chün-i)",
        "nickname": "\"Jade Qilin\"",
        "otherNames": "<br> ",
        "division": "Commander",
        "designation": "Deputy leader",
        "origin": "Squire",
        "homePlace": "Daming Prefecture<br> (in present-day Handan, Hebei)",
        "weapon": "Spear,<br> Cudgel,<br> Pudao",
        "starVietnamese": "Thiên Cương Tinh <p>(天罡星)</p> ",
        "nicknameVietnamese": "Ngọc Kỳ Lân (kỳ lân ngọc)",
        "nameVietnamese": "Lư Tuấn Nghĩa",
        "designationVietnamese": "Tổng Binh Đô Đầu Lĩnh",
        "image": "002_thien cuong tinh_ngoc ky lan_lu tuan nghia.jpg"
      },
      {
        "rank": "3",
        "star": "Tianji<br> (天機);<br> Knowledge Star<br> (天機星)",
        "name": "Wu Yong<br> (吴用; 吳用; Wú Yòng; Wu Yung)",
        "nickname": "\"Resourceful Star\"",
        "otherNames": "Xuejiu<br> (學究)",
        "division": "Strategist",
        "designation": "Chief strategist",
        "origin": "Professor",
        "homePlace": "Yuncheng County, Heze, Shandong",
        "weapon": "Bronze hammer",
        "starVietnamese": "Thiên Cơ Tinh <p>(天機星)</p> ",
        "nicknameVietnamese": "Trí Đa Tinh (mưu trí sáng tựa ngàn sao)",
        "nameVietnamese": "Ngô Dụng",
        "designationVietnamese": "Quân Sư",
        "image": "003_thien co tinh_tri da tinh_ngo dung.jpg"
      },
      {
        "rank": "4",
        "star": "Tianxian<br> (天閒);<br> Leisure Star<br> (天閒星)",
        "name": "Gongsun Sheng<br> (公孙胜; 公孫勝; Gōngsūn Shèng; Kung-sun Sheng)",
        "nickname": "\"Dragon in the Clouds\"",
        "otherNames": "<br> ",
        "division": "Strategist",
        "designation": "Strategist in charge of army formation",
        "origin": "Taoist",
        "homePlace": "Jizhou<br> (present-day Ji County, Tianjin)",
        "weapon": "Sword, Taoist magic",
        "starVietnamese": "Thiên Nhàn Tinh <p>(天閒星)</p> ",
        "nicknameVietnamese": "Nhập Vân Long (Rồng luồn mây)",
        "nameVietnamese": "Công Tôn Thắng",
        "designationVietnamese": "Phương Sĩ",
        "image": "004_thien nhan tinh_nhap van long_cong ton thang.jpg"
      },
      {
        "rank": "5",
        "star": "Tianyong<br> (天勇);<br> Brave Star<br> (天勇星)",
        "name": "Guan Sheng<br> (关胜; 關勝; Guān Shèng; Kuan Sheng)",
        "nickname": "\"Great Blade\"",
        "otherNames": "<br> ",
        "division": "Five Tiger Generals(cavalry)",
        "designation": "Left General",
        "origin": "Imperial general",
        "homePlace": "Yuncheng, Shanxi",
        "weapon": "Blue Dragon Crescent Moon Blade<br> (青龍偃月刀)",
        "starVietnamese": "Thiên Dũng Tinh <p>(天勇星)</p> ",
        "nicknameVietnamese": "Đại Đao (đao lớn)",
        "nameVietnamese": "Quan Thắng",
        "designationVietnamese": "Mã Quân Thanh Long Tướng",
        "image": "005_thien dung tinh_dai dao_quan thang.jpg"
      },
      {
        "rank": "6",
        "star": "Tianxiong<br> (天雄);<br> Majestic Star<br> (天雄星)",
        "name": "Lin Chong<br> (林沖; 林沖; Lín Chōng; Lin Ch'ung)",
        "nickname": "\"Panther Head\"",
        "otherNames": "Instructor Lin<br> (林教頭);<br> Little Zhang Fei<br> (小張飛)",
        "division": "Five Tiger Generals (cavalry)",
        "designation": "Right General",
        "origin": "Martial arts instructor of the Imperial Guards",
        "homePlace": "Dongjing<br> (present-day Kaifeng, Henan)",
        "weapon": "8-foot-long (2.4 m) Snake Spear<br> (丈八蛇矛);<br> Pudao<br> (朴刀)",
        "starVietnamese": "Thiên Hùng Tinh <p>(天雄星)</p> ",
        "nicknameVietnamese": "Báo Tử Đầu (báo chúa, báo đầu đàn)",
        "nameVietnamese": "Lâm Xung",
        "designationVietnamese": "Mã Quân Xích Long Tướng",
        "image": "006_thien hung tinh_bao tu dau_lam xung.jpg"
      },
      {
        "rank": "7",
        "star": "Tianmeng<br> (天猛);<br> Fierce Star<br> (天猛星)",
        "name": "Qin Ming<br> (秦明; 秦明; Qín Míng; Ch'in Ming)",
        "nickname": "\"Fiery Thunderbolt\"",
        "otherNames": "<br> ",
        "division": "Five Tiger Generals (cavalry)",
        "designation": "Vanguard General",
        "origin": "Imperial general",
        "homePlace": "Kaizhou (believed to be present-day Puyang, Henan)",
        "weapon": "Wolf-toothed mace<br> (狼牙棒)",
        "starVietnamese": "Thiên Mãnh Tinh <p>(天猛星)</p> ",
        "nicknameVietnamese": "Tích Lịch Hỏa (lửa sấm sét)",
        "nameVietnamese": "Tần Minh",
        "designationVietnamese": "Mã Quân Hổ Tướng",
        "image": "007_thien manh tinh_tich lich hoa_tan minh.jpg"
      },
      {
        "rank": "8",
        "star": "Tianwei<br> (天威);<br> Prestige Star<br> (天威星)",
        "name": "Huyan Zhuo<br> (呼延灼; 呼延灼; Hūyán Zhuó; Hu-yen Cho)",
        "nickname": "\"Double Clubs\"",
        "otherNames": "<br> ",
        "division": "Five Tiger Generals (cavalry)",
        "designation": "Rear General",
        "origin": "Imperial general",
        "homePlace": "Taiyuan, Shanxi",
        "weapon": "Pair of steel clubs",
        "starVietnamese": "Thiên Uy Tinh <p>(天威星)</p> ",
        "nicknameVietnamese": "Song Tiên (hai roi)",
        "nameVietnamese": "Hô Diên Chước",
        "designationVietnamese": "Mã Quân Hổ Tướng",
        "image": "008_thien uy tinh_song tien_ho dien chuoc.jpg"
      },
      {
        "rank": "9",
        "star": "Tianying<br> (天英);<br> Hero Star<br> (天英星)",
        "name": "Hua Rong<br> (花荣; 花榮; Huā Róng; Hua Jung)",
        "nickname": "\"Little Li Guang\"",
        "otherNames": "<br> ",
        "division": "Eight Tiger Cub Vanguard Generals (cavalry)",
        "designation": "<br> ",
        "origin": "Military officer",
        "homePlace": "Qingfeng Fort (in present-day Qingzhou, Weifang, Shandong)",
        "weapon": "Spear;<br> Bow and arrows",
        "starVietnamese": "Thiên Anh Tinh <p>(天英星)</p> ",
        "nicknameVietnamese": "Tiểu Lý Quảng (Lý Quảng nhỏ)",
        "nameVietnamese": "Hoa Vinh",
        "designationVietnamese": "Mã Quân Bát Hổ Tiên Phong Sứ",
        "image": "009_thien anh tinh_tieu ly quang_hoa vinh.jpg"
      },
      {
        "rank": "10",
        "star": "Tiangui<br> (天貴);<br> Noble Star<br> (天貴星)",
        "name": "Chai Jin<br> (柴进; 柴進; Chái Jìn; Ch'ai Chin)",
        "nickname": "\"Little Whirlwind\"",
        "otherNames": "Nobleman Chai<br> (柴大官人);<br> Ke Yin<br> (柯引)",
        "division": "Logistics",
        "designation": "Chief accountant",
        "origin": "Nobleman, descendant of Chai Rong",
        "homePlace": "Cangzhou, Hebei",
        "weapon": "Spear",
        "starVietnamese": "Thiên Quý Tinh <p>(天貴星)</p> ",
        "nicknameVietnamese": "Tiểu Toàn Phong (cơn lốc nhỏ)",
        "nameVietnamese": "Sài Tiến",
        "designationVietnamese": "Quân Lương Lệnh Sử",
        "image": "010_thien quy tinh_tieu toan phong_sai tien.jpg"
      },
      {
        "rank": "11",
        "star": "Tianfu<br> (天富);<br> Wealth Star<br> (天富星)",
        "name": "Li Ying<br> (李应; 李應; Lǐ Yìng; Li Ying)",
        "nickname": "\"Striking Hawk\"",
        "otherNames": "<br> ",
        "division": "Logistics",
        "designation": "Chief accountant",
        "origin": "Squire",
        "homePlace": "Yunzhou, Zhongshan Prefecture (around present-day Dongping County, Tai'an, Shandong)",
        "weapon": "Steel alloy spear<br> (渾鐵點鋼槍);<br> Flying daggers<br> (飛刀)",
        "starVietnamese": "Thiên Phú Tinh <p>(天富 星)</p> ",
        "nicknameVietnamese": "Phác Thiên Bằng (chim bằng / đại bàng vút trời)",
        "nameVietnamese": "Lý Ứng",
        "designationVietnamese": "Quân Lương Lệnh Sử",
        "image": "011_thien phu tinh_phac thien bang_ly ung.jpg"
      },
      {
        "rank": "12",
        "star": "Tianman<br> (天滿);<br> Fulfillment Star<br> (天滿星)",
        "name": "Zhu Tong<br> (朱仝; Zhū Tóng; Chu T'ung)",
        "nickname": "\"Lord of the Beautiful Beard\"",
        "otherNames": "<br> ",
        "division": "Eight Tiger Cub Vanguard Generals (cavalry)",
        "designation": "<br> ",
        "origin": "Constable",
        "homePlace": "Yuncheng County, Heze, Shandong",
        "weapon": "Sabre",
        "starVietnamese": "Thiên Mãn Tinh <p>(天滿星)</p> ",
        "nicknameVietnamese": "Mỹ Nhiêm Công (ông tốt râu)",
        "nameVietnamese": "Chu Đồng",
        "designationVietnamese": "Mã Quân Bát Hổ Tiên Phong Sứ",
        "image": "012_thien man tinh_my nhiem cong_chu dong.jpg"
      },
      {
        "rank": "13",
        "star": "Tiangu<br> (天孤);<br> Solitary Star<br> (天孤星)",
        "name": "Lu Zhishen<br> (鲁智深; 魯智深; Lǔ Zhìshēn; Lu Chih-shen)",
        "nickname": "\"Flowery Monk\"<br> (花和尚)",
        "otherNames": "Lu Da<br> (魯達);<br> Major Lu<br> (魯提轄)",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Garrison major",
        "homePlace": "Weizhou (around present-day Pingliang, Gansu)",
        "weapon": "Monk's spade,<br> Dagger",
        "starVietnamese": "Thiên Cô Tinh <p>(天孤星)</p> ",
        "nicknameVietnamese": "Hoa Hòa Thượng (花和尚) <p>(sư xăm hoa)</p> ",
        "nameVietnamese": "Lỗ Trí Thâm, Lỗ Đạt <p>(魯智深, 魯達)</p> ",
        "designationVietnamese": "Mã Quân Thống Bộ Đầu Lĩnh",
        "image": "013_thien co tinh_hoa hoa thuong_lo tri tham.jpg"
      },
      {
        "rank": "14",
        "star": "Tianshang<br> (天傷);<br> Harm Star<br> (天傷星)",
        "name": "Wu Song<br> (武松; Wǔ Sōng; Wu Sung)",
        "nickname": "\"Pilgrim\"<br> (行者);<br> \"Tiger-fighting Hero\"<br> (打虎英雄)",
        "otherNames": "Chief Wu<br> (武都頭);<br> Grandmaster Qingzhong<br> (清忠祖師)<br> \"Wu the Second\"<br> (武二郎)",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Constable",
        "homePlace": "Qinghe County, Xingtai, Hebei",
        "weapon": "Pair of sabres,<br> staff",
        "starVietnamese": "Thiên Thương Tinh <p>(天傷星)</p> ",
        "nicknameVietnamese": "Hành Giả (行者) <p>(sư đi khuyến   thiện, khất thực)</p> ",
        "nameVietnamese": "Võ Tòng <p>(武松)</p> ",
        "designationVietnamese": "Mã Quân Thống Bộ Đầu Lĩnh",
        "image": "014_thien thuong tinh_hanh gia_vo tong.jpg"
      },
      {
        "rank": "15",
        "star": "Tianli<br> (天立);<br> Steadfast Star<br> (天立星)",
        "name": "Dong Ping<br> (董平; Dǒng Píng; Tung P'ing)",
        "nickname": "\"General of Double Spears\"<br> (雙槍將)",
        "otherNames": "\"Refined and Cultured General of Double Spears\"<br> (風流雙槍將)",
        "division": "Five Tiger Generals (cavalry)",
        "designation": "<br> ",
        "origin": "Imperial general",
        "homePlace": "Shangdang, Hedong<br> (around present-day Yuncheng, Shanxi)",
        "weapon": "Pair of spears",
        "starVietnamese": "Thiên Lập Tinh <p>(天立星)</p> ",
        "nicknameVietnamese": "Song Thương Tướng (雙鎗將) <p>(tướng hai   thương)</p> ",
        "nameVietnamese": "Đổng Bình (董 平)",
        "designationVietnamese": "",
        "image": "015_thien lap tinh_song thuong tuong_dong binh.jpg"
      },
      {
        "rank": "16",
        "star": "Tianjie<br> (天捷);<br> Agile Star<br> (天捷星)",
        "name": "Zhang Qing<br> (张清; 張清; Zhāng Qīng; Chang Ch'ing)",
        "nickname": "\"Featherless Arrow\"<br> (沒羽箭)",
        "otherNames": "<br> ",
        "division": "Eight Tiger Cub Vanguard Generals (cavalry)",
        "designation": "<br> ",
        "origin": "Imperial general",
        "homePlace": "Zhangde Prefecture<br> (present-day Anyang, Henan)",
        "weapon": "Spear,<br> Stones",
        "starVietnamese": "Thiên Tiệp Tinh <p>(天捷星)</p> ",
        "nicknameVietnamese": "Một Vũ Tiễn (沒羽箭) <p>(mũi tên không   lông)</p> ",
        "nameVietnamese": "Trương Thanh <p>(張清)</p> ",
        "designationVietnamese": "Mã Quân Bát Hổ Tiên Phong Sứ",
        "image": "016_thien tiep tinh_mot vu tien_truong thanh.jpg"
      },
      {
        "rank": "17",
        "star": "Tian'an<br> (天暗);<br> Dark Star<br> (天暗星)",
        "name": "Yang Zhi<br> (杨志; 楊志; Yáng Zhì; Yang Chih)",
        "nickname": "\"Blue Faced Beast\"<br> (青面獸)",
        "otherNames": "<br> ",
        "division": "Eight Tiger Cub Vanguard Generals (cavalry)",
        "designation": "<br> ",
        "origin": "Military officer",
        "homePlace": "Xintai, Linzhou (present-day Shenmu County, Yulin, Shaanxi)",
        "weapon": "Sabre,<br> Spear",
        "starVietnamese": "Thiên Ám Tinh <p>(天暗星)</p> ",
        "nicknameVietnamese": "Thanh Diện Thú (青面獸) <p>(thú mặt xanh)</p> ",
        "nameVietnamese": "Dương Chí <p>(楊志)</p> ",
        "designationVietnamese": "Mã Quân Bát Hổ Tiên Phong Sứ",
        "image": "017_thien am tinh_thanh dien thu_duong chi.jpg"
      },
      {
        "rank": "18",
        "star": "Tianyou<br> (天祐);<br> Guardian Star<br> (天祐星)",
        "name": "Xu Ning<br> (徐宁; 徐寧; Xú Níng; Hsü Ning)",
        "nickname": "\"Gold Lancer\"<br> (金槍手)",
        "otherNames": "<br> ",
        "division": "Eight Tiger Cub Vanguard Generals (cavalry)",
        "designation": "<br> ",
        "origin": "Instructor of Gold Lancers unit of the Imperial Army",
        "homePlace": "Henan",
        "weapon": "Hooked Lance<br> (鈎鐮槍)",
        "starVietnamese": "Thiên Hữu Tinh <p>(天祐星)</p> ",
        "nicknameVietnamese": "Kim Sang Thủ (金鎗手) <p>(tay câu vàng)</p> ",
        "nameVietnamese": "Từ Ninh <p>(徐寧)</p> ",
        "designationVietnamese": "Mã Quân Bát Hổ Tiên Phong Sứ",
        "image": "018_thien huu tinh_kim sang thu_tu ninh.jpg"
      },
      {
        "rank": "19",
        "star": "Tiankong<br> (天空);<br> Flight Star<br> (天空星)",
        "name": "Suo Chao<br> (索超; Suǒ Chāo; So Ch'ao)",
        "nickname": "\"Impatient Vanguard\"<br> (急先鋒)",
        "otherNames": "<br> ",
        "division": "Eight Tiger Cub Vanguard Generals (cavalry)",
        "designation": "<br> ",
        "origin": "Military officer",
        "homePlace": "Hebei",
        "weapon": "Golden Axe<br> (金蘸斧)",
        "starVietnamese": "Thiên Không Tinh <p>(天空星)</p> ",
        "nicknameVietnamese": "Cấp Tiên Phong (急先鋒) <p>(tiên phong nóng   tính)</p> ",
        "nameVietnamese": "Sách Siêu <p>(索超)</p> ",
        "designationVietnamese": "Mã Quân Bát Hổ Tiên Phong Sứ",
        "image": "019_thien khong tinh_cap tien phong_sach sieu.jpg"
      },
      {
        "rank": "20",
        "star": "Tiansu<br> (天速);<br> Speed Star<br> (天速星)",
        "name": "Dai Zong<br> (戴宗; Dài Zōng; Tai Tsung)",
        "nickname": "\"Magic Traveller\"<br> (神行太保)",
        "otherNames": "<br> ",
        "division": "Reconnaissance and intelligence",
        "designation": "Scouting chief",
        "origin": "Prison warden",
        "homePlace": "Jiangzhou (江州; present-day Jiujiang, Jiangxi)",
        "weapon": "Sword",
        "starVietnamese": "Thiên Tốc Tinh <p>(天速星)</p> ",
        "nicknameVietnamese": "Thần Hành Thái Bảo (神行太保) <p>(ông thủ từ đi   nhanh)</p> ",
        "nameVietnamese": "Đới Tung <p>(戴宗)</p> ",
        "designationVietnamese": "Tổng cục thăm dò tin tức",
        "image": "020_thien di tinh_xich phat quy_luu duong.jpg"
      },
      {
        "rank": "21",
        "star": "Tianyi<br> (天異);<br> Deviance Star<br> (天異星)",
        "name": "Liu Tang<br> (刘唐; 劉唐; Liú Táng; Liu T'ang)",
        "nickname": "\"Red Haired Devil\"<br> (赤髮鬼)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Illegal trader",
        "homePlace": "Dongluzhou<br> (東潞州; believed to be present-day Changzhi, Shanxi)",
        "weapon": "Pudao",
        "starVietnamese": "Thiên Dị Tinh <p>(天異星)</p> ",
        "nicknameVietnamese": "Xích Phát Quỷ (赤髪鬼) <p>(quỷ tóc đỏ)</p> ",
        "nameVietnamese": "Lưu Đường <p>(劉唐)</p> ",
        "designationVietnamese": "Bộ Quân Đầu Lĩnh",
        "image": "021_thien sat tinh_hac toan phong_ly quy.jpg"
      },
      {
        "rank": "22",
        "star": "Tiansha<br> (天殺);<br> Killer Star<br> (天殺星)",
        "name": "Li Kui<br> (李逵; Lǐ Kuí; Li K'uei)",
        "nickname": "\"Black Whirlwind\"<br> (黑旋風)",
        "otherNames": "\"Iron Ox\"<br> (鐵牛)",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Jailer",
        "homePlace": "Baizhang Village, Yishui County, Yizhou<br> (in present-day Linyi, Shandong)",
        "weapon": "Pair of axes,<br> Pudao",
        "starVietnamese": "Thiên Sát Tinh <p>(天殺星)</p> ",
        "nicknameVietnamese": "Hắc Toàn Phong (黑旋風) <p>(cơn lốc đen),</p> <p>Thiết Ngưu (鐵   牛)</p> <p>(máy kéo)</p> ",
        "nameVietnamese": "Lý Quỳ <p>(李逵)</p> ",
        "designationVietnamese": "Bộ Quân Đầu Lĩnh",
        "image": "022_thien toc tinh_than hanh thai bao_doi tung.jpg"
      },
      {
        "rank": "23",
        "star": "Tianwei<br> (天微);<br> Minute Star<br> (天微星)",
        "name": "Shi Jin<br> (史进; 史進; Shǐ Jìn; Shih Chin)",
        "nickname": "\"Nine Tattooed Dragons\"<br> (九紋龍)",
        "otherNames": "<br> ",
        "division": "Eight Tiger Cub Vanguard Generals (cavalry)",
        "designation": "<br> ",
        "origin": "Squire",
        "homePlace": "Huayin County (present-day Huayin, Weinan, Shaanxi)",
        "weapon": "Staff,<br> Pudao",
        "starVietnamese": "Thiên Vị Tinh <p>(天微星)</p> ",
        "nicknameVietnamese": "Cửu Văn Long (九紋龍) <p>(Người xăm Chín   con rồng)</p> ",
        "nameVietnamese": "Sử Tiến <p>(史進)</p> ",
        "designationVietnamese": "Mã Quân Bát Hổ Tiên Phong Sứ",
        "image": "023_thien vi tinh_cuu van long_su tien.jpg"
      },
      {
        "rank": "24",
        "star": "Tianjiu<br> (天究);<br> Investigative Star<br> (天究星)",
        "name": "Mu Hong<br> (穆弘; Mù Hóng; Mu Hung)",
        "nickname": "\"Unrestrained\"<br> (沒遮攔)",
        "otherNames": "<br> ",
        "division": "Eight Tiger Cub Vanguard Generals (cavalry)",
        "designation": "<br> ",
        "origin": "Rich man",
        "homePlace": "Jieyang Town (believed to be in present-day Jiujiang, Jiangxi)",
        "weapon": "Pudao",
        "starVietnamese": "Thiên Cứu Tinh <p>(天究星)</p> ",
        "nicknameVietnamese": "Một Già Lan (沒遮攔) <p>(không che giấu)</p> ",
        "nameVietnamese": "Mục Hoằng <p>(穆弘)</p> ",
        "designationVietnamese": "Mã Quân Bát Hổ Tiên Phong Sứ",
        "image": "024_thien cuu tinh_moc gia lan_muc hoang.jpg"
      },
      {
        "rank": "25",
        "star": "Tiantui<br> (天退);<br> Defence Star<br> (天退星)",
        "name": "Lei Heng<br> (雷横; 雷橫; Léi Héng; Lei Heng)",
        "nickname": "\"Winged Tiger\"<br> (插翅虎)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Blacksmith,<br> Constable",
        "homePlace": "Yuncheng County, Heze, Shandong",
        "weapon": "Pudao",
        "starVietnamese": "Thiên Thoái Tinh <p>(天退星)</p> ",
        "nicknameVietnamese": "Sáp Sí Hổ (挿翅虎) <p>(Hổ chắp cánh)</p> ",
        "nameVietnamese": "Lôi Hoành <p>(雷橫)</p> ",
        "designationVietnamese": "Bộ Quân Đầu Lĩnh",
        "image": "025_thien thoai tinh_sap si ho_loi hoanh.jpg"
      },
      {
        "rank": "26",
        "star": "Tianshou<br> (天壽);<br> Longevity Star<br> (天壽星)",
        "name": "Li Jun<br> (李俊; Lǐ Jùn; Li Chün)",
        "nickname": "\"River Dragon\"<br> (混江龍)",
        "otherNames": "<br> ",
        "division": "Navy",
        "designation": "Navy leader",
        "origin": "Ferryman",
        "homePlace": "Luzhou (present-day Hefei, Anhui)",
        "weapon": "Sword",
        "starVietnamese": "Thiên Thọ Tinh <p>(天壽星)</p> ",
        "nicknameVietnamese": "Hỗn Giang Long (混江龍) <p>(rồng quấy sông)</p> ",
        "nameVietnamese": "Lý Tuấn <p>(李俊)</p> ",
        "designationVietnamese": "Thủy Quân Đầu Lĩnh",
        "image": "026_thien tho tinh_hon giang long_ly tuan.jpg"
      },
      {
        "rank": "27",
        "star": "Tianjian<br> (天劍);<br> Sword Star<br> (天劍星)",
        "name": "Ruan Xiao'er<br> (阮小二; Ruǎn Xiǎo'èr; Juan Hsiao-erh)",
        "nickname": "\"Tai Sui Who Stands His Ground\"<br> (立地太歲)",
        "otherNames": "<br> ",
        "division": "Navy",
        "designation": "Navy leader",
        "origin": "Fisherman",
        "homePlace": "Shijie Village (in present-day Liangshan County, Jining, Shandong)",
        "weapon": "<br> ",
        "starVietnamese": "Thiên Kiếm Tinh <p>(天劍星)</p> ",
        "nicknameVietnamese": "Lập Địa Thái Tuế (立地太歲) <p>(thái tuế mở   đất)</p> ",
        "nameVietnamese": "Nguyễn Tiểu Nhị <p>(阮小二)</p> ",
        "designationVietnamese": "Thủy Quân Đầu Lĩnh",
        "image": "027_thien kiem tinh_lap dia thai tue_nguyen tieu nhi.jpg"
      },
      {
        "rank": "28",
        "star": "Tianping<br> (天平);<br> Balance Star<br> (天平星)",
        "name": "Zhang Heng<br> (张横; 張橫; Zhāng Héng; Chang Heng)",
        "nickname": "\"Boatman\"<br> (船火兒)",
        "otherNames": "<br> ",
        "division": "Navy",
        "designation": "Navy leader",
        "origin": "Pirate",
        "homePlace": "Xiaogushan (in present-day Susong County, Anqing, Anhui)",
        "weapon": "<br> ",
        "starVietnamese": "Thiên Bình Tinh <p>(天平星)</p> ",
        "nicknameVietnamese": "Thuyền Đầu Hoả (船火兒) <p>(lửa đầu thuyền)</p> ",
        "nameVietnamese": "Trương Hoành <p>(張橫)</p> ",
        "designationVietnamese": "Thủy Quân Đầu Lĩnh",
        "image": "028_thien binh tinh_thuyen dau hoa_truong hoanh.jpg"
      },
      {
        "rank": "29",
        "star": "Tianzui<br> (天罪);<br> Guilt Star<br> (天罪星)",
        "name": "Ruan Xiaowu<br> (阮小五; Ruǎn Xiǎowǔ; Juan Hsiao-wu)",
        "nickname": "\"Short-lived Second Brother\"<br> (短命二郎)",
        "otherNames": "<br> ",
        "division": "Navy",
        "designation": "Navy leader",
        "origin": "Fisherman",
        "homePlace": "Shijie Village (in present-day Liangshan County, Jining, Shandong)",
        "weapon": "<br> ",
        "starVietnamese": "Thiên Tội Tinh <p>(天罪星)</p> ",
        "nicknameVietnamese": "Đoản Mệnh Nhị Lang (短命二郎) <p>(chàng hai xấu   số)</p> ",
        "nameVietnamese": "Nguyễn Tiểu Ngũ <p>(阮小五)</p> ",
        "designationVietnamese": "Thủy Quân Đầu Lĩnh",
        "image": "029_thien toi tinh_doan menh tam lang_nguyen tieu ngu.jpg"
      },
      {
        "rank": "30",
        "star": "Tiansun<br> (天損);<br> Damage Star<br> (天損星)",
        "name": "Zhang Shun<br> (张顺; 張順; Zhāng Shùn; Chang Shun)",
        "nickname": "\"White Stripe in the Waves\"<br> (浪里白條)",
        "otherNames": "<br> ",
        "division": "Navy",
        "designation": "Navy leader",
        "origin": "Fisherman",
        "homePlace": "Xiaogushan (in present-day Susong County, Anqing, Anhui)",
        "weapon": "<br> ",
        "starVietnamese": "Thiên Tổn Tinh <p>(天損星)</p> ",
        "nicknameVietnamese": "Lãng Lý Bạch Điều (浪裏白條) <p>(lụa trắng trên   sóng)</p> ",
        "nameVietnamese": "Trương Thuận <p>(張順)</p> ",
        "designationVietnamese": "Thủy Quân Đầu Lĩnh",
        "image": "030_thien ton tinh_lang ly bach dieu_truong hoanh.jpg"
      },
      {
        "rank": "31",
        "star": "Tianbai<br> (天敗);<br> Defeat Star<br> (天敗星)",
        "name": "Ruan Xiaoqi<br> (阮小七; Ruǎn Xiǎoqī; Juan Hsiao-ch'i)",
        "nickname": "\"Living King Yama<br> (活閻羅)",
        "otherNames": "<br> ",
        "division": "Navy",
        "designation": "Navy leader",
        "origin": "Fisherman",
        "homePlace": "Shijie Village (in present-day Liangshan County, Jining, Shandong)",
        "weapon": "<br> ",
        "starVietnamese": "Thiên Bại Tinh <p>(天敗星)</p> ",
        "nicknameVietnamese": "Hoạt Diêm La (活閻羅) <p>(Diêm La sống)</p> ",
        "nameVietnamese": "Nguyễn Tiểu Thất <p>(阮小七)</p> ",
        "designationVietnamese": "Thủy Quân Đầu Lĩnh",
        "image": "031_thien dai tinh_hoat diem la_nguyent tieu that.jpg"
      },
      {
        "rank": "32",
        "star": "Tianlao<br> (天牢);<br> Secure Star<br> (天牢星)",
        "name": "Yang Xiong<br> (杨雄; 楊雄; Yáng Xióng; Yang Hsiung)",
        "nickname": "\"Sick Guan Suo\"<br> (病關索)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Prison warden and executioner",
        "homePlace": "Henan",
        "weapon": "<br> ",
        "starVietnamese": "Thiên Lao Tinh <p>(天牢星)</p> ",
        "nicknameVietnamese": "Bệnh Quan Sách (病關索) <p>(Quan Sách ốm)</p> ",
        "nameVietnamese": "Dương Hùng <p>(楊雄)</p> ",
        "designationVietnamese": "Bộ Quân Đầu Lĩnh",
        "image": "032_thien lao tinh_benh quan sach_duong hung.jpg"
      },
      {
        "rank": "33",
        "star": "Tianhui<br> (天慧);<br> Wisdom Star<br> (天慧星)",
        "name": "Shi Xiu<br> (石秀; Shí Xiù; Shih Hsiu)",
        "nickname": "\"Daredevil Third Brother\"<br> (拚命三郎)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Firewood seller",
        "homePlace": "Jiankang Prefecture, Jinling<br> (present-day Nanjing, Jiangsu)",
        "weapon": "<br> ",
        "starVietnamese": "Thiên Tuệ Tinh <p>(天慧星)</p> ",
        "nicknameVietnamese": "Phanh Mệnh Tam Lang (拚命三郎) <p>(chàng ba liều   mạng)</p> ",
        "nameVietnamese": "Thạch Tú <p>(石秀)</p> ",
        "designationVietnamese": "Bộ Quân Đầu Lĩnh",
        "image": "033_thien tue tinh_bien menh tam lang_thach tu.jpg"
      },
      {
        "rank": "34",
        "star": "Tianbao<br> (天暴);<br> Savage Star<br> (天暴星)",
        "name": "Xie Zhen<br> (解珍; Xiè Zhēn; Hsieh Chen)",
        "nickname": "\"Double-headed Serpent\"<br> (兩頭蛇)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Hunter",
        "homePlace": "Dengzhou<br> (in present-day eastern Shandong)",
        "weapon": "Bronze forked spear<br> (渾鐵點鋼叉)",
        "starVietnamese": "Thiên Bảo Tinh <p>(天暴星)</p> ",
        "nicknameVietnamese": "Lưỡng Đầu Xà (兩頭蛇) <p>(rắn hai đầu)</p> ",
        "nameVietnamese": "Giải Trân <p>(解珍)</p> ",
        "designationVietnamese": "Bộ Quân Đầu Lĩnh",
        "image": "034_thien bao tinh_luong dau xa_giai tran.jpg"
      },
      {
        "rank": "35",
        "star": "Tianku<br> (天哭);<br> Crying Star<br> (天哭星)",
        "name": "Xie Bao<br> (解宝; 解寶; Xiè Bǎo; Hsieh Pao)",
        "nickname": "\"Twin-tailed Scorpion\"<br> (雙尾蠍)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Hunter",
        "homePlace": "Dengzhou (in present-day eastern Shandong)",
        "weapon": "Bronze forked spear<br> (渾鐵點鋼叉)",
        "starVietnamese": "Thiên Khốc Tinh <p>(天哭星)</p> ",
        "nicknameVietnamese": "Song Vĩ Hạt (雙尾蠍) <p>(bọ cạp hai   đuôi)</p> ",
        "nameVietnamese": "Giải Bảo <p>(解寶)</p> ",
        "designationVietnamese": "Bộ Quân Đầu Lĩnh",
        "image": "035_thien khoc tinh_song vi hat_giai bao.jpg"
      },
      {
        "rank": "36",
        "star": "Tianqiao<br> (天巧);<br> Skilful Star<br> (天巧星)",
        "name": "Yan Qing<br> (燕青; Yàn Qīng; Yen Ch'ing)",
        "nickname": "\"Prodigal\" / \"Wanderer\"<br> (浪子)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Lu Junyi's steward",
        "homePlace": "Daming Prefecture<br> (in present-day Handan, Hebei)",
        "weapon": "Crossbow",
        "starVietnamese": "Thiên Xảo Tinh <p>(天巧星)</p> ",
        "nicknameVietnamese": "Lãng Tử (浪子) <p>(tay chơi)</p> ",
        "nameVietnamese": "Yến Thanh <p>(燕青)</p> ",
        "designationVietnamese": "Bộ Quân Đầu Lĩnh",
        "image": "036_thien xao tinh_lang tu_yen thanh.jpg"
      },
      {
        "rank": "37",
        "star": "Dikui<br> (地魁);<br> Leader Star<br> (地魁星)",
        "name": "Zhu Wu<br> (朱武; Zhū Wǔ; Chu Wu)",
        "nickname": "\"Resourceful Strategist\"<br> (神機軍師)",
        "otherNames": "<br> ",
        "division": "Strategist",
        "designation": "Strategist",
        "origin": "Bandit leader",
        "homePlace": "Dingyuan (present-day Dingyuan County, Chuzhou, Anhui)",
        "weapon": "Pair of swords",
        "starVietnamese": "Địa Khôi Tinh",
        "nicknameVietnamese": "Thần Cơ Quân Sư (quân sư giỏi kế)",
        "nameVietnamese": "Chu Vũ",
        "designationVietnamese": "",
        "image": "037_dia khoi tinh_than co quan su_chu vu.jpg"
      },
      {
        "rank": "38",
        "star": "Disha<br> (地煞);<br> Malignant Star<br> (地煞星)",
        "name": "Huang Xin<br> (黄信; 黃信; Huáng Xìn; Huang Hsin)",
        "nickname": "\"Guardian of Three Mountains\"<br> (鎮三山)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Imperial general",
        "homePlace": "Qingzhou (in present-day Shandong)",
        "weapon": "Sword of Death<br> (喪門劍)",
        "starVietnamese": "Địa Sát Tinh",
        "nicknameVietnamese": "Trấn Tam Sơn (trấn ba núi)",
        "nameVietnamese": "Hoàng Tín",
        "designationVietnamese": "",
        "image": "038_dia sat tinh_tran tam son_hoang tin.jpg"
      },
      {
        "rank": "39",
        "star": "Diyong<br> (地勇);<br> Brave Star<br> (地勇星)",
        "name": "Sun Li<br> (孙立; 孫立; Sūn Lì; Sun Li)",
        "nickname": "\"Sick Yuchi\"<br> (病尉遲)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Garrison major",
        "homePlace": "Qiongzhou<br> (present-day Hainan)",
        "weapon": "Spear,<br> Steel clubs",
        "starVietnamese": "Địa Dũng Tinh",
        "nicknameVietnamese": "Bệnh Uý Trì (Uý Trì ốm) ",
        "nameVietnamese": "Tôn Lập",
        "designationVietnamese": "",
        "image": "039_dia dung tinh_benh uy tri_ton lap.jpg"
      },
      {
        "rank": "40",
        "star": "Dijie<br> (地傑);<br> Prominence Star<br> (地傑星)",
        "name": "Xuan Zan<br> (宣赞; 宣贊; Xuān Zàn; Hsüan Tsan)",
        "nickname": "\"Ugly Prince Consort\"<br> (醜郡馬)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Military officer",
        "homePlace": "<br> ",
        "weapon": "Sabre",
        "starVietnamese": "Địa Kiệt Tinh",
        "nicknameVietnamese": "Xú Quận Mã",
        "nameVietnamese": "Tuyên Tán",
        "designationVietnamese": "",
        "image": "040_dia kiet tinh_xu quan ma_tuyen tan.jpg"
      },
      {
        "rank": "41",
        "star": "Dixiong<br> (地雄);<br> Magnificent Star<br> (地雄星)",
        "name": "Hao Siwen<br> (郝思文; Hǎo Sīwén; Hao Szu-wen)",
        "nickname": "\"Wood Dog of Well\"<br> (井木犴)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Imperial general",
        "homePlace": "<br> ",
        "weapon": "<br> ",
        "starVietnamese": "Địa Hùng Tinh",
        "nicknameVietnamese": "Tỉnh Mộc Hãn (chó ngao đen)",
        "nameVietnamese": "Hác Tư Văn",
        "designationVietnamese": "",
        "image": "041_dia hung tinh_moc tinh can_hac tu van.jpg"
      },
      {
        "rank": "42",
        "star": "Diwei<br> (地威);<br> Majestic Star<br> (地威星)",
        "name": "Han Tao<br> (韩滔; 韓滔; Hán Tāo; Han T'ao)",
        "nickname": "\"General of a Hundred Victories\"<br> (百勝將)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Imperial drill instructor",
        "homePlace": "Dongjing<br> (present-day Kaifeng, Henan)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Uy Tinh",
        "nicknameVietnamese": "Bách Thắng Tướng",
        "nameVietnamese": "Hàn Thao",
        "designationVietnamese": "",
        "image": "042_dia uy tinh_bach thang tuong_han thao.jpg"
      },
      {
        "rank": "43",
        "star": "Diying<br> (地英);<br> Hero Star<br> (地英星)",
        "name": "Peng Qi<br> (彭玘; Péng Qǐ; P'eng Ch'i)",
        "nickname": "\"General of Heavenly Vision\"<br> (天目將)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Imperial drill instructor",
        "homePlace": "Dongjing<br> (present-day Kaifeng, Henan)",
        "weapon": "Sabre<br> (三尖兩刃刀)",
        "starVietnamese": "Địa Anh Tinh",
        "nicknameVietnamese": "Thiên Mục Tướng (tướng mắt trời)",
        "nameVietnamese": "Bành Kỷ",
        "designationVietnamese": "",
        "image": "043_dia anh tinh_thien muc tuong_banh di.jpg"
      },
      {
        "rank": "44",
        "star": "Diqi<br> (地奇);<br> Unique Star<br> (地奇星)",
        "name": "Shan Tinggui<br> (单廷圭; 單廷珪; Shàn Tíngguī; Shan T'ing-kui)",
        "nickname": "\"General of Sacred Water\"<br> (聖水將)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Imperial drill instructor",
        "homePlace": "Lingzhou (present-day Ling County, Dezhou, Shandong)",
        "weapon": "Black spear,<br> Bow and arrows",
        "starVietnamese": "Địa Kỳ Tinh",
        "nicknameVietnamese": "Thánh Thủy Tướng Quân (tướng thánh nước)",
        "nameVietnamese": "Đan Đình Khuê",
        "designationVietnamese": "",
        "image": "044_dia ky tinh_thanh thuy tuong quan_dan dinh khue.jpg"
      },
      {
        "rank": "45",
        "star": "Dimeng<br> (地猛);<br> Fierce Star<br> (地猛星)",
        "name": "Wei Dingguo<br> (魏定国; 魏定國; Wèi Dìngguó; Wei Ting-kuo)",
        "nickname": "\"General of Holy Fire\"<br> (神火將)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Imperial drill instructor",
        "homePlace": "Lingzhou<br> (present-day Ling County, Dezhou, Shandong)",
        "weapon": "Sabre,<br> Bow and arrows",
        "starVietnamese": "Địa Mãnh Tinh",
        "nicknameVietnamese": "Thần Hoả Tướng Quân (tướng thần lửa)",
        "nameVietnamese": "Ngụy Định Quốc",
        "designationVietnamese": "",
        "image": "045_dia manh tinh_than hoa tuong quan_nguy dinh quoc.jpg"
      },
      {
        "rank": "46",
        "star": "Diwen<br> (地文);<br> Literature Star<br> (地文星)",
        "name": "Xiao Rang<br> (萧让; 蕭讓; Xiāo Ràng; Hsiao Jang)",
        "nickname": "\"Sacred Handed Scholar\"<br> (聖手書生)",
        "otherNames": "<br> ",
        "division": "<br> ",
        "designation": "Chief secretary",
        "origin": "Scholar and calligrapher",
        "homePlace": "Jizhou (around present-day Jining and Heze, Shandong)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Văn Tinh",
        "nicknameVietnamese": "Thánh Thủ Thư Sinh (học trò chữ đẹp)",
        "nameVietnamese": "Tiêu Nhượng",
        "designationVietnamese": "",
        "image": "046_dia van tinh_thanh thu thu sinh_tieu nhuong.jpg"
      },
      {
        "rank": "47",
        "star": "Dizheng<br> (地正);<br> Upright Star<br> (地正星)",
        "name": "Pei Xuan<br> (裴宣; Péi Xuān; P'ei Hsüan)",
        "nickname": "\"Iron Faced Magistrate's Clerk\"<br> (鐵面孔目)",
        "otherNames": "<br> ",
        "division": "<br> ",
        "designation": "Chief Justice",
        "origin": "Magistrate",
        "homePlace": "Jingzhao Prefecture (around present-day Xi'an, Shaanxi)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Chính Tinh",
        "nicknameVietnamese": "Thiết Diện Khổng Mục (quan toà mặt sắt)",
        "nameVietnamese": "Bùi Tuyên",
        "designationVietnamese": "",
        "image": "047_dia chinh tinh_thiet dien khong muc_bui tuyen.jpg"
      },
      {
        "rank": "48",
        "star": "Dikuo<br> (地闊);<br> Wide Star<br> (地闊星)",
        "name": "Ou Peng<br> (欧鹏; 歐鵬; Ōu Péng; Ou P'eng)",
        "nickname": "\"Golden Wings Brushing Against the Clouds\"<br> (摩雲金翅)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Bandit leader",
        "homePlace": "Huangzhou (in present-day Huanggang, Hubei)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Khoát Tinh",
        "nicknameVietnamese": "Ma Vân Kim Sí (chim cắt luồn mây)",
        "nameVietnamese": "Âu Bằng",
        "designationVietnamese": "",
        "image": "048_dia tich tinh_ma van kim si_au bang.jpg"
      },
      {
        "rank": "49",
        "star": "Dihe<br> (地闔);<br> Whole Star<br> (地闔星)",
        "name": "Deng Fei<br> (邓飞; 鄧飛; Dèng Fēi; Teng Fei)",
        "nickname": "\"Fiery Eyed Suan-ni\"<br> (火眼狻猊)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Bandit leader",
        "homePlace": "Xiangyang, Hubei",
        "weapon": "Iron chain with spikes",
        "starVietnamese": "Địa Hạp Tinh",
        "nicknameVietnamese": "Hoả Nhãn Toan Nghê (sư tử mắt lửa)",
        "nameVietnamese": "Đặng Phi",
        "designationVietnamese": "",
        "image": "049_dia hap tinh_hoa nhon toan nghe_dang phi.jpg"
      },
      {
        "rank": "50",
        "star": "Diqiang<br> (地強);<br> Strong Star<br> (地強星)",
        "name": "Yan Shun<br> (燕顺; 燕順; Yàn Shùn; Yen Shun)",
        "nickname": "\"Multicoloured Tiger\"<br> (錦毛虎)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Bandit leader",
        "homePlace": "Laizhou (around present-day Yantai, Shandong)",
        "weapon": "Sabre",
        "starVietnamese": "Địa Cường Tinh",
        "nicknameVietnamese": "Cẩm Mao Hổ (hổ lông gấm)",
        "nameVietnamese": "Yến Thuận",
        "designationVietnamese": "",
        "image": "050_dia cuong tinh_cam mao ho_yen thuan.jpg"
      },
      {
        "rank": "51",
        "star": "Di'an<br> (地暗);<br> Dark Star<br> (地暗星)",
        "name": "Yang Lin<br> (杨林; 楊林; Yáng Lín; Yang Lin)",
        "nickname": "\"Multicoloured Leopard\"<br> (錦豹子)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Wandering outlaw",
        "homePlace": "Zhangde Prefecture<br> (present-day Anyang, Henan)",
        "weapon": "Iron spear",
        "starVietnamese": "Địa Âm Tinh",
        "nicknameVietnamese": "Cẩm Báo Tử (báo gấm)",
        "nameVietnamese": "Dương Lâm",
        "designationVietnamese": "",
        "image": "051_dia am tinh_cam bao tu_duong lam.jpg"
      },
      {
        "rank": "52",
        "star": "Difu<br> (地輔);<br> Assist Star<br> (地輔星)",
        "name": "Ling Zhen<br> (凌振; Líng Zhèn; Ling Chen)",
        "nickname": "\"Heaven Shaking Thunder\"<br> (轟天雷)",
        "otherNames": "<br> ",
        "division": "Pyrotechnics",
        "designation": "Pyrotechnics unit commander",
        "origin": "<br> ",
        "homePlace": "Yanling (believed to be present-day Yanling County, Xuchang, Henan)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Phụ Tinh",
        "nicknameVietnamese": "Oanh Thiên Lôi (tiếng sét vang trời)",
        "nameVietnamese": "Lăng Chấn",
        "designationVietnamese": "",
        "image": "052_dia phu tinh_oanh thien loi_lang chan.jpg"
      },
      {
        "rank": "53",
        "star": "Dihui<br> (地會);<br> Meet Star<br> (地會星)",
        "name": "Jiang Jing<br> (蒋敬; 蔣敬; Jiǎng Jìng; Chiang Ching)",
        "nickname": "\"Divine Mathematician\"<br> (神算子)",
        "otherNames": "<br> ",
        "division": "Logistics",
        "designation": "Accountant",
        "origin": "Bandit leader",
        "homePlace": "Tanzhou, Hunan",
        "weapon": "<br> ",
        "starVietnamese": "Địa Hội Tinh",
        "nicknameVietnamese": "Thần Toán Tử (người giỏi tính kế)",
        "nameVietnamese": "Tưởng Kính",
        "designationVietnamese": "",
        "image": "053_dia hoi tinh_than toan tu_tuong kinh.jpg"
      },
      {
        "rank": "54",
        "star": "Dizuo<br> (地佐);<br> Aid Star<br> (地佐星)",
        "name": "Lü Fang<br> (吕方; 呂方; Lǚ Fāng; Lü Fang)",
        "nickname": "\"Little Marquis of Wen\"<br> (小溫侯)",
        "otherNames": "<br> ",
        "division": "Cavalry",
        "designation": "Central Camp Defendant General",
        "origin": "Bandit leader",
        "homePlace": "Tanzhou (around present-day Changsha, Hunan)",
        "weapon": "Sky Piercer<br> (方天畫戟)",
        "starVietnamese": "Địa Tá Tinh",
        "nicknameVietnamese": "Tiểu Ôn Hầu (Ôn hầu nhỏ)",
        "nameVietnamese": "Lã Phương",
        "designationVietnamese": "",
        "image": "054_dia ta tinh_tieu on hau_la phuong.jpg"
      },
      {
        "rank": "55",
        "star": "Diyong<br> (地佑);<br> Help Star<br> (地佑星)",
        "name": "Guo Sheng<br> (郭盛; Guō Shèng; Kuo Sheng)",
        "nickname": "\"Comparable to Rengui\"<br> (賽仁貴)",
        "otherNames": "<br> ",
        "division": "Cavalry",
        "designation": "Central Camp Defendant General",
        "origin": "Bandit",
        "homePlace": "Jialing (present-day Jialing District, Nanchong, Sichuan)",
        "weapon": "\"Sky Piercer\"<br> (方天畫戟)",
        "starVietnamese": "Địa Hựu Tinh",
        "nicknameVietnamese": "Trại Nhân Quý (giống Nhân Quý )",
        "nameVietnamese": "Quách Thịnh",
        "designationVietnamese": "",
        "image": "055_dia huu tinh_kien nhan quy_quach thinh.jpg"
      },
      {
        "rank": "56",
        "star": "Diling<br> (地靈);<br> Efficacious Star<br> (地靈星)",
        "name": "An Daoquan<br> (安道全; Ān Dàoquán; An Tao-ch'üan)",
        "nickname": "\"Divine Physician\"<br> (神醫)",
        "otherNames": "<br> ",
        "division": "Medical",
        "designation": "Physician",
        "origin": "Physician",
        "homePlace": "Jiankang Prefecture<br> (present-day Nanjing, Jiangsu)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Linh Tinh",
        "nicknameVietnamese": "Thần Y (thầy thuốc giỏi)",
        "nameVietnamese": "An Đạo Toàn",
        "designationVietnamese": "",
        "image": "056_dia linh tinh_than y_an dao toan.jpg"
      },
      {
        "rank": "57",
        "star": "Dishou<br> (地獸);<br> Beast Star<br> (地獸星)",
        "name": "Huangfu Duan<br> (皇甫端; Huángfǔ Duān; Huang-fu Tuan)",
        "nickname": "\"Purple Bearded Count\"<br> (紫髯伯)",
        "otherNames": "<br> ",
        "division": "Medical",
        "designation": "Veterinarian",
        "origin": "Veterinarian",
        "homePlace": "Youzhou<br> (present-day Beijing)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Thú Tinh",
        "nicknameVietnamese": "Tử Nhiêm Bá (ông râu tía)",
        "nameVietnamese": "Hoàng Phủ Đoan",
        "designationVietnamese": "",
        "image": "057_dia thu tinh_tu nhiem ba_hoang phu dan.jpg"
      },
      {
        "rank": "58",
        "star": "Diwei<br> (地微);<br> Minute Star<br> (地微星)",
        "name": "Wang Ying<br> (王英; Wáng Yīng; Wang Ying)",
        "nickname": "\"Stumpy Tiger\"<br> (矮腳虎)",
        "otherNames": "<br> ",
        "division": "Cavalry",
        "designation": "Cavalry leader",
        "origin": "Bandit leader",
        "homePlace": "Huai River region",
        "weapon": "<br> ",
        "starVietnamese": "Địa Vi Tinh",
        "nicknameVietnamese": "Nuỵ Cước Hổ (hổ chân ngắn)",
        "nameVietnamese": "Vương Anh",
        "designationVietnamese": "",
        "image": "058_dia vi tinh_nuy cuoc ho_vuong anh.jpg"
      },
      {
        "rank": "59",
        "star": "Dihui<br> (地慧);<br> Bright Star<br> (地慧星)",
        "name": "Hu Sanniang<br> (扈三娘; Hù Sānniáng; Hu San-niang)",
        "nickname": "\"Ten Feet of Blue\"<br> (一丈青)",
        "otherNames": "<br> ",
        "division": "Cavalry",
        "designation": "Cavalry leader",
        "origin": "<br> ",
        "homePlace": "Yunzhou, Zhongshan Prefecture (around present-day Dongping County, Tai'an, Shandong)",
        "weapon": "Pair of sabres,<br> Lasso",
        "starVietnamese": "Địa Tuệ Tinh",
        "nicknameVietnamese": "Nhất Trượng Thanh (một trượng xanh)",
        "nameVietnamese": "Hổ Tam Nương",
        "designationVietnamese": "",
        "image": "059_dia tue tinh_nhat truong thanh_ho tam nuong.jpg"
      },
      {
        "rank": "60",
        "star": "Dibao<br> (地暴);<br> Savage Star<br> (地暴星)",
        "name": "Bao Xu<br> (鲍旭; 鮑旭; Bào Xù; Pao Hsü)",
        "nickname": "\"God of Death\"<br> (喪門神)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Bandit leader",
        "homePlace": "Kouzhou (believed to be present-day Guan County, Liaocheng, Shandong)",
        "weapon": "Sword<br> (闊刃劍)",
        "starVietnamese": "Địa Hao Tinh",
        "nicknameVietnamese": "Tang Môn Thần (thần cửa nhà táng)",
        "nameVietnamese": "Bào Húc",
        "designationVietnamese": "",
        "image": "060_dia hao tinh_tang mon than_dao huc.jpg"
      },
      {
        "rank": "61",
        "star": "Diran<br> (地然);<br> Correct Star<br> (地然星)",
        "name": "Fan Rui<br> (樊瑞; Fán Ruì; Fan Jui)",
        "nickname": "\"Demon King of Chaos\"<br> (混世魔王)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Bandit leader",
        "homePlace": "Puzhou<br> (in present-day Chongqing)",
        "weapon": "Chain spiked mace<br> (流星槌)",
        "starVietnamese": "Địa Mặc Tinh",
        "nicknameVietnamese": "Hỗn Thế Ma Vương (ma vương càn quấy)",
        "nameVietnamese": "Phàn Thụy",
        "designationVietnamese": "",
        "image": "061_dia mac tinh_hon the ma vuong_phan thuy.jpg"
      },
      {
        "rank": "62",
        "star": "Dichang<br> (地猖);<br> Wild Star<br> (地猖星)",
        "name": "Kong Ming<br> (孔明; Kǒng Míng; K'ung Ming)",
        "nickname": "\"Hairy Star\"<br> (毛頭星)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Central Camp Defendant General",
        "origin": "Bandit leader",
        "homePlace": "Qingzhou<br> (in present-day Shandong)",
        "weapon": "Spear",
        "starVietnamese": "Địa Xương Tinh",
        "nicknameVietnamese": "Mao Đẩu Tinh (sao nhỏ)",
        "nameVietnamese": "Khổng Minh",
        "designationVietnamese": "",
        "image": "062_dia xuong tinh_mao dau tinh_khong minh.jpg"
      },
      {
        "rank": "63",
        "star": "Dikuang<br> (地狂);<br> Crazy Star<br> (地狂星)",
        "name": "Kong Liang<br> (孔亮; Kǒng Liàng; K'ung Liang)",
        "nickname": "\"Lonely Fiery Star\"<br> (獨火星)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Central Camp Defendant General",
        "origin": "Bandit leader",
        "homePlace": "Qingzhou<br> (in present-day Shandong)",
        "weapon": "Spear",
        "starVietnamese": "Địa Cuồng Tinh",
        "nicknameVietnamese": "Độc Hoả Tinh (sao lửa)",
        "nameVietnamese": "Khổng Lượng",
        "designationVietnamese": "",
        "image": "063_dia cuong tinh_doc hoa tinh_khong luong.jpg"
      },
      {
        "rank": "64",
        "star": "Difei<br> (地飛);<br> Flying Star<br> (地飛星)",
        "name": "Xiang Chong<br> (项充; 項充; Xiàng Chōng; Hsiang Ch'ung)",
        "nickname": "\"Eight-armed Nezha\"<br> (八臂哪吒)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Bandit leader",
        "homePlace": "Pei County, Xuzhou",
        "weapon": "Spear,<br> Flying daggers",
        "starVietnamese": "Địa Phi Tinh",
        "nicknameVietnamese": "Bát Tý Na Tra (Na Tra 8 tay)",
        "nameVietnamese": "Hạng Sung",
        "designationVietnamese": "",
        "image": "064_dia phi tinh_bat ty na tra_hang sung.jpg"
      },
      {
        "rank": "65",
        "star": "Dizou<br> (地走);<br> Walking Star<br> (地走星)",
        "name": "Li Gun<br> (李衮; 李袞; Lǐ Gǔn; Li Kun)",
        "nickname": "\"Sky Soaring Great Sage\"<br> (飛天大聖)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Bandit leader",
        "homePlace": "Pei County, Xuzhou",
        "weapon": "Sword,<br> Javelins",
        "starVietnamese": "Địa Tẩu Tinh",
        "nicknameVietnamese": "Phi Thiên Đại Thánh (Đại Thánh về trời)",
        "nameVietnamese": "Lý Cổn",
        "designationVietnamese": "",
        "image": "065_dia tau tinh_phi thien dai thanh_ly con.jpg"
      },
      {
        "rank": "66",
        "star": "Diqiao<br> (地巧);<br> Skilful Star<br> (地巧星)",
        "name": "Jin Dajian<br> (金大坚; 金大堅; Jīn Dàjiān; Chin Ta-chien)",
        "nickname": "\"Jade Armed Craftsman\"<br> (玉臂匠)",
        "otherNames": "<br> ",
        "division": "<br> ",
        "designation": "Head craftsman",
        "origin": "Craftsman",
        "homePlace": "Jizhou (around present-day Jining and Heze, Shandong)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Xảo Tinh",
        "nicknameVietnamese": "Ngọc Tý Tượng (tay thợ ngọc)",
        "nameVietnamese": "Kim Đại Kiện",
        "designationVietnamese": "",
        "image": "066_dia xao tinh_ngoc ty tuong_kim dai kien.jpg"
      },
      {
        "rank": "67",
        "star": "Diming<br> (地明);<br> Bright Star<br> (地明星)",
        "name": "Ma Lin<br> (马麟; 馬麟; Mǎ Lín; Ma Lin)",
        "nickname": "\"Iron Flute Deity\"<br> (鐵笛仙)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Bandit leader",
        "homePlace": "Jiankang Prefecture<br> (present-day Nanjing, Jiangsu)",
        "weapon": "Pair of sabres",
        "starVietnamese": "Địa Minh Tinh",
        "nicknameVietnamese": "Thiết Địch Tiên (tiên thổi sáo sắt)",
        "nameVietnamese": "Mã Lân",
        "designationVietnamese": "",
        "image": "067_dia minh tinh_thiet dich tien_ma lan.jpg"
      },
      {
        "rank": "68",
        "star": "Dijin<br> (地進);<br> Forward Star<br> (地進星)",
        "name": "Tong Wei<br> (童威; Tóng Wēi; T'ung Wei)",
        "nickname": "\"Dragon Emerging from a Cave\"<br> (出洞蛟)",
        "otherNames": "<br> ",
        "division": "Navy",
        "designation": "Navy leader",
        "origin": "Salt trader",
        "homePlace": "Jieyang Ridge (believed to be in present-day Jiujiang, Jiangxi)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Tiến Tinh",
        "nicknameVietnamese": "Xuất Động Giao (cá sấu rời động)",
        "nameVietnamese": "Đồng Uy",
        "designationVietnamese": "",
        "image": "068_dia tien tinh_xuat dong giao_dong uy.jpg"
      },
      {
        "rank": "69",
        "star": "Ditui<br> (地退);<br> Retreating Star<br> (地退星)",
        "name": "Tong Meng<br> (童猛; Tóng Měng; T'ung Meng)",
        "nickname": "\"River Churning Clam\"<br> (翻江蜃)",
        "otherNames": "<br> ",
        "division": "Navy",
        "designation": "Navy leader",
        "origin": "Salt trader",
        "homePlace": "Jieyang Ridge (believed to be in present-day Jiujiang, Jiangxi)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Thoái Tinh",
        "nicknameVietnamese": "Phiên Giang Thẩn (sò khuấy nước)",
        "nameVietnamese": "Đồng Mãnh",
        "designationVietnamese": "",
        "image": "069_dia thoai tinh_phan giang than_dong manh.jpg"
      },
      {
        "rank": "70",
        "star": "Diman<br> (地滿);<br> Full Star<br> (地滿星)",
        "name": "Meng Kang<br> (孟康; Mèng Kāng; Meng K'ang)",
        "nickname": "\"Jade Flagpole\"<br> (玉幡竿)",
        "otherNames": "<br> ",
        "division": "<br> ",
        "designation": "Chief ship builder",
        "origin": "Bandit leader",
        "homePlace": "Zhending Prefecture (around present-day Zhengding County, Shijiazhuang, Hebei)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Mãn Tinh",
        "nicknameVietnamese": "Ngọc Phan Cang (cán cờ ngọc)",
        "nameVietnamese": "Mạnh Khang",
        "designationVietnamese": "",
        "image": "070_dia man tinh_ngoc phan cang_manh khang.jpg"
      },
      {
        "rank": "71",
        "star": "Disui<br> (地遂);<br> Succeed Star<br> (地遂星)",
        "name": "Hou Jian<br> (侯健; Hóu Jiàn; Hou Chien)",
        "nickname": "\"Long Armed Ape\"<br> (通臂猿)",
        "otherNames": "<br> ",
        "division": "<br> ",
        "designation": "Chief tailor",
        "origin": "Tailor",
        "homePlace": "Hongdu<br> (present-day Nanchang, Jiangxi)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Toại Tinh",
        "nicknameVietnamese": "Thông Tý Viên (vượn tay dài)",
        "nameVietnamese": "Hầu Kiện",
        "designationVietnamese": "",
        "image": "071_dia toai tinh_thong ty vien_hau kien.jpg"
      },
      {
        "rank": "72",
        "star": "Dizhou<br> (地周);<br> Complete Star<br> (地周星)",
        "name": "Chen Da<br> (陈达; 陳達; Chén Dá; Ch'en Ta)",
        "nickname": "\"Stream Leaping Tiger\"<br> (跳澗虎)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Bandit leader",
        "homePlace": "Ye<br> (in present-day Handan, Hebei)",
        "weapon": "Iron spear",
        "starVietnamese": "Địa Chu Tinh",
        "nicknameVietnamese": "Khiêu Giản Hổ (hổ nhảy khe)",
        "nameVietnamese": "Trần Đạt",
        "designationVietnamese": "",
        "image": "072_dia chu tinh_khieu gian ho_tran dat.jpg"
      },
      {
        "rank": "73",
        "star": "Diyin<br> (地隱);<br> Latent Star<br> (地隱星)",
        "name": "Yang Chun<br> (杨春; 楊春; Yáng Chūn; Yang Ch'un)",
        "nickname": "\"White Flower Serpent\"<br> (白花蛇)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Bandit leader",
        "homePlace": "Jieliang, Puzhou (present-day Jiezhou Town, Yanhu District, Yuncheng, Shanxi)",
        "weapon": "Sabre",
        "starVietnamese": "Địa Ẩn Tinh",
        "nicknameVietnamese": "Bạch Hoa Xà (rắn hoa trắng)",
        "nameVietnamese": "Dương Xuân",
        "designationVietnamese": "",
        "image": "073_dia an tinh_bach hoa xa_duong xuan.jpg"
      },
      {
        "rank": "74",
        "star": "Diyi<br> (地異);<br> Different Star<br> (地異星)",
        "name": "Zheng Tianshou<br> (郑天寿; 鄭天壽; Zhèng Tiānshòu; Cheng T'ien-shou)",
        "nickname": "\"Fair Skinned Gentleman\"<br> (白面郎君)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Bandit leader",
        "homePlace": "Suzhou, Jiangsu",
        "weapon": "<br> ",
        "starVietnamese": "Địa Di Tinh",
        "nicknameVietnamese": "Bạch Diện Lang Quân (anh mặt trắng)",
        "nameVietnamese": "Trịnh Thiên Thọ",
        "designationVietnamese": "",
        "image": "074_dia di tinh_bach dien lang quan_trinh thien tho.jpg"
      },
      {
        "rank": "75",
        "star": "Dili<br> (地理);<br> Manage Star<br> (地理星)",
        "name": "Tao Zongwang<br> (陶宗旺; Táo Zōngwàng; T'ao Tsung-wang)",
        "nickname": "\"Nine Tailed Turtle\"<br> (九尾龜)",
        "otherNames": "<br> ",
        "division": "<br> ",
        "designation": "Construction supervisor",
        "origin": "Bandit leader",
        "homePlace": "Guangzhou (around present-day Huangchuan County, Xinyang, Henan)",
        "weapon": "Iron shovel",
        "starVietnamese": "Địa Lý Tinh",
        "nicknameVietnamese": "Cửu Vĩ Quy (rùa chín đuôi)",
        "nameVietnamese": "Đào Tông Vượng",
        "designationVietnamese": "",
        "image": "075_dia ly tinh_cuu vy quy_dao ton vuong.jpg"
      },
      {
        "rank": "76",
        "star": "Dijun<br> (地俊);<br> Handsome Star<br> (地俊星)",
        "name": "Song Qing<br> (宋清; Sòng Qīng; Sung Ch'ing)",
        "nickname": "\"Iron Fan\"<br> (鐵扇子)",
        "otherNames": "<br> ",
        "division": "<br> ",
        "designation": "Banquet organiser",
        "origin": "Farmer",
        "homePlace": "Yuncheng County, Heze, Shandong",
        "weapon": "<br> ",
        "starVietnamese": "Địa Tuấn Tinh",
        "nicknameVietnamese": "Thiết Phiến Tử (tay quạt sắt)",
        "nameVietnamese": "Tống Thanh",
        "designationVietnamese": "",
        "image": "076_dia tuan tinh_thiet phien tu_tong thanh.jpg"
      },
      {
        "rank": "77",
        "star": "Diyue<br> (地樂);<br> Music Star<br> (地樂星)",
        "name": "Yue He<br> (乐和; 樂和; Yuè Hé; Yüeh He)",
        "nickname": "\"Iron Whistle\"<br> (鐵叫子)",
        "otherNames": "<br> ",
        "division": "Reconnaissance and intelligence",
        "designation": "Infantry scouting leader",
        "origin": "Jailer",
        "homePlace": "Maozhou<br> (present-day Changyi, Weifang, Shandong)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Nhạc Tinh",
        "nicknameVietnamese": "Thiết Khiếu Tử (tay sáo sắt)",
        "nameVietnamese": "Nhạc Hoà",
        "designationVietnamese": "",
        "image": "077_dia nhac tinh_thiet khieu tu_nhac hoa.jpg"
      },
      {
        "rank": "78",
        "star": "Dijie<br> (地捷);<br> Victorious Star<br> (地捷星)",
        "name": "Gong Wang<br> (龚旺; 龔旺; Gōng Wàng; Kung Wang)",
        "nickname": "\"Flowery Necked Tiger\"<br> (花項虎)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Imperial general",
        "homePlace": "<br> ",
        "weapon": "Spear",
        "starVietnamese": "Địa Tiệp Tinh",
        "nicknameVietnamese": "Hoa Hạng Hổ (hổ sẹo hoa)",
        "nameVietnamese": "Cung Vượng",
        "designationVietnamese": "",
        "image": "078_dia tiep tinh_hoa hang ho_cung vuong.jpg"
      },
      {
        "rank": "79",
        "star": "Disu<br> (地速);<br> Speed Star<br> (地速星)",
        "name": "Ding Desun<br> (丁得孙; 丁得孫; Dīng Désūn; Ting Te-sun)",
        "nickname": "\"Arrow-hit Tiger\"<br> (中箭虎)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Imperial general",
        "homePlace": "<br> ",
        "weapon": "Forked spear",
        "starVietnamese": "Địa Tốc Tinh",
        "nicknameVietnamese": "Trúng Tiễn Hổ (hổ trúng tên)",
        "nameVietnamese": "Đinh Đắc Tôn",
        "designationVietnamese": "",
        "image": "079_dia toc tinh_tung tien ho_dinh dac ton.jpg"
      },
      {
        "rank": "80",
        "star": "Dizhen<br> (地鎮);<br> Guardian Star<br> (地鎮星)",
        "name": "Mu Chun<br> (穆春; Mù Chūn; Mu Ch'un)",
        "nickname": "\"Little Restrained\"<br> (小遮攔)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Rich man",
        "homePlace": "Jieyang Town (believed to be in present-day Jiujiang, Jiangxi)",
        "weapon": "Sabre",
        "starVietnamese": "Địa Trấn Tinh",
        "nicknameVietnamese": "Tiểu Già Lan (giấu chút ít)",
        "nameVietnamese": "Mục Xuân",
        "designationVietnamese": "",
        "image": "080_dia tran tinh_tieu gia lan_muc xuan.jpg"
      },
      {
        "rank": "81",
        "star": "Diji<br> (地嵇);<br> Ji Star<br> (地嵇星)",
        "name": "Cao Zheng<br> (曹正; Cáo Zhèng; Ts'ao Cheng)",
        "nickname": "\"Knife Wielding Demon\"<br> (操刀鬼)",
        "otherNames": "<br> ",
        "division": "<br> ",
        "designation": "Chief butcher",
        "origin": "Butcher",
        "homePlace": "Kaifeng",
        "weapon": "<br> ",
        "starVietnamese": "Địa cơ Tinh",
        "nicknameVietnamese": "Thao Đao Quỷ (quỷ múa dao)",
        "nameVietnamese": "Tào Chính",
        "designationVietnamese": "",
        "image": "081_dia co tinh_thao dao quy_tao chinh.jpg"
      },
      {
        "rank": "82",
        "star": "Dimo<br> (地魔);<br> Devil Star<br> (地魔星)",
        "name": "Song Wan<br> (宋万; 宋萬; Sòng Wàn; Sung Wan)",
        "nickname": "\"Giant in the Clouds\"<br> (雲裏金剛)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Bandit leader",
        "homePlace": "<br> ",
        "weapon": "<br> ",
        "starVietnamese": "Địa Ma Tinh",
        "nicknameVietnamese": "Vân Lý Kim Cương (thần Kim Cương đường mây)",
        "nameVietnamese": "Tống Vạn",
        "designationVietnamese": "",
        "image": "082_dia ma tinh_van ly kim cuong_tong van.jpg"
      },
      {
        "rank": "83",
        "star": "Diyao<br> (地妖);<br> Demon Star<br> (地妖星)",
        "name": "Du Qian<br> (杜迁; 杜遷; Dù Qiān; Tu Ch'ien)",
        "nickname": "\"Touching the Sky\"<br> (摸着天)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Bandit leader",
        "homePlace": "<br> ",
        "weapon": "<br> ",
        "starVietnamese": "Địa Yêu Tinh",
        "nicknameVietnamese": "Mô Trước Thiên (sờ được trời)",
        "nameVietnamese": "Đỗ Thiên",
        "designationVietnamese": "",
        "image": "083_dia yeu tinh_mo truoc thien_do thien.jpg"
      },
      {
        "rank": "84",
        "star": "Diyou<br> (地幽);<br> Tranquil Star<br> (地幽星)",
        "name": "Xue Yong<br> (薛永; Xuē Yǒng; Hsüeh Yung)",
        "nickname": "\"Sick Tiger\"<br> (病大蟲)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Medicine peddler",
        "homePlace": "Luoyang, Henan",
        "weapon": "<br> ",
        "starVietnamese": "Địa U Tinh",
        "nicknameVietnamese": "Bệnh Đại Trùng (hổ ốm)",
        "nameVietnamese": "Tiết Vĩnh",
        "designationVietnamese": "",
        "image": "084_dia u tinh_benh dai trung_tiet vinh.jpg"
      },
      {
        "rank": "85",
        "star": "Difu<br> (地伏);<br> Concealment Star<br> (地伏星)",
        "name": "Shi En<br> (施恩; Shī Ēn; Shih En)",
        "nickname": "\"Golden Eyed Tiger Cub\"<br> (金眼彪)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Prison warden",
        "homePlace": "Mengzhou, Jiaozuo, Henan",
        "weapon": "<br> ",
        "starVietnamese": "Địa Phục Tinh",
        "nicknameVietnamese": "Kim Nhãn Bưu (beo mắt vàng)",
        "nameVietnamese": "Thi Ân",
        "designationVietnamese": "",
        "image": "085_dia phuc tinh_kim nhan buu_thi an.jpg"
      },
      {
        "rank": "86",
        "star": "Dipi<br> (地僻);<br> Remote Star<br> (地僻星)",
        "name": "Li Zhong<br> (李忠; Lǐ Zhōng; Li Chung)",
        "nickname": "\"Tiger Slaying General\"<br> (打虎將)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Medicine peddler",
        "homePlace": "Haozhou<br> (present-day Fengyang County, Anhui)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Tích Tinh",
        "nicknameVietnamese": "Đả Hổ Tướng (tướng đánh hổ)",
        "nameVietnamese": "Lý Trung",
        "designationVietnamese": "",
        "image": "086_dia tich tinh_da ho tuong_ly trung.jpg"
      },
      {
        "rank": "87",
        "star": "Dikong<br> (地空);<br> Empty Star<br> (地空星)",
        "name": "Zhou Tong<br> (周通; Zhōu Tōng; Chou T'ung)",
        "nickname": "\"Little Conqueror\"<br> (小覇王)",
        "otherNames": "<br> ",
        "division": "Scouting general (cavalry)",
        "designation": "Tiger Cub Scouting General",
        "origin": "Bandit leader",
        "homePlace": "Qingzhou<br> (in present-day Shandong)",
        "weapon": "Spear<br> (走水綠沉槍)",
        "starVietnamese": "Địa Không Tinh",
        "nicknameVietnamese": "Tiểu Bá Vương (Bá vương nhỏ)",
        "nameVietnamese": "Chu Thông",
        "designationVietnamese": "",
        "image": "087_dia khong tinh_tieu ba vuong_chu thong.jpg"
      },
      {
        "rank": "88",
        "star": "Digu<br> (地孤);<br> Solitary Star<br> (地孤星)",
        "name": "Tang Long<br> (汤隆; 湯隆; Tāng Lóng; T'ang Lung)",
        "nickname": "\"Gold Coin Spotted Leopard\"<br> (金錢豹子)",
        "otherNames": "<br> ",
        "division": "<br> ",
        "designation": "Chief armourer",
        "origin": "Blacksmith",
        "homePlace": "Yan'an, Shaanxi",
        "weapon": "<br> ",
        "starVietnamese": "Địa Cô Tinh",
        "nicknameVietnamese": "Kim Tiền Báo Tử (báo đốm vàng)",
        "nameVietnamese": "Thang Long",
        "designationVietnamese": "",
        "image": "088_dia co tinh_kim tien bao tu_thang long.jpg"
      },
      {
        "rank": "89",
        "star": "Diquan<br> (地全);<br> Complete Star<br> (地全星)",
        "name": "Du Xing<br> (杜兴; 杜興; Dù Xīng; Tu Hsing)",
        "nickname": "\"Demon Face\"<br> (鬼臉兒)",
        "otherNames": "<br> ",
        "division": "Reconnaissance and intelligence",
        "designation": "Scout leader",
        "origin": "Li Ying's steward",
        "homePlace": "Zhongshan<br> (present-day Dingzhou, Hebei)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Toàn Tinh",
        "nicknameVietnamese": "Quỷ Kiểm Nhi (gã đếm quỷ)",
        "nameVietnamese": "Đỗ Hưng",
        "designationVietnamese": "",
        "image": "089_dia toan tinh_quy kiem nhi_do hung.jpg"
      },
      {
        "rank": "90",
        "star": "Diduan<br> (地短);<br> Short Star<br> (地短星)",
        "name": "Zou Yuan<br> (邹渊; 鄒淵; Zōu Yuān; Tsou Yüan)",
        "nickname": "\"Forest Emerging Dragon\"<br> (出林龍)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Bandit leader",
        "homePlace": "Laizhou, Yantai, Shandong",
        "weapon": "Flying Tiger Staff<br> (飛虎棒)",
        "starVietnamese": "Địa Đoản Tinh",
        "nicknameVietnamese": "Xuất Lâm Long (rồng rời rừng)",
        "nameVietnamese": "Trâu Uyên",
        "designationVietnamese": "",
        "image": "090_dia doan tinh_xuat lam long_trau uyen.jpg"
      },
      {
        "rank": "91",
        "star": "Dijiao<br> (地角);<br> Horn Star<br> (地角星)",
        "name": "Zou Run<br> (邹润; 鄒潤; Zōu Rùn; Tsou Jun)",
        "nickname": "\"Single Horned Dragon\"<br> (獨角龍)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Bandit leader",
        "homePlace": "Laizhou, Yantai, Shandong",
        "weapon": "<br> ",
        "starVietnamese": "Địa Giốc Tinh",
        "nicknameVietnamese": "Độc Giác Long (rồng một sừng)",
        "nameVietnamese": "Trâu Nhuận",
        "designationVietnamese": "",
        "image": "091_dia gioc tinh_doc giac long_trau nhuan.jpg"
      },
      {
        "rank": "92",
        "star": "Diqiu<br> (地囚);<br> Prisoner Star<br> (地囚星)",
        "name": "Zhu Gui<br> (朱贵; 朱貴; Zhū Guì; Chu Kui)",
        "nickname": "\"Dry Land Alligator\"<br> (旱地忽律)",
        "otherNames": "<br> ",
        "division": "Reconnaissance and intelligence",
        "designation": "Scout leader",
        "origin": "Bandit leader",
        "homePlace": "Yishui County, Yizhou<br> (in present-day Linyi, Shandong)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Tú Tinh",
        "nicknameVietnamese": "Hạn Địa Hốt Luật (cá sấu trên cạn)",
        "nameVietnamese": "Chu Quý",
        "designationVietnamese": "",
        "image": "092_dia tu tinh_han dia hot luat_chu quy.jpg"
      },
      {
        "rank": "93",
        "star": "Dicang<br> (地藏);<br> Hidden Star<br> (地藏星)",
        "name": "Zhu Fu<br> (朱富; Zhū Fù; Chu Fu)",
        "nickname": "\"Sneering Tiger\"<br> (笑面虎)",
        "otherNames": "<br> ",
        "division": "<br> ",
        "designation": "Brewery master",
        "origin": "Tavern owner",
        "homePlace": "Yishui County, Yizhou<br> (in present-day Linyi, Shandong)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Tàng Tinh",
        "nicknameVietnamese": "Tiếu Diện Hổ (hổ mặt cười)",
        "nameVietnamese": "Chu Phú",
        "designationVietnamese": "",
        "image": "093_dia tang tinh_tieu dien ho_chu phu.jpg"
      },
      {
        "rank": "94",
        "star": "Diping<br> (地平);<br> Level Star<br> (地平星)",
        "name": "Cai Fu<br> (蔡福; Cài Fú; Ts'ai Fu)",
        "nickname": "\"Iron Arm\"<br> (鐵臂膊)",
        "otherNames": "<br> ",
        "division": "<br> ",
        "designation": "Chief executioner",
        "origin": "Prison warden and executioner",
        "homePlace": "Daming Prefecture<br> (in present-day Handan, Hebei)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Binh Tinh",
        "nicknameVietnamese": "Thiết Tý Bác (bác tay sắt)",
        "nameVietnamese": "Sái Phúc",
        "designationVietnamese": "",
        "image": "094_dia binh tinh_thiet ty phu_xai phuc.jpg"
      },
      {
        "rank": "95",
        "star": "Disun<br> (地損);<br> Harm Star<br> (地損星)",
        "name": "Cai Qing<br> (蔡庆; 蔡慶; Cài Qìng; Ts'ai Ch'ing)",
        "nickname": "\"Stalk of Flower\"<br> (一枝花)",
        "otherNames": "<br> ",
        "division": "<br> ",
        "designation": "Chief executioner",
        "origin": "Prison warden and executioner",
        "homePlace": "Daming Prefecture<br> (in present-day Handan, Hebei)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Tổn Tinh",
        "nicknameVietnamese": "Nhất Chi Hoa (một nhành hoa)",
        "nameVietnamese": "Sái Khánh",
        "designationVietnamese": "",
        "image": "095_dia ton tinh_nhat chi xoa_xai khanh.jpg"
      },
      {
        "rank": "96",
        "star": "Dinu<br> (地奴);<br> Slave Star<br> (地奴星)",
        "name": "Li Li<br> (李立; Lǐ Lì; Li Li)",
        "nickname": "\"Life Taking Judge\"<br> (催命判官)",
        "otherNames": "<br> ",
        "division": "Reconnaissance and intelligence",
        "designation": "Scout leader",
        "origin": "Tavern owner",
        "homePlace": "Luzhou (present-day Hefei, Anhui)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Nô Tinh",
        "nicknameVietnamese": "Thôi Mệnh Phán Quan (phán quan đoạt mệnh)",
        "nameVietnamese": "Lý Lập",
        "designationVietnamese": "",
        "image": "096_dia no tinh_thoi menh phan quan_ly lap.jpg"
      },
      {
        "rank": "97",
        "star": "Dicha<br> (地察);<br> Detective Star<br> (地察星)",
        "name": "Li Yun<br> (李云; 李雲; Lǐ Yún; Li Yün)",
        "nickname": "\"Green Eyed Tiger\"<br> (青眼虎)",
        "otherNames": "<br> ",
        "division": "<br> ",
        "designation": "Construction supervisor",
        "origin": "Constable",
        "homePlace": "Yishui County, Yizhou<br> (in present-day Linyi, Shandong)",
        "weapon": "Sabre",
        "starVietnamese": "Địa Sát Tinh",
        "nicknameVietnamese": "Thanh Nhãn Hổ (hổ mắt xanh)",
        "nameVietnamese": "Lý Vân",
        "designationVietnamese": "",
        "image": "097_dia sat tinh_thanh nho ho_ly van.jpg"
      },
      {
        "rank": "98",
        "star": "Di'e<br> (地惡);<br> Evil Star<br> (地惡星)",
        "name": "Jiao Ting<br> (焦挺; Jiāo Tǐng; Chiao T'ing)",
        "nickname": "\"Faceless\"<br> (沒面目)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Wrestler",
        "homePlace": "Zhongshan Prefecture (around present-day Dingzhou, Baoding, Hebei)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Ác Tinh",
        "nicknameVietnamese": "Một Diện Mục (anh xấu hổ)",
        "nameVietnamese": "Tiêu Đĩnh",
        "designationVietnamese": "",
        "image": "098_dia ac tinh_mot dien muc_tieu dinh.jpg"
      },
      {
        "rank": "99",
        "star": "Dichou<br> (地丑);<br> Ugly Star<br> (地丑星)",
        "name": "Shi Yong<br> (石勇; Shí Yǒng; Shih Yung)",
        "nickname": "\"Stone General\"<br> (石將軍)",
        "otherNames": "<br> ",
        "division": "Infantry",
        "designation": "Infantry leader",
        "origin": "Gambler",
        "homePlace": "Daming Prefecture<br> (in present-day Handan, Hebei)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Xú Tinh",
        "nicknameVietnamese": "Thạch Tướng Quân (tướng quân họ Thạch)",
        "nameVietnamese": "Thạch Dũng",
        "designationVietnamese": "",
        "image": "099_dia xu tinh_thach tuong quan_thach dung.jpg"
      },
      {
        "rank": "100",
        "star": "Dishu<br> (地數);<br> Number Star<br> (地數星)",
        "name": "Sun Xin<br> (孙新; 孫新; Sūn Xīn; Sun Hsin)",
        "nickname": "\"Little Yuchi\"<br> (小尉遲)",
        "otherNames": "<br> ",
        "division": "Reconnaissance and intelligence",
        "designation": "Scout leader",
        "origin": "Tavern owner",
        "homePlace": "Qiongzhou<br> (present-day Hainan)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Số Tinh",
        "nicknameVietnamese": "Tiểu Uý Trì (Uý Trì nhỏ) ",
        "nameVietnamese": "Tôn Tân",
        "designationVietnamese": "",
        "image": "100_dia so tinh_tieu uy tri_ton tan.jpg"
      },
      {
        "rank": "101",
        "star": "Diyin<br> (地陰);<br> Yin Star<br> (地陰星)",
        "name": "Gu Dasao<br> (顾大嫂; 顧大嫂; Gù Dàsǎo; Ku Ta-sao)",
        "nickname": "\"Female Tiger\"<br> (母大蟲)",
        "otherNames": "<br> ",
        "division": "Reconnaissance and intelligence",
        "designation": "Scout leader",
        "origin": "Tavern owner",
        "homePlace": "<br> ",
        "weapon": "<br> ",
        "starVietnamese": "Địa Âm Tinh",
        "nicknameVietnamese": "Mẫu Đại Trùng (hổ mẹ)",
        "nameVietnamese": "Cố Đại Tẩu",
        "designationVietnamese": "",
        "image": "101_dia am tinh_mau dai trung_co dai tau.jpg"
      },
      {
        "rank": "102",
        "star": "Dixing<br> (地刑);<br> Execute Star<br> (地刑星)",
        "name": "Zhang Qing<br> (张青; 張青; Zhāng Qīng; Chang Ch'ing)",
        "nickname": "\"Gardener\"<br> (菜園子)",
        "otherNames": "<br> ",
        "division": "Reconnaissance and intelligence",
        "designation": "Scout leader",
        "origin": "Tavern owner",
        "homePlace": "Mengzhou, Jiaozuo, Henan",
        "weapon": "<br> ",
        "starVietnamese": "Địa Hình Tinh",
        "nicknameVietnamese": "Thái Viên Tử (người trông vườn rau)",
        "nameVietnamese": "Trương Thanh",
        "designationVietnamese": "",
        "image": "102_dia hinh tinh_thai vien tu_truong thanh.jpg"
      },
      {
        "rank": "103",
        "star": "Dizhuang<br> (地壯);<br> Strong Star<br> (地壯星)",
        "name": "Sun Erniang<br> (孙二娘; 孫二娘; Sūn Èrniáng; Sun Erh-niang)",
        "nickname": "\"Female Yaksha\"<br> (母夜叉)",
        "otherNames": "<br> ",
        "division": "Reconnaissance and intelligence",
        "designation": "Scout leader",
        "origin": "Tavern owner",
        "homePlace": "<br> ",
        "weapon": "<br> ",
        "starVietnamese": "Địa Tráng Tinh",
        "nicknameVietnamese": "Mẫu Dạ Xoa (dạ xoa cái)",
        "nameVietnamese": "Tôn Nhị Nương",
        "designationVietnamese": "",
        "image": "103_dia trang tinh_mau da xoa_ton nhi nuong.jpg"
      },
      {
        "rank": "104",
        "star": "Dilie<br> (地劣);<br> Inferior Star<br> (地劣星)",
        "name": "Wang Dingliu<br> (王定六; Wáng Dìngliù; Wang Ting-liu)",
        "nickname": "\"Living Goddess of Lightning\"<br> (活閃婆)",
        "otherNames": "<br> ",
        "division": "Reconnaissance and intelligence",
        "designation": "Scout leader",
        "origin": "Tavern owner",
        "homePlace": "Jiankang Prefecture<br> (present-day Nanjing, Jiangsu)",
        "weapon": "<br> ",
        "starVietnamese": "Địa Liệt Tinh",
        "nicknameVietnamese": "Hoạt Thiểm Bà (Thiểm Bà sống)",
        "nameVietnamese": "Vương Định Lục",
        "designationVietnamese": "",
        "image": "104_dia tiet tinh_hoat diem la_vuong dinh luc.jpg"
      },
      {
        "rank": "105",
        "star": "Dijian<br> (地健);<br> Healthy Star<br> (地健星)",
        "name": "Yu Baosi<br> (郁保四; Yù Bǎosì; Yü Pao-szu)",
        "nickname": "\"God of the Dangerous Road\"<br> (險道神)",
        "otherNames": "<br> ",
        "division": "<br> ",
        "designation": "Chief flag bearer",
        "origin": "Bandit",
        "homePlace": "<br> ",
        "weapon": "<br> ",
        "starVietnamese": "Địa Kiện Tinh",
        "nicknameVietnamese": "Hiểm Đạo Thần (thần hiểm ác)",
        "nameVietnamese": "Úc Bảo Tứ",
        "designationVietnamese": "",
        "image": "105_dia kien tinh_hiem dao than_uc bao tu.jpg"
      },
      {
        "rank": "106",
        "star": "Dihao<br> (地耗);<br> Rat Star<br> (地耗星)",
        "name": "Bai Sheng<br> (白胜; 白勝; Bái Shèng; Pai Sheng)",
        "nickname": "\"Daylight Rat\"<br> (白日鼠)",
        "otherNames": "<br> ",
        "division": "Reconnaissance and intelligence",
        "designation": "Scout leader",
        "origin": "Gambler",
        "homePlace": "Anle Village, Yuncheng County, Shandong",
        "weapon": "<br> ",
        "starVietnamese": "Địa Hao Tinh",
        "nicknameVietnamese": "Bạch Nhật Thử (chuột chính ngày)",
        "nameVietnamese": "Bạch Thắng",
        "designationVietnamese": "",
        "image": "106_dia hao tinh_bach nhat thu_bach thang.jpg"
      },
      {
        "rank": "107",
        "star": "Dizei<br> (地賊);<br> Thief Star<br> (地賊星)",
        "name": "Shi Qian<br> (时迁; 時遷; Shí Qiān; Shih Ch'ien)",
        "nickname": "\"Flea on a Drum\"<br> (鼓上蚤)",
        "otherNames": "<br> ",
        "division": "Reconnaissance and intelligence",
        "designation": "Scout leader",
        "origin": "Thief,<br> Tomb raider",
        "homePlace": "Gaotangzhou<br> (present-day Gaotang County, Shandong)",
        "weapon": "Pudao",
        "starVietnamese": "Địa Tặc Tinh",
        "nicknameVietnamese": "Cổ Thượng Tảo (bọ trên trống)",
        "nameVietnamese": "Thời Thiên",
        "designationVietnamese": "",
        "image": "107_dia tac tinh_co thuong tao_thoi thien.jpg"
      },
      {
        "rank": "108",
        "star": "Digou<br> (地狗);<br> Hound Star<br> (地狗星)",
        "name": "Duan Jingzhu<br> (段景住; Duàn Jǐngzhù; Tuan Ching-chu)",
        "nickname": "\"Golden Haired Hound\"<br> (金毛犬)",
        "otherNames": "<br> ",
        "division": "Reconnaissance and intelligence",
        "designation": "Scout leader",
        "origin": "Horse thief",
        "homePlace": "Zhuozhou, Hebei",
        "weapon": "<br> ",
        "starVietnamese": "Địa Cẩu Tinh",
        "nicknameVietnamese": "Kim Mao Khuyển (chó lông vàng)",
        "nameVietnamese": "Đoàn Cảnh Trụ",
        "designationVietnamese": "",
        "image": "108_dia cau tinh_kim mao khuyen_doan canh tru.jpg"
      }
];
//heroes.forEach(hero => console.log(JSON.stringify(hero, null, 2) + ','));
