var people = [
{ lastName: 'Đan', code: 'ONGNGOAI', fullName: 'Nguyễn Văn Đan', gender: 'male', dob: '1929', avatar: '', job: 'Nông dân' },
{ lastName: 'Bật', code: 'BANGOAI', fullName: 'Vũ Thị Bật', gender: 'female', dob: '1927', avatar: '', job: 'Nông dân' },
{ lastName: 'Chắt', code: 'CHAT', fullName: 'Nguyễn Thị Chắt', gender: 'female', dob: '11/1951', avatar: '', job: 'Nông dân' },

{ lastName: 'Hoành', code: 'HOANH', fullName: 'Nguyễn Văn Hoành', gender: 'male', dob: '23/01/1948', avatar: '', job: 'Nông dân' },
{ lastName: 'Huệ', code: 'HUEKHANH', fullName: 'Nguyễn Minh Huệ', gender: 'female', dob: '21/12/1973', avatar: '', job: 'Dược sĩ' },
{ lastName: 'Minh', code: 'MINH', fullName: 'Nguyễn Tuyết Minh', gender: 'female', dob: '1976', avatar: '', job: 'Giáo viên cấp 1' },
{ lastName: 'Duyên', code: 'DUYEN', fullName: 'Nguyễn Thị Duyên', gender: 'female', dob: '10/03/1978', avatar: '', job: 'Giáo viên cấp 3' },
{ lastName: 'Huế', code: 'HUEDUNG', fullName: 'Nguyễn Thị Huế', gender: 'female', dob: '24/06/1980', avatar: '', job: 'Giáo viên cấp 3' },
{ lastName: 'Năm', code: 'NAM', fullName: 'Nguyễn Thị Năm', gender: 'female', dob: '11/1984', avatar: '', job: 'Giảng viên đại học' },
{ lastName: 'Huyên', code: 'HUYEN', fullName: 'Nguyễn Văn Huyên', gender: 'male', dob: '11/05/1987', avatar: 'HUYEN.jpg', job: 'Lập trình viên' },

{ lastName: 'Khánh', code: 'KHANH', fullName: 'Nguyễn Văn Khánh', gender: 'male', dob: '19', avatar: '', job: 'Hiệu phó cấp 2' },
{ lastName: 'Nhi', code: 'NHI', fullName: 'Nguyễn Yến Nhi', gender: 'female', dob: '19', avatar: '', job: 'NA' },
{ lastName: 'Khanh', code: 'MAIKHANH', fullName: 'Nguyễn Mai Khanh', gender: 'female', dob: '19', avatar: '', job: 'NA' },
{ lastName: 'Phúc', code: 'PHUC', fullName: 'Nguyễn Văn Phúc', gender: 'male', dob: '19', avatar: '', job: 'NA' },
{ lastName: 'Doanh', code: 'DOANH', fullName: 'Nguyễn Hữu Doanh', gender: 'male', dob: '1970', avatar: '', job: 'Bộ đội' },
{ lastName: 'Trang', code: 'TRANG', fullName: 'Nguyễn Minh Trang', gender: 'female', dob: '1999', avatar: '', job: 'Học sinh cấp 1' },
{ lastName: 'Thư', code: 'THU', fullName: 'Nguyễn Minh Thư', gender: 'female', dob: '2004', avatar: '', job: 'Đi mẫu giáo' },
{ lastName: 'Hà', code: 'HADUYEN', fullName: 'Nguyễn Việt Hà', gender: 'male', dob: '19', avatar: '', job: 'Bưu điện' },
{ lastName: 'Linh', code: 'LINH', fullName: 'Nguyễn Hà Linh', gender: 'female', dob: '19', avatar: '', job: 'NA' },
{ lastName: 'Hùng', code: 'HUNG', fullName: 'Nguyễn Mạnh Hùng', gender: 'male', dob: '19', avatar: '', job: 'Học sinh cấp 1' },
{ lastName: 'Dũng', code: 'DUNG', fullName: 'Nguyễn Văn Dũng', gender: 'male', dob: '19', avatar: '', job: 'Ủy ban huyện' },
{ lastName: 'Nguyệt', code: 'NGUYET', fullName: 'Nguyễn Minh Nguyệt', gender: 'female', dob: '19', avatar: '', job: 'Học sinh cấp 1' },
{ lastName: 'Lợi', code: 'LOI', fullName: 'Nguyễn Văn Lợi', gender: 'male', dob: '19', avatar: '', job: '' },
{ lastName: 'Hà', code: 'HANAM', fullName: 'Nguyễn Văn Hà', gender: 'male', dob: '19', avatar: '', job: '' },
{ lastName: 'Quân', code: 'QUAN', fullName: 'Nguyễn Hoàng Quân', gender: 'male', dob: '19', avatar: '', job: '' },
{ lastName: 'Chi', code: 'CHI', fullName: 'Nguyễn Hoàng Linh Chi', gender: 'female', dob: '19', avatar: '', job: '' },
{ lastName: 'Dương', code: 'DUONG', fullName: 'Cao Thị Thùy Dương', gender: 'female', dob: '16/10/1992', avatar: 'DUONG.jpg', job: 'Tester' },
{ lastName: 'Tuấn', code: 'NGUYENANHTUAN', fullName: 'Nguyễn Anh Tuấn', gender: 'male', dob: '16/03/2019', avatar: 'NGUYEN_ANH_TUAN.jpg', job: '' }
];
