var data = [
    {
        name: 'Truyện Cổ Nhật Bản',
        stories: [
            {"title":"Những cuộn kinh linh ứng","src":"http://www.sachnoionline.com/upload/files/Truyen co Nhat Ban 1.mp3"},
            {"title":"Vị thần của dân nghèo","src":"http://www.sachnoionline.com/upload/files/Truyen co Nhat Ban 2.mp3"},
            {"title":"Thiên đàng của Mèo","src":"http://www.sachnoionline.com/upload/files/Truyen co Nhat Ban 3.mp3"},
            {"title":"Cây Dẻ trả ơn","src":"http://www.sachnoionline.com/upload/files/Truyen co Nhat Ban 4.mp3"},
            {"title":"Lấy oán trả ơn","src":"http://www.sachnoionline.com/upload/files/Truyen co Nhat Ban 5.mp3"},
            {"title":"Lòng biết ơn của con Cáo","src":"http://www.sachnoionline.com/upload/files/Truyen co Nhat Ban 6.mp3"},
            {"title":"Lông mi của Chó Sói","src":"http://www.sachnoionline.com/upload/files/Truyen co Nhat Ban 7.mp3"},
            {"title":"Ông già làm cây nở hoa","src":"http://www.sachnoionline.com/upload/files/Truyen co Nhat Ban 8.mp3"}
        ]
    },
    {
        name: 'Cổ tích thế giới',
        stories: [
            {"title":"Cô Bé Choàng Khăn Đỏ","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 01.mp3"},
            {"title":"Nàng Bạch Tuyết và Bảy Chú Lùn","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 02.mp3"},
            {"title":"Chuyện Ba Hạt Dẻ và Nàng Lọ Lem","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 03.mp3"},
            {"title":"Đóa Hồng","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 04.mp3"},
            {"title":"Bông Hoa Cúc Trắng","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 05.mp3"},
            {"title":"Ba Cô Tiên","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 06.mp3"},
            {"title":"Cọp và Khỉ","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 07.mp3"},
            {"title":"Cậu Bé Chăn Cừu","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 08.mp3"},
            {"title":"Thỏ Trắng Thông Minh và Láu Lỉnh","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 09.mp3"},
            {"title":"Chim Họa Mi","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 10.mp3"},
            {"title":"Hai Ông Cháu","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 11.mp3"},
            {"title":"Con Ngỗng Vàng","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 12.mp3"},
            {"title":"Bảy Chú Dê Con","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 13.mp3"},
            {"title":"Hai Chú Gấu Tham Ăn","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 14.mp3"},
            {"title":"Ngựa Thiếc và Nàng Công Chúa Bạch Ngân","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 15.mp3"},
            {"title":"Masa và Gấu","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 16.mp3"},
            {"title":"Chú Ếch Kiêu Căng","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 17.mp3"},
            {"title":"Những Nhạc Sĩ Thành Brêm","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 18.mp3"},
            {"title":"Sự Tích Con Cú Mèo","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 19.mp3"},
            {"title":"Con Mèo Đi Hia","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 20.mp3"},
            {"title":"Ba Cô Gái","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 21.mp3"},
            {"title":"Trái Tim Của Khỉ","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 22.mp3"},
            {"title":"Vì Sao Chồn và Cáo Sống Trong Hang","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 23.mp3"},
            {"title":"Nàng Tiên Cá","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 24.mp3"},
            {"title":"Đàn Ngỗng Trời","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 25.mp3"},
            {"title":"Em Bé Bán Diêm","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 26.mp3"},
            {"title":"Sư Tử và Kiến Càng","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 27.mp3"},
            {"title":"Ở Sao Thì Được Vậy","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 28.mp3"},
            {"title":"Ông Lão Đánh Cá và Con Cá Vàng","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 29.mp3"},
            {"title":"Ngựa và Sói","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 30.mp3"},
            {"title":"Bài Học Cho Cáo","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 31.mp3"},
            {"title":"Bà Chú Tuyết ","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 32.mp3"},
            {"title":"Sói và Cừu Tránh Rét","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 33.mp3"},
            {"title":"Cây Bút Thần","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 34.mp3"},
            {"title":"Ông Lão và Sóc Nâu","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 35.mp3"},
            {"title":"Bé Tí Hon","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 36.mp3"},
            {"title":"Chú Bò Đen Tốt Bụng","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 37.mp3"},
            {"title":"Ông Lão Mưu Trí và Gã Hung Thần","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 38.mp3"},
            {"title":"Khỉ và Lạc Đà Đi Ăn Trộm","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 39.mp3"},
            {"title":"Nàng PhaTiMa và Lão Phù Thủy Trong Rừng","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 40.mp3"},
            {"title":"Chích Chòe và Cáo","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 41.mp3"},
            {"title":"Con Cò, Con Cua và Đàn Đá","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 42.mp3"},
            {"title":"Quạ và Chích Chòe","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 43.mp3"},
            {"title":"TÌnh Bạn Cảm Động","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 44.mp3"},
            {"title":"Dê và Sói","src":"http://www.sachnoionline.com/upload/files/TRUYEN CO TICH THE GIOI 45.mp3"}
        ]
    },
    {
        name: 'Thần thoại Hy Lạp',
        stories: [
            {"title":"Lời giới thiệu","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 01.mp3"},
            {"title":"Thần Zeus ra đời","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 02.mp3"},
            {"title":"Zues lật đổ Crônôx, cuộc giao tranh với các Tităng","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 03.mp3"},
            {"title":"Nguồn gốc của Loài Người năm thời đại","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 04.mp3"},
            {"title":"Prômêtê và Loài Người","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 05.mp3"},
            {"title":"Păngdor - Người đàn bà đầu tiên của thế gian và những tai họa Zeus giáng xuống trừng phạt Loài Người","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 06.mp3"},
            {"title":"Nạn hồng thủy Đơcalinông và Piara, giống Người Đá","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 07.mp3"},
            {"title":"Zues trừng phạt Prômêtê","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 08.mp3"},
            {"title":"Thế giới Ôlympia và Mười Hai Vị Thần Tối Cao","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 09.mp3"},
            {"title":"Pôdêiđông và các Thần Biển","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 10.mp3"},
            {"title":"Thế giới âm phủ của Hađex","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 11.mp3"},
            {"title":"Nữ thần Hêra","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 12.mp3"},
            {"title":"Thần Apôlông","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 13.mp3"},
            {"title":"Mối tình của Apôlông với Tiên Nữ Đaphnê","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 14.mp3"},
            {"title":"Apôlông và Các Nàng Muydơ","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 15.mp3"},
            {"title":"Nữ thần Artêmix","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 16.mp3"},
            {"title":"Artêmix biến Actêông thành Hươu","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 17.mp3"},
            {"title":"Atêna thắng Pôdêiđông được cai quản miền đồng bằng Attich","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 18.mp3"},
            {"title":"Thần Hermex","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 19.mp3"},
            {"title":"Thần chiến tranh Arex","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 20.mp3"},
            {"title":"Nữ thần Aphrôđitơ","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 21.mp3"},
            {"title":"Aphrôđitơ ban phúc cho Pigmaliông","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 22.mp3"},
            {"title":"Aphrôđitơ giáng họa xuống Narxix","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 23.mp3"},
            {"title":"Nữ thần Đêmêter và nàng Perxêphôn","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 24.mp3"},
            {"title":"Cuộc phiêu lưu của Phaêtông","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 25.mp3"},
            {"title":"Sự ra đời của người anh hùng Hêraclex","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 26.mp3"},
            {"title":"Kỳ công của Hêraclex","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 27.mp3"},
            {"title":"Hội Ôlympich","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 28.mp3"},
            {"title":"Vua XiDip phải chịu cực hình","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 29.mp3"},
            {"title":"Nổi buồn của chàng Kiparixxôx","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 30.mp3"},
            {"title":"Cái chết của chàng Hiakintôx","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 31.mp3"},
            {"title":"Mối tình chung thủy của danh ca Orphê với nàng Orđix","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 32.mp3"},
            {"title":"Cái chết của Orphê","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 33.mp3"},
            {"title":"Truyền thuyết về cuộc chiến tranh Tơroa","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 34.mp3"},
            {"title":"Nguồn gốc cuộc chiến tranh Tơroa: từ \"Quả táo của mối bất hòa\" đến việc nàng Hêlen bị Parix quyến rủ","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 35.mp3"},
            {"title":"Quân Hy Lạp tập trung ở sông Ôlix. Đổ bộ lên đất Miđi","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 36.mp3"},
            {"title":"Quân Hy Lạp lại tập trung ở Ôlix","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 37.mp3"},
            {"title":"Tướng Philôctet bị bỏ lại ở dọc đường","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 38.mp3"},
            {"title":"Những gì đã xảy ra trong chín năm giao tranh","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 39.mp3"},
            {"title":"Mối bất hòa giữa chủ tướng Agamemnông với Akhin","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 40.mp3"},
            {"title":"Không thể chấm dứt chiến tranh bằng định ước tay đôi","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 41.mp3"},
            {"title":"Quân Hy Lạp tấn công. Chiến công của tướng Điômeđ","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 42.mp3"},
            {"title":"HecTor từ giã ĂngĐrôMác trước khi xuất trận","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 43.mp3"},
            {"title":"Zeus thực hiện lời hứa với nữ thần Thêtix: quân Tơroa phản công thắng lợi","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 44.mp3"},
            {"title":"Agmemnông nhận ra lỗi lầm xin Akhin xuất trận","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 45.mp3"},
            {"title":"Quân Tơroa tiến công thắng lợi tràn vào doanh trại quân Hy Lạp, thọc sâu vào khu vực chiến thuyền","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 46.mp3"},
            {"title":"HecTor giết chết Patơrôclơ","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 47.mp3"},
            {"title":"Akhin nguôi giận, hòa giải với Agamemnông","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 48.mp3"},
            {"title":"Akhin xuất trận đánh đuổi quân Tơroa phải chạy về thành","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 49.mp3"},
            {"title":"Akhin giết chết Hector","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 50.mp3"},
            {"title":"Lão vương Priam đi chuộc xác con","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 51.mp3"},
            {"title":"Akhin giết chết chủ tướng Memnông cầm đầu đạo quân Êthiôpi","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 52.mp3"},
            {"title":"Akhin tử trận","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 53.mp3"},
            {"title":"Agiắc-Lớn con của Têlamông tự tử","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 54.mp3"},
            {"title":"Chiến công của Uylix, Philôctet tham chiến","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 55.mp3"},
            {"title":"Thành Tơroa thất thủ","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 56.mp3"},
            {"title":"Ôđixê","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 57.mp3"},
            {"title":"Hành trình đi tìm cha của Têlêmac","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 58.mp3"},
            {"title":"Thoát khỏi hang tên khổng lồ Pôliphem ăn thịt người","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 59.mp3"},
            {"title":"Bị những người khổng lồ Lettơrigông tiêu diệt, đoàn thuyền mười hai chiếc chỉ có thoát được có một con thuyền của Uylix","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 60.mp3"},
            {"title":"Cứu đồng đội thoát khỏi kiếp lợn trong tay tiên nữ-phù thủy Kiếckê","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 61.mp3"},
            {"title":"Ăn thịt bò của thần Hêliốt, cả đoàn thủy thủ bị trừng phạt. Chỉ riêng mình Uylix sống sót","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 62.mp3"},
            {"title":"Uylix thoát khỏi sự giam cầm của tiên nữ Calipxô","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 63.mp3"},
            {"title":"Thần Pôdêiđông gây bão. Đắm bè, Uylix trôi dạt vào bờ biển xứ Phêaki","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 64.mp3"},
            {"title":"Uylix gặp công chúa Nôdica. Công chúa đưa chàng về thành","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 65.mp3"},
            {"title":"Vua Ankinôôx tiếp đãi và cho thuyền chở Uylix về quê hương","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 66.mp3"},
            {"title":"Uylix trừng trị bọn cầu hôn, đoàn tụ với gia đình, hai cha con gặp nhau bày mưu trừng trị bọn cầu hôn","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 67.mp3"},
            {"title":"Uylix gặp Pênêlôp","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 68.mp3"},
            {"title":"Cuộc chiến đấu với bọn cầu hôn","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 69.mp3"},
            {"title":"Pênêlôp nhận ra chồng","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 70.mp3"},
            {"title":"Ơpitet đòi trả thù, nữ thần Atêna hòa giải","src":"http://www.sachnoionline.com/upload/files/THAN THOAI HY LAP 71.mp3"}
        ]
    },
    {
        name: 'Cổ tích về loài vật',
        stories: [
            {title: "Kho báu của Vàng Tro", src: "http://www.sachnoionline.com/upload/files/TRUYEN VE LOAI VAT-01.mp3"},
            {title: "Thức suốt", src: "http://www.sachnoionline.com/upload/files/TRUYEN VE LOAI VAT-02.mp3"},
            {title: "Vợ chồng linh miêu", src: "http://www.sachnoionline.com/upload/files/TRUYEN VE LOAI VAT-03.mp3"},
            {title: "Quạ và Chim Sẻ", src: "http://www.sachnoionline.com/upload/files/TRUYEN VE LOAI VAT-04.mp3"},
            {title: "Cậu ông trời", src: "http://www.sachnoionline.com/upload/files/TRUYEN VE LOAI VAT-05.mp3"},
            {title: "Kiếp luân hồi của cặp chim đa đa", src: "http://www.sachnoionline.com/upload/files/TRUYEN VE LOAI VAT-06.mp3"},
            {title: "Mèo và Kên Kên", src: "http://www.sachnoionline.com/upload/files/TRUYEN VE LOAI VAT-07.mp3"},
            {title: "Quạ và Cáo", src: "http://www.sachnoionline.com/upload/files/TRUYEN VE LOAI VAT-08.mp3"},
            {title: "Chó già lừa Chó Sói", src: "http://www.sachnoionline.com/upload/files/TRUYEN VE LOAI VAT-09.mp3"},
            {title: "Cá Sấu và Chó rừng", src: "http://www.sachnoionline.com/upload/files/TRUYEN VE LOAI VAT-10.mp3"},
            {title: "Hải Ly bíp", src: "http://www.sachnoionline.com/upload/files/TRUYEN VE LOAI VAT-11.mp3"},
            {title: "Cáo và Bồ Nông", src: "http://www.sachnoionline.com/upload/files/TRUYEN VE LOAI VAT-12.mp3"},
            {title: "Con Mèo thông minh", src: "http://www.sachnoionline.com/upload/files/TRUYEN VE LOAI VAT-13.mp3"},
            {title: "Cáo và Gấu", src: "http://www.sachnoionline.com/upload/files/TRUYEN VE LOAI VAT-14.mp3"}
        ]
    }
    
    /*
    ,
    {
        name: 'Thần thoại Ấn Độ',
        stories: [
            {"title":"Shakuntala","src":"http://www.sachnoionline.com/upload/files/365 CAU CHUYEN THAN THAI AN DO HAY NHAT 01.mp3"},
            {"title":"Samudra Manthan","src":"http://www.sachnoionline.com/upload/files/365 CAU CHUYEN THAN THAI AN DO HAY NHAT 02.mp3"},
            {"title":"Dhruva dũng cảm","src":"http://www.sachnoionline.com/upload/files/365 CAU CHUYEN THAN THAI AN DO HAY NHAT 03.mp3"},
            {"title":"Thác Ganga đổ xuống","src":"http://www.sachnoionline.com/upload/files/365 CAU CHUYEN THAN THAI AN DO HAY NHAT 04.mp3"},
            {"title":"Sita bị bắt cóc","src":"http://www.sachnoionline.com/upload/files/365 CAU CHUYEN THAN THAI AN DO HAY NHAT 05.mp3"},
            {"title":"Swayamvara của Draupadi","src":"http://www.sachnoionline.com/upload/files/365 CAU CHUYEN THAN THAI AN DO HAY NHAT 06.mp3"},
            {"title":"Satyavadi Harishchandra","src":"http://www.sachnoionline.com/upload/files/365 CAU CHUYEN THAN THAI AN DO HAY NHAT 07.mp3"},
            {"title":"Garuda","src":"http://www.sachnoionline.com/upload/files/365 CAU CHUYEN THAN THAI AN DO HAY NHAT 08.mp3"},
            {"title":"Garuda đã trở thành con ngựa cưỡi của thần Vishnu như thế nào","src":"http://www.sachnoionline.com/upload/files/365 CAU CHUYEN THAN THAI AN DO HAY NHAT 09.mp3"},
            {"title":"Yudhisthira thông thái","src":"http://www.sachnoionline.com/upload/files/365 CAU CHUYEN THAN THAI AN DO HAY NHAT 10.mp3"},
            {"title":"Nala và Damayanti","src":"http://www.sachnoionline.com/upload/files/365 CAU CHUYEN THAN THAI AN DO HAY NHAT 11.mp3"},
            {"title":"Upmanyu","src":"http://www.sachnoionline.com/upload/files/365 CAU CHUYEN THAN THAI AN DO HAY NHAT 12.mp3"}
        ]
    }*/
];