package download.service.album;

import common.util.Downloader;

import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 * http://hamtruyen.vn/doc-truyen/doraemon-%5Bban-dep%5D-chapter-268.html
 *
 * @author lockex1987
 */
public class DownloadHamtruyen extends BaseAlbumDownloader {

	private static final String BASE = "http://hamtruyen.vn/doc-truyen/";

	public DownloadHamtruyen(String url, int chapter) throws Exception {
		this.url = BASE + url + ".html";
		this.chapter = chapter;
		this.chapterPrefix = true;
		super.process();
	}

	@Override
	protected void getImageList() throws Exception {
		Document doc = Downloader.jsoup(url);
		Element div = doc.getElementById("content_chap");
		Elements a = div.getElementsByTag("img");
		for (Element e : a) {
			list.add(e.attr("src"));
		}
	}
	
	private static void testDownloadHamtruyen() throws Exception {
		String[] a = new String[] {
				"doraemon-scan-chapter-1",
				"doraemon-scan-chapter-2",
				"doraemon-scan-chapter-3",
				"doraemon-scan-chapter-4",
				"doraemon-scan-chapter-5",
				"doraemon-scan-chapter-6",
				"doraemon-scan-chapter-7",
				"doraemon-scan-chapter-8",
				"doraemon-scan-chapter-9",
				"doraemon-scan-chapter-10",
				"doraemon-scan-chapter-11",
				"doraemon-scan-chapter-12",
				"doraemon-scan-chapter-13",
				"doraemon-scan-chapter-14",
				"doraemon-scan-chapter-15",
				"doraemon-scan-chapter-16",
				"doraemon-scan-chapter-17",
				"doraemon-scan-chapter-18",
				"doraemon-scan-chapter-19",
				"doraemon-scan-chapter-20",
				"doraemon-scan-chapter-21",
				"doraemon-scan-chapter-22",
				"doraemon-scan-chapter-23",
				"doraemon-scan-chapter-24",
				"doraemon-scan-chapter-25",
				"doraemon-scan-chapter-26",
				"doraemon-scan-chapter-27",
				"doraemon-scan-chapter-28",
				"doraemon-scan-chapter-29",
				"doraemon-scan-chapter-30",
				"doraemon-scan-chapter-31",
				"doraemon-scan-chapter-32",
				"doraemon-scan-chapter-33",
				"doraemon-scan-chapter-34",
				"doraemon-scan-chapter-35",
				"doraemon-scan-chapter-36",
				"doraemon-scan-chapter-37",
				"doraemon-scan-chapter-38",
				"doraemon-scan-chapter-39",
				"doraemon-scan-chapter-40",
				"doraemon-scan-chapter-41",
				"doraemon-scan-chapter-42",
				"doraemon-scan-chapter-43",
				"doraemon-scan-chapter-44",
				"doraemon-scan-chapter-45",
				"doraemon-scan-chapter-46",
				"doraemon-scan-chapter-47",
				"doraemon-scan-chapter-48",
				"doraemon-scan-chapter-49",
				"doraemon-scan-chapter-50",
				"doraemon-scan-chapter-51",
				"doraemon-scan-chapter-52",
				"doraemon-scan-chapter-53",
				"doraemon-scan-chapter-54",
				"doraemon-scan-chapter-55",
				"doraemon-scan-chapter-56",
				"doraemon-scan-chapter-57",
				"doraemon-scan-chapter-58",
				"doraemon-scan-chapter-59",
				"doraemon-scan-chapter-60",
				"doraemon-scan-chapter-61",
				"doraemon-scan-chapter-62",
				"doraemon-scan-chapter-63",
				"doraemon-scan-chapter-64",
				"doraemon-scan-chapter-65",
				"doraemon-scan-chapter-66",
				"doraemon-scan-chapter-67",
				"doraemon-scan-chapter-68",
				"doraemon-scan-chapter-69",
				"doraemon-scan-chapter-70",
				"doraemon-scan-chapter-71",
				"doraemon-scan-chapter-72",
				"doraemon-scan-chapter-73",
				"doraemon-scan-chapter-74",
				"doraemon-scan-chapter-75",
				"doraemon-scan-chapter-76",
				"doraemon-scan-chapter-77",
				"doraemon-scan-chapter-78",
				"doraemon-scan-chapter-79",
				"doraemon-scan-chapter-80",
				"doraemon-scan-chapter-81",
				"doraemon-scan-chapter-82",
				"doraemon-scan-chapter-83",
				"84", // 84?
				"doraemon-scan-chapter-85",
				"doraemon-scan-chapter-86",
				"doraemon-scan-chapter-87",
				"doraemon-scan-chapter-88",
				"doraemon-scan-chapter-89",
				"doraemon-scan-chapter-90",
				"doraemon-scan-chapter-91",
				"doraemon-scan-chapter-92",
				"doraemon-scan-chapter-93",
				"doraemon-scan-chapter-94",
				"doraemon-scan-chapter-95",
				"doraemon-scan-chapter-96",
				"doraemon-scan-chapter-97",
				"doraemon-scan-chapter-98",
				"doraemon-scan-chapter-99",
				"doraemon-scan-chapter-100",
				"doraemon-scan-chapter-101",
				"doraemon-scan-chapter-102",
				"doraemon-scan-chapter-103",
				"doraemon-scan-chapter-104",
				"doraemon-scan-chapter-105",
				"doraemon-scan-chapter-106",
				"doraemon-scan-chapter-107",
				"doraemon-scan-chapter-108",
				"doraemon-scan-chapter-109",
				"doraemon-scan-chapter-110",
				"doraemon-scan-chapter-111",
				"doraemon-scan-chapter-112",
				"doraemon-scan-chapter-113",
				"doraemon-scan-chapter-114",
				"doraemon-scan-chapter-115",
				"doraemon-scan-chapter-116",
				"doraemon-scan-chapter-117",
				"doraemon-scan-chapter-118",
				"doraemon-scan-chapter-119",
				"doraemon-scan-chapter-120",
				"doraemon-scan-chapter-121",
				"doraemon-scan-chapter-122",
				"doraemon-scan-chapter-123",
				"doraemon-scan-chapter-124",
				"doraemon-scan-chapter-125",
				"doraemon-scan-chapter-126",
				"doraemon-scan-chapter-127",
				"doraemon-scan-chapter-128",
				"doraemon-scan-chapter-129",
				"doraemon-scan-chapter-130",
				"doraemon-scan-chapter-131",
				"doraemon-scan-chapter-132",
				"doraemon-scan-chapter-133",
				"doraemon-scan-chapter-134",
				"doraemon-scan-chapter-135",
				"doraemon-scan-chapter-136",
				"doraemon-scan-chapter-137",
				"doraemon-scan-chapter-138",
				"doraemon-scan-chapter-139",
				"doraemon-scan-chapter-140",
				"doraemon-scan-chapter-141",
				"doraemon-scan-chapter-142",
				"doraemon-scan-chapter-143",
				"doraemon-scan-chapter-144",
				"doraemon-scan-chapter-145",
				"doraemon-scan-chapter-146",
				"doraemon-scan-chapter-147",
				"doraemon-scan-chapter-148",
				"doraemon-scan-chapter-149",
				"doraemon-scan-chapter-150",
				"doraemon-scan-chapter-151",
				"doraemon-scan-chapter-152",
				"doraemon-scan-chapter-153",
				"doraemon-scan-chapter-154",
				"doraemon-scan-chapter-155",
				"doraemon-scan-chapter-156",
				"doraemon-scan-chapter-157",
				"doraemon-scan-chapter-158",
				"doraemon-scan-chapter-159",
				"doraemon-scan-chapter-160",
				"doraemon-scan-chapter-161",
				"doraemon-scan-chapter-162",
				"doraemon-scan-chapter-163",
				"doraemon-scan-chapter-164",
				"doraemon-scan-chapter-165",
				"doraemon-scan-chapter-166",
				"doraemon-scan-chapter-167",
				"doraemon-scan-chapter-168",
				"doraemon-scan-chapter-169",
				"doraemon-scan-chapter-170",
				"doraemon-[ban-dep]-chapter-171",
				"doraemon-[ban-dep]-chapter-172",
				"doraemon-[ban-dep]-chapter-173",
				"doraemon-[ban-dep]-chapter-174",
				"doraemon-[ban-dep]-chapter-175",
				"doraemon-[ban-dep]-chapter-176",
				"doraemon-[ban-dep]-chapter-177",
				"doraemon-[ban-dep]-chapter-178",
				"doraemon-[ban-dep]-chapter-179",
				"doraemon-[ban-dep]-chapter-180",
				"doraemon-[ban-dep]-chapter-181",
				"doraemon-[ban-dep]-chapter-182",
				"doraemon-[ban-dep]-chapter-183",
				"doraemon-[ban-dep]-chapter-184",
				"doraemon-[ban-dep]-chapter-185",
				"doraemon-[ban-dep]-chapter-186",
				"doraemon-[ban-dep]-chapter-187",
				"doraemon-[ban-dep]-chapter-188",
				"doraemon-[ban-dep]-chapter-189",
				"doraemon-[ban-dep]-chapter-190",
				"doraemon-[ban-dep]-chapter-191",
				"doraemon-[ban-dep]-chapter-192",
				"doraemon-[ban-dep]-chapter-193",
				"doraemon-[ban-dep]-chapter-194",
				"doraemon-[ban-dep]-chapter-196",
				"doraemon-[ban-dep]-chapter-197",
				"doraemon-[ban-dep]-chapter-198",
				"doraemon-[ban-dep]-chapter-199",
				"doraemon-[ban-dep]-chapter-200",
				"doraemon-scan-chapter-201",
				"doraemon-scan-chapter-202",
				"doraemon-scan-chapter-203",
				"doraemon-scan-chapter-204",
				"doraemon-scan-chapter-205",
				"doraemon-scan-chapter-206",
				"doraemon-scan-chapter-207",
				"doraemon-scan-chapter-208",
				"doraemon-scan-chapter-209",
				"doraemon-scan-chapter-210",
				"doraemon-scan-chapter-211",
				"doraemon-scan-chapter-212",
				"doraemon-scan-chapter-213",
				"doraemon-scan-chapter-214",
				"doraemon-scan-chapter-215",
				"doraemon-scan-chapter-216",
				"doraemon-scan-chapter-217",
				"doraemon-scan-chapter-218",
				"doraemon-scan-chapter-219",
				"doraemon-scan-chapter-220",
				"doraemon-scan-chapter-221",
				"doraemon-scan-chapter-222",
				"doraemon-scan-chapter-223",
				"doraemon-scan-chapter-224",
				"doraemon-scan-chapter-225",
				"doraemon-scan-chapter-226",
				"doraemon-scan-chapter-227",
				"doraemon-scan-chapter-228",
				"doraemon-scan-chapter-229",
				"doraemon-scan-chapter-230",
				"doraemon-scan-chapter-231",
				"doraemon-scan-chapter-232",
				"doraemon-scan-chapter-233",
				"doraemon-scan-chapter-234",
				"doraemon-scan-chapter-235",
				"doraemon-scan-chapter-236",
				"doraemon-scan-chapter-237",
				"doraemon-scan-chapter-238",
				"doraemon-scan-chapter-239",
				"doraemon-scan-chapter-240",
				"doraemon-scan-chapter-241",
				"doraemon-scan-chapter-242",
				"doraemon-scan-chapter-243",
				"doraemon-scan-chapter-244",
				"doraemon-scan-chapter-245",
				"doraemon-scan-chapter-246",
				"doraemon-scan-chapter-247",
				"doraemon-scan-chapter-248",
				"doraemon-scan-chapter-249",
				"doraemon-scan-chapter-250",
				"doraemon-scan-chapter-251",
				"doraemon-scan-chapter-252",
				"doraemon-scan-chapter-253",
				"doraemon-scan-chapter-254",
				"doraemon-scan-chapter-255",
				"doraemon-scan-chapter-256",
				"doraemon-scan-chapter-257",
				"doraemon-scan-chapter-258",
				"doraemon-scan-chapter-259",
				"doraemon-scan-chapter-260",
				"doraemon-[ban-dep]-chapter-261",
				"doraemon-[ban-dep]-chapter-262",
				"doraemon-[ban-dep]-chapter-263",
				"doraemon-[ban-dep]-chapter-264",
				"doraemon-[ban-dep]-chapter-265",
				"doraemon-[ban-dep]-chapter-266",
				"doraemon-[ban-dep]-chapter-267",
				"doraemon-[ban-dep]-chapter-268",
				"doraemon-[ban-dep]-chapter-269",
				"doraemon-[ban-dep]-chapter-270",
				"doraemon-[ban-dep]-chapter-271",
				"doraemon-[ban-dep]-chapter-272",
				"doraemon-[ban-dep]-chapter-273",
				"doraemon-[ban-dep]-chapter-274",
				"doraemon-[ban-dep]-chapter-275",
				"doraemon-[ban-dep]-chapter-276",
				"doraemon-[ban-dep]-chapter-277",
				"doraemon-[ban-dep]-chapter-278",
				"doraemon-[ban-dep]-chapter-279",
				"doraemon-[ban-dep]-chapter-280",
				"doraemon-[ban-dep]-chapter-281",
				"doraemon-[ban-dep]-chapter-282",
				"doraemon-[ban-dep]-chapter-283",
				"doraemon-[ban-dep]-chapter-284",
				"doraemon-[ban-dep]-chapter-285",
				"doraemon-[ban-dep]-chapter-286",
				"doraemon-[ban-dep]-chapter-287",
				"doraemon-[ban-dep]-chapter-288",
				"doraemon-[ban-dep]-chapter-289",
				"doraemon-[ban-dep]-chapter-290"
		};
		int from = 1; //Integer.parseInt(prop.getProperty(KEY_FROM));
		int to = 2; //Integer.parseInt(prop.getProperty(KEY_TO));
		for (int chapter = from; chapter <= to; chapter++) {
			new DownloadHamtruyen(a[chapter - 1], chapter);
		}
	}


}
