var volumes = [
  [
    "Bloomers and the Monkey King",
    "No Balls!",
    "Sea Monkeys",
    "They Call Him... the Turtle Hermit",
    "Oo! Oo! Oolong!",
    "So Long, Oolong!",
    "Yamcha and Pu'ar",
    "One, Two, Yamcha-cha!",
    "Dragon Balls in Danger!!",
    "Onward to Fry-Pan...",
    "... And Into the Fire!"
  ],
  [
    "In Search of Kame-Sen'nin",
    "Fanning the Flame",
    "Kamehameha!",
    "At Sixes and Sevens",
    "One Goal, One Enemy",
    "Carrot Top",
    "Who's Got My Balls?!",
    "At Last... the Dragon!",
    "Just One Wish!!",
    "Full Moon",
    "The End of the Tale",
    "Separate Ways",
    "The High Price of Education"
  ],
  [
    "A Rival Arrives!!",
    "Who's That Girl?!",
    "Nothing to Sneeze At",
    "Let the Training Begin!",
    "Bad Day at Turtle Rock",
    "Milk Run",
    "It Only Gets Harder",
    "Let the Contest Begin!!",
    "Hard Work Pays!!",
    "Strongest Under the Heavens!",
    "The Battle is Set!!",
    "Match No. 1"
  ],
  [
    "Match No. 2",
    "Water and Cheesecake",
    "Monster Smash",
    "The Tail of Goku",
    "Kuririn vs. Jackie Chun",
    "The Big Fight",
    "The Mysterious Jackie Chun",
    "The Name of the Game is Namu",
    "Taking the Air",
    "The Final Match",
    "The Kamehameha",
    "One Lucky Monkey"
  ],
  [
    "The Big Sleep",
    "Jackie's Shocking Secret",
    "And the Crowd Goes Wild!!",
    "The Climax Approaches!",
    "The Final Blow",
    "On the Road Again",
    "The Red Ribbon",
    "The Dragon Ball Scramble",
    "The Storming of Muscle Tower",
    "The Flexing of Muscle Tower",
    "Devil on the Third Floor",
    "Purple People Beater"
  ],
  [
    "The 4½ Tatami Mat Flip",
    "The Ninja Split!",
    "Mechanical Man No. 8",
    "The Horrible... Jiggler!",
    "How to Unjiggle a Jiggler",
    "Muscle Tower's Final Hour",
    "Go West, Young Goku...",
    "Monkey in the City",
    "Bulma and Goku",
    "Bulma's Big Mistake!!",
    "The Turtle is Spotted!",
    "The Blue Meanies"
  ],
  [
    "The Wrong Turtle to Mess With",
    "The Pirates' Trap",
    "Robot in Waiting!",
    "The Treasure!",
    "Bright Blue's Eyes",
    "The Great Escape",
    "Run, Run, Run!!",
    "The Three Stolen Dragon Balls",
    "Chased to Penguin Village!",
    "The Broken Dragon Radar",
    "The Stolen Dragon Radar",
    "The Karin Sanctuary"
  ],
  [
    "Taopaipai the Assassin",
    "The Devastating Dodon-Pa!!!",
    "The Great Climb",
    "Sage of the Karin Tower",
    "A Drink of Water",
    "Son Goku Strikes Back!",
    "Battle in the Sanctuary!!",
    "Taopaipai at the Brink",
    "Goku's Charge",
    "Attack From the Sky!",
    "The Fall of Commander Red",
    "The Triumph!"
  ],
  [
    "The Lost Dragon Ball",
    "The All-Seeing Crone",
    "The Five Champions",
    "Battle of the Bleeders",
    "The Devil's Cesspool",
    "Goku at the Plate!",
    "The Power of Goku",
    "The Beam of Evil",
    "The Last Champion",
    "Strong vs. Strong",
    "To Win by a Tail",
    "Son Gohan"
  ],
  [
    "A Second Helping of Pilaf",
    "The Pilaf Machine",
    "Reenter the Dragon",
    "Go, Goku, Go!",
    "Return to the Tournament",
    "The Qualifying Rounds",
    "King Chappa",
    "The Doctored Lottery",
    "Yamcha's Kamehameha!",
    "The Cruelty of Tenshinhan",
    "The Full Moon Grudge",
    "Look Out! The Dodon Blast!"
  ],
  [
    "Kuririn's Master Plan",
    "Goku vs. Panpoot",
    "Tenshinhan vs. Jackie Chun",
    "Young Tenshinhan",
    "Goku vs. Kuririn",
    "Goku vs. Kuririn, Part 2",
    "Goku vs. Kuririn, Part 3",
    "Goku vs. Tenshinhan",
    "The Volleyball Play",
    "The Fist of the Sun",
    "Tsuru-Sen'nin",
    "The Arms Race"
  ],
  [
    "Desperation Move",
    "Up in the Air",
    "The Death of Kuririn",
    "Target: Tenka'ichi Budōkai",
    "We Need You, Goku!",
    "The Weirdo with the Ball",
    "Yajirobe's Prey",
    "The Martial Artist Hunters",
    "Goku vs. Tambourine",
    "Piccolo Descends!",
    "Goku vs. The Demon King",
    "Goku... Loses?"
  ],
  [
    "The Muten-Rōshi's Decision",
    "The Mafū-Ba",
    "The Demon King of Old... Restored!",
    "Go Ask Karin!",
    "World Domination",
    "Karin's Quandary",
    "The Superest Super Water!!!",
    "Piccolo's World",
    "Tenshinhan's Decision!!",
    "Tenshinhan vs. Drum",
    "Guess Who's Back?",
    "Fury"
  ],
  [
    "The Immortal Battle",
    "Goku's Greatest Crisis!",
    "The Blasted Earth",
    "Goku's Final Gamble",
    "The Fist of Son Goku",
    "The Nyoi-bō's Secret",
    "The Heaven of Kami-sama",
    "Enter God",
    "Shen Long Resurrected!",
    "The Reunion",
    "New Challengers",
    "The 8 Finalists"
  ],
  [
    "Tenshinhan vs Taopaipai",
    "The Assassin's Struggles",
    "Goku Gets Married!",
    "Kuririn vs. Demon Junior",
    "Kuririn vs. Demon Junior, Part 2",
    "Yamcha vs. Shen",
    "Shen",
    "Goku vs. Tenshinhan",
    "Goku vs. Tenshinhan, Part 2",
    "Tenshinhan's Secret Move!",
    "The Two Weak Points",
    "Kami-sama vs. the Demon King"
  ],
  [
    "God's Miscalculation",
    "The Fated Showdown!",
    "Testing the Waters",
    "The Real Fight",
    "The Super Kamehameha",
    "Panic at the Tenka'ichi Budōkai!",
    "Piccolo's Super Giantification Spell",
    "Goku's Fight",
    "The Demon King's Final Gamble",
    "Piccolo Destroys Everything!",
    "The 10 Count",
    "The Last Gasp!",
    "The Fate of the Strongest",
    "The Gift of the Dragon Balls"
  ],
  [
    "The Mysterious Warrior From Space",
    "Kakarrot",
    "Tails of Future Not-Quite-Past",
    "An Enemy in Common",
    "An Unexpected Strength",
    "Nothing Up My Sleeve...",
    "Piccolo's Farewell to Arms!?",
    "A Surprise Appearance",
    "Goku's Last Chance",
    "Sayonara, Goku"
  ],
  [
    "A Warrior in Hell",
    "Gohan and Piccolo",
    "Son Gohan, the Inconsolable",
    "Deeds Done by the Full Moon",
    "Goku and Gohan's Training Begins!!!",
    "Masters and Students",
    "The Hardest Time of His Death",
    "Closer... Closer...",
    "The Day of the Saiyans",
    "Let the Games Begin!",
    "One Down...",
    "Heroes in Terror"
  ],
  [
    "Hope Runs Out",
    "The Last Blast",
    "Goku, Hurry!",
    "Back From the Other Side",
    "The Time Draws Near",
    "The Death of a God!!",
    "Piccolo's Last Stand",
    "The Quiet Wrath of Son Goku",
    "Vengeance",
    "The Mystery of the Kaiō-ken",
    "The Last of Nappa",
    "Mano a Maniac!!",
    "Page Gallery"
  ],
  [
    "The Decisive Battle at Last!",
    "Too Much Power?",
    "Battle in the Red Zone!!",
    "The Moon",
    "The Energy Sphere",
    "All That Power...",
    "The Last Heartbeat",
    "Least Resistance",
    "One More... the Sphere!",
    "The Hopes of a Planet",
    "The Worn-Out Warriors",
    "Monkey in the Moon"
  ],
  [
    "Goku's Request",
    "The Bittersweet End",
    "Destination Namek",
    "The Mysterious Spaceship",
    "3... 2... 1... Lift Off!",
    "The Return of Vegeta",
    "Planet Namek, Cold and Dark",
    "The Mysterious Strangers",
    "Vegeta's True Power",
    "Goku Returns! Again!",
    "Son Goku's Spaceship",
    "Namekian Fear"
  ],
  [
    "Showdown!",
    "Ten Seconds of Death",
    "Son Gohan Snaps!",
    "Death in Flight",
    "Vegeta vs. Dodoria",
    "Hide and Seek",
    "The Sixth Dragon Ball",
    "The Last Dragon Ball",
    "The Four Dead Heroes",
    "Vegeta vs. Zarbon",
    "Zarbon's True Power",
    "The Great Elder's House"
  ],
  [
    "The Dragon Balls Change Hands",
    "Vegeta's Laughter, Freeza's Rage",
    "Reunion of Terror!",
    "Vegeta in Overdrive!",
    "Brains and Brawn",
    "Premonitions of War",
    "The Enemy of My Enemy...",
    "The Ginyu Force",
    "Five Deadly Fighters",
    "Gurd's Psychic Powers",
    "Vegeta vs. Reacoom",
    "Vegeta vs. Reacoom, Part 2"
  ],
  [
    "Freeza Victorious?!!",
    "Son Gohan's Last Stand",
    "Son Goku Has Landed!",
    "Super Saiyan?",
    "Jheese and Butta",
    "With Allies Like These...",
    "Ginyu Steps In",
    "A Matter of Pride",
    "The Last Three Namekians",
    "Nail, Champion of Namek",
    "The Switch",
    "Goku or Ginyu?!"
  ],
  [
    "Ginyu's Mistake!",
    "The Final Switch",
    "Nail's Sacrifice",
    "The True Dragon God",
    "The Three Wishes",
    "The Last Wish",
    "The Assimilation",
    "The Transformation",
    "Freeza vs. Gohan",
    "Freeza vs. Gohan, Part 2",
    "The Fourth Warrior",
    "Freeza vs. Piccolo"
  ],
  [
    "Freeza vs. Piccolo, Part 2",
    "Freeza's Third Form",
    "Vegeta's Ploy",
    "The Final Transformation",
    "Will It Be Freeza? Or Vegeta?",
    "Son Goku... Resurrected!!",
    "The Ultimate Battle Begins!",
    "The Death of Vegeta",
    "Underwater Battle",
    "Aerial Battle",
    "Hand to Foot",
    "50% Maximum Power",
    "Kaiō-ken times 20!!!"
  ],
  [
    "The Great Genki-Dama",
    "The Last Chance",
    "The Galaxy Strikes Back",
    "Life or Death",
    "The Super Saiyan",
    "The Tables Turn",
    "The End of Namek?",
    "Maximum Desperation",
    "Two Warriors, One Finish",
    "The Two Wishes",
    "The Quiet, Fierce Battle",
    "Son Goku Quits"
  ],
  [
    "Son Goku's Choice",
    "The End of Everything",
    "Namek's End",
    "Where is Goku?",
    "The Coming of King Cold",
    "The Young Man of Mystery",
    "The Second Super Saiyan",
    "Son Goku Comes Home",
    "The Boy From the Future",
    "The Terrifying Message",
    "The Risky Decision",
    "The Gathering of the Warriors"
  ],
  [
    "Slaughter in South City",
    "Yamcha Falls",
    "The Red Ribbon Androids",
    "Powerless!",
    "One Down...",
    "Vegeta Returns!!!",
    "The Androids Unhinged",
    "A Change of Plans",
    "Trunks Returns",
    "A Sound of Thunder",
    "Dr. Gero's Laboratory",
    "The Androids Awake!"
  ],
  [
    "#17, #18... #16?",
    "The Androids Walk Among Us",
    "Vegeta vs. Android #18",
    "Vegeta vs. Android #18, Round 2",
    "The Androids at Ease",
    "Retreat and Regroup",
    "Kami's Conditions",
    "A Discovery",
    "The Time Machine",
    "Kami-sama's Vision",
    "Kami-sama and the Demon King Become One",
    "Cell"
  ],
  [
    "Ginger Town Showdown",
    "A Farewell to Arms",
    "Cell Laughs Last",
    "Son Goku Awakens",
    "The Super Saiyans' Training",
    "Piccolo vs. #17",
    "Waiting in the Wings",
    "Cell vs. the Androids",
    "New Piccolo... Last Piccolo?",
    "Cell vs. #16",
    "#16 Summons His Power",
    "The New Cell"
  ],
  [
    "Goku Meets Cell",
    "Vegeta and Trunks Emerge",
    "Vegeta's Confidence",
    "Beyond the Super Saiyan",
    "Super Vegeta",
    "Cell's Last Chance",
    "The Evil Truce",
    "Vegeta vs. Trunks?",
    "The Complete Cell",
    "A Reversal",
    "The Final Flash",
    "Trunks Steps In"
  ],
  [
    "Trunks Surpasses His Father",
    "The Balance of Power",
    "Cell's Idea",
    "Message of Terror",
    "The Emergence",
    "The Calm Before the Storm",
    "Cell vs. the Army",
    "The New Kami-sama",
    "The Cell Game Begins!",
    "Heroes Assemble!",
    "Hercule, Champion of the World",
    "s: The Story"
  ],
  [
    "Cell vs. Son Goku",
    "Full Power",
    "The Highest Level",
    "Ring Out",
    "Kamehameha Full Power",
    "Last Resort",
    "The Successor",
    "Let's Go, Gohan!",
    "The Rage of Son Gohan?",
    "#16's Secret Weapon",
    "The Little Cells",
    "Gohan Unleashed!"
  ],
  [
    "Cell vs. Gohan",
    "The Ultimate Kamehameha",
    "Cell, Brought to Bay",
    "The End of the Cell Game",
    "Gohan's Pain",
    "The Tables Turn",
    "Father and Son",
    "Kamehameha vs. Kamehameha",
    "Finale",
    "Farewell, Warriors",
    "The Other Outcome",
    "Peace to the Future"
  ],
  [
    "Herculopolis High",
    "Undercover",
    "A Hero Is Born!",
    "Videl's Emergency!!",
    "Revealed!!!",
    "Strongest in the Heavens!",
    "Let the Training Begin!",
    "Videl Learns to Fly",
    "Fathers",
    "The Dragon Team Returns!",
    "The Preliminaries Begin",
    "The Two Little Warriors"
  ],
  [
    "Trunks vs. Goten",
    "Trunks vs. Goten, Part 2",
    "The Winner!",
    "Hercule's Courage!",
    "The Mysterious Duo",
    "The Finalists are Chosen!",
    "The First Two Fights",
    "Shin's Surprise",
    "Videl... Battered",
    "Gohan Gets Mad!!",
    "The Plot of the Lords",
    "The Stolen Energy",
    "The Terrible Mystery"
  ],
  [
    "Bobbidi the Warlock",
    "The Evil Masters",
    "The Descent",
    "Stage One: Focus",
    "Stage Two: Yakon",
    "Yakon's Treat",
    "Battle Royale",
    "Mighty Mask Shows His Power!",
    "We Have a Winner!!",
    "A Wicked Soul Revealed",
    "Goku vs. Vegeta",
    "Vegeta's Pride",
    "Two Battles to the Death",
    "Countdown"
  ],
  [
    "The Djinn Awakens?!",
    "Can This Be Boo?!",
    "The Menace of Boo",
    "Terrifying Power",
    "Vegeta vs. Boo",
    "Boo Gets Mad",
    "The Mastermind's Demise",
    "Farewell, Proud Warrior",
    "Back to the Nightmare",
    "A Slim Hope",
    "Bobbidi's Revenge",
    "A Time of Trial",
    "The Zeta Sword"
  ],
  [
    "Goku Meets Boo!!",
    "Super Saiyan Level 3!!!",
    "Boo Unbound",
    "Goku's Time",
    "Goku Goes Back",
    "Where is Gohan?",
    "The Zeta Sword",
    "The Fusion Succeeds...?!",
    "The Earth's Secret Weapon!",
    "Super Fusion!",
    "The Friends of the Djinn",
    "The Creature of Wrath",
    "Two Boos?!"
  ],
  [
    "The New, Terrible Boo",
    "Humanity's End",
    "Return to the Room of Spirit and Time",
    "The Confidence of Gotenks!!",
    "The Extreme Confidence of Gotenks!!",
    "The Kamikaze Ghost!",
    "The Door Closes",
    "Escape From the Time Dimension",
    "Super Gotenks!",
    "Super Fusion Unleashed!!",
    "Deep Trouble!!",
    "Gohan's Counterattack!",
    "What's Boo Doing?!",
    "Ambush!",
    "A Turn of the Tables",
    "Enter a Savior?!",
    "Will the Potara Prevail?!"
  ],
  [
    "The Ultimate Combination!!",
    "The Ultimate Fighter",
    "Vegerot's Game",
    "Two Inside Boo",
    "Boos Inside Boo",
    "The Boo of Pure Evil",
    "Battle for the Universe",
    "Vegeta and Kakarrot",
    "Vegeta Puts His Life on the Line!",
    "The End of Super Saiyan 3",
    "Vegeta's Plan",
    "A Message to Earth",
    "Just Not Enough",
    "Battle's End",
    "A Happy Ending... And Then...",
    "10 Years After",
    "Farewell, Dragon World!"
  ]
];