package common.util;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

import org.junit.Ignore;
import org.junit.Test;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class AdEmail {

	// Email sender configuration
	private String username = "hotro@itrithuc.vn";
	private String password = "123312a@a";
	private String alias = "iTrithuc";
	private String host = "smtp.gmail.com";
	private int port = 465;

	@Test
	public void testSendTextByGmail() throws Exception {
		

		Recipient[] a = {
				/*
				new Recipient("Nguyễn Văn Huyên", "lockex1987@gmail.com"),
				new Recipient("Phan Đức Dũng", "ducdung872001@gmail.com"),
				
				new Recipient("phuonglinh", "phuonglinhdoan96@gmail.com"),
				new Recipient("Trần Hải Linh", "tranhailinh6090@gmail.com"),
				new Recipient("Trần Nhật Lệ", "trannhatle268@gmail.com"),
				new Recipient("Lê Minh Đức", "m.duc151094@gmail.com"),
				new Recipient("Thanh", "thanhkhmt2@gmail.com"),
				new Recipient("Nguyễn Văn Lăng", "nvlang0411@gmail.com"),
				new Recipient("Đăng Kiên", "kien.ptit9293@gmail.com"),
				new Recipient("Từ Minh Hoàng", "minhhoangibio@gmail.com"),
				new Recipient("Mai Hùng Cường", "hungcuong2911@gmail.com"),
				new Recipient("Duy Hoat", "duyhoat191088@gmail.com"),
				new Recipient("trương đắc tú", "tudark179@gmail.com"),
				new Recipient("Đào Quang Huy", "huydq124@gmail.com"),
				new Recipient("Đào Quang Huy", "huydq124@gmail.com"),
				new Recipient("nguyễn tiến phú", "informationvn.vn@gmail.com"),
				new Recipient("trantuan24bk", "trantuan24bk@gmail.com"),
				new Recipient("Tuan Nguyen", "tuangtvt@gmail.com"),
				new Recipient("Tuan Nguyen", "tuangtvt@gmail.com"),
				new Recipient("Vũ Phan Trung Dũng", "dungvpt@gmail.com"),
				new Recipient("Phí Thị Thu", "phithuptit@gmail.com"),
				new Recipient("Đặng Đình Hoàng", "hoang2010k5@gmail.com"),
				new Recipient("Đặng Văn Hảo", "danghao.hut.edu@gmail.com"),
				new Recipient("Đặng Văn Hảo", "danghao.hut.edu@gmail.com"),
				new Recipient("Nguyễn Đức Toàn", "nguyenductoandtvt@gmail.com"),
				new Recipient("Nguyễn Đức Toàn", "nguyenductoandtvt@gmail.com"),
				new Recipient("Nguyễn Đức Toàn", "nguyenductoan_dt9@yahoo.com"),
				new Recipient("Phan Đăng Duy", "pdangduy1105@gmail.com"),
				new Recipient("Trần Anh Dũng", "dungtrantad@gmail.com"),
				new Recipient("Nguyen Quoc Hoan", "hoancdt2bk@gmail.com"),
				new Recipient("Đoàn Thiên Phúc", "m.rdoan1996@gmail.com"),
				new Recipient("Hoàng Văn Hữu", "hoangvanhuu89@gmail.com"),
				new Recipient("Minh Hiền", "Nm.hien2504@gmail.com"),
				new Recipient("Vũ Hải Linh Phương", "linhphuong0892@gmail.com"),
				new Recipient("Lê Hoàng Diệu Linh", "linhlh@gmail.com.vn"),
				new Recipient("Vũ Ngọc Đức", "vuduchvktqs@gmail.com"),
				new Recipient("Nguyễn Tài Đại", "taidai1569@gmail.com"),
				new Recipient("Nguyễn Huy Hoàng", "hoang.nguyenhuy899@gmail.com"),
				new Recipient("Nguyễn Văn Hiếu", "hieunguyen1k9@gmail.com"),
				new Recipient("Vũ Khánh Duy", "vukhanhduyy@gmail.com"),
				new Recipient("Nguyễn Quang Phúc", "phuc@gmail.com"),
				new Recipient("Khuất Thanh Sáng", "ktshut8602@gmail.com"),
				new Recipient("Trang", "Dangthidoantrang93@gmail.com"),
				new Recipient("Võ Đại Hùng", "vodaihung178@gmail.com"),
				new Recipient("Đào  Thị Trang", "tranghubt90@gmail.com"),
				new Recipient("Vũ Thị Huyền", "huyenvu23hd@gmail.com"),
				new Recipient("Đào Văn Vĩnh", "daovinhvt@gmail.com"),
				new Recipient("Đoàn Văn Hùng", "doanvanhung1234@gmail.com"),
				new Recipient("Nguyễn Thị Huyền Trangg", "doepro68@gmail.com"),
				new Recipient("Hồ Tấn Lộc", "41202002@hcmut.edu.vn"),
				new Recipient("Hồ Tấn Lộc", "41202002@hcmut.edu.vn"),
				new Recipient("Hồ Tấn Lộc", "41202002@hcmut.edu.vn"),
				new Recipient("Hồ Tấn Lộc", "41202002@hcmut.edu.vn"),
				new Recipient("Nguyễn Văn Tùng", "tungnv1902@gmail.com"),
				new Recipient("Nguyễn Tiến Đông", "dongnt1612@gmail.com"),
				new Recipient("Nguyễn thanh trúc", "truccd_04_b3@yahoo.com"),
				new Recipient("Tran Viet An", "vietan92.th@gmail.com"),
				new Recipient("Xuân", "ntxuan.hba93@gmail.com"),
				new Recipient("Mẫn Văn Thắng", "manvanthang@gmail.com"),
				new Recipient("Phạm Quốc Thịnh", "phamquocthinh@gmail.com"),
				new Recipient("Nguyễn Quốc Thái", "chuyo2522@gmail.com"),
				new Recipient("Dương Thế Anh", "dta.haui93@gmail.com"),
				new Recipient("Ngô Xuân Việt", "xuanvieta1@gmail.com"),
				new Recipient("Nguyễn Đức Minh", "Namn11@yahoo.com"),
				new Recipient("Lê Trí Minh", "Ltminh.hcmut@gmail.com"),
				new Recipient("Hưng", "hungpn6@gmail.com"),
				new Recipient("Hưng", "hungpn6@gmail.com"),
				new Recipient("Vi Đức Dương", "Namn12@yahoo.com"),
				new Recipient("Nguyễn Thị Thúy", "thuynt180796@gmail.com.vn"),
				new Recipient("Phạm Tiến Hải", "pth241@gmail.com"),
				new Recipient("Trần Trung Hiếu", "hmobile.188891@gmail.com"),
				new Recipient("Nguyễn Văn Hoàng", "hoangnv.vtdt@gmail.com"),
				new Recipient("Nguyễn Quang Thắng", "nguyenthangptit2611@gmail.com"),
				new Recipient("Võ Thị Phương An", "vothiphuongan@gmail.com"),
				new Recipient("Phan Thanh Nga", "ptnga.hdg@gmail.com"),
				new Recipient("LÂM THANH TÙNG", "lamthanhtung.94@gmail.com"),
				new Recipient("Nguyễn thành tâm", "Nttam22111992@gmail.com"),
				new Recipient("Vũ Đình Hùng", "fantamasxy9999@gmail.com"),
				new Recipient("Nam", "trinhnam01633760233@gmail.com"),
				new Recipient("Đinh Thị Mai Chi", "dinhmaichi5296@gmail.com"),
				new Recipient("Đinh Minh Tiến", "Tiendinhminh@gmail.com"),
				new Recipient("Nguyễn mạnh cường", "cuongbkhn90@gmail.com"),
				new Recipient("nguyễn văn dật", "dat.nguyenvan105@gmail.com"),
				new Recipient("pham van phuc", "phucmobile321@gmail.com"),
				*/
				
				/*
				new Recipient("Phạm Doãn Huy", "binhyennoidau103195@gmail.com"),
				new Recipient("Lê Thị Thu Thơm", "lethuthom94@gmail.com"),
				new Recipient("Phạm Sơn Tùng", "tung160196@gmail.com"),
				new Recipient("Nguyễn Văn Tân", "nguyentan92bg@gmail.com"),
				new Recipient("Dương Xuân Hùng", "hungdx.vta@gmail.com"),
				new Recipient("Vũ Văn Toản", "toanvu080691@gmail.com"),
				new Recipient("Nguyễn Trung Thành", "trungthanhvt46@gmail.com"),
				new Recipient("Nguyễn Trung Thành", "trungthanhvt46@gmail.com"),
				new Recipient("Phạm Trung Anh", "anhpt1205@gmail.com"),
				new Recipient("Minh Công", "minhcong.9x.db@gmail.com"),
				new Recipient("Lê Hoàng Anh", "1la.hoanganhbk@gmail.com"),
				new Recipient("Nam", "khoanam.lenguyen@gmail.com"),
				new Recipient("Ho Tan Duc", "duc.hotan2312@gmail.com"),
				new Recipient("Nguyễn Thị Hà", "nguyenhaktxd52@gmail.com"),
				new Recipient("Trần Hải Phú", "phutranhai93@gmail.com"),
				new Recipient("Nguyễn Đức An", "ngducan80@gmail.com"),
				new Recipient("Lê Trần Trung Hiếu", "letrantrunghieu21@gmail.com"),
				new Recipient("Nguyễn Anh Đức", "anhducds@gmail.com"),
				new Recipient("Nguyễn Ngọc Quyết", "qt14xx@gmail.com"),
				new Recipient("Nguyễn Ngọc Anh Khoa", "khoanna281095@gmail.com"),
				new Recipient("Phan Văn Hưng", "hungphan227@gmail.com"),
				new Recipient("Trần Quang Bình", "quangbinhtran35@gmail.com"),
				new Recipient("Nguyen Dinh Dung", "nddung1994@gmail.com"),
				new Recipient("Nguyen Huu Phuoc", "phuocnguyenhuu.ee@gmail.com"),
				new Recipient("Kiều Huyền", "kieuhuyen297@gmail.com"),
				new Recipient("Nguyễn Thị Linh", "linhhust143@gmail.com"),
				new Recipient("Trần Đình Chung", "chungk57uet@gmail.com"),
				new Recipient("La Văn Quân", "lavanquan_kstn_cntt@gmail.com"),
				new Recipient("Phạm Hoàng Nam", "nambk51@gmail.com"),
				new Recipient("nguyễn thanh định", "nguyenthanhdinh9@gmail.com"),
				new Recipient("Dương Minh Tuấn", "sumpv1@gmail.com"),
				new Recipient("Nguyễn Văn Viên", "nguyenvanvien92@gmail.com"),
				new Recipient("Nguyễn Văn Viên", "nguyenvanvien92@gmail.com"),
				new Recipient("Nguyễn Văn Viên", "nguyenvanvien92@gmail.com"),
				new Recipient("Lê Phi Hạnh", "phihanhiq123@gmail.com"),
				new Recipient("khắc phượng", "khacphuonght92@gmail.com"),
				new Recipient("Thu Thao Phan", "thuthaophan5690@gmail.com"),
				new Recipient("Đoàn Văn Trà", "travandoan@gmail.com"),
				new Recipient("Nguyen Tien Thien", "thienbk1908@gmail.com"),
				new Recipient("Nguyễn Văn Hiếu", "tranhieu254@gmail.com"),
				new Recipient("Nguyễn Thị An", "annt495022@gmail.com"),
				new Recipient("Nguyễn Ngọc Cường", "cuongk49cntt@gmail.com"),
				new Recipient("Nguyễn Đình Thảo", "linhtt11@viettel.com.vn"),
				new Recipient("Nguyễn Thị Thu Nga", "ntnga213@gmail.com"),
				new Recipient("Trần Hà Ngọc Thiện", "tranhangocthien@gmail.com"),
				new Recipient("Tình", "Tinhlion0@gmail.com"),
				new Recipient("Đào Huy Hiệp", "mrhiep2810@gmail.com"),
				new Recipient("Nguyễn Thị Huyền Trang", "huyentrang53.16@gmail.com"),
				new Recipient("hai95", "nduc712@gmail.com"),
				new Recipient("Đàm Hồng Duân", "duandh204@gmail.com"),
				new Recipient("Đào Ngọc Long", "longptit08@gmail.com"),
				new Recipient("Dương Minh Hùng", "duongminhhung2411@gmail.com"),
				new Recipient("Lê Bá Chung", "lebachungtdh@gmail.com"),
				new Recipient("Dương Tấn Thành", "thanhbe68@gmail.com"),
				new Recipient("Nguyễn Thái Long", "longnt251168@gmail.com"),
				new Recipient("Vũ Hoàng Luân", "hoangluan803@gmail.com"),
				new Recipient("Nguyễn Văn Phương", "nvphuongdt05@gmail.com"),
				new Recipient("Nguyễn Trường Sơn", "sonvt@viettet.com.vn"),
				new Recipient("Ngô Thị Mỹ Nữ", "numnt@gmail.com"),
				new Recipient("ngoctinhct55@gmail.com", "ngoctinhct55@gmail.com"),
				new Recipient("Nguyễn Thành Đông", "nguyenthanhdong0109@gmail.com"),
				new Recipient("Nguyễn Thế Hiếu", "hieuntgtvt@gmail.com"),
				new Recipient("Đặng Thái Phong", "phongdt712@gmail.com"),
				new Recipient("Đặng Đức Duy", "ddduy88@gmail.com"),
				new Recipient("Đặng Đức Duy", "ddduy88@gmail.com"),
				new Recipient("Bùi Đức Hưng", "buiduchung.bkhn@gmail.com"),
				new Recipient("Lưu Trọng Khôi", "luukhoiptit92@gmail.com"),
				new Recipient("Vũ Thái Hà", "vuthaiha92@gmail.com"),
				new Recipient("buitoan", "buiminhtoan.6789@gmail.com"),
				new Recipient("nguyễn xuân đông", "xuandong46@gmail.com"),
				new Recipient("Huỳnh Tấn Đạt", "tandathuynh148@gmail.com"),
				new Recipient("nguyenvannam", "namnv.1104@gmail.com"),
				new Recipient("Hoàng Đình Tiệp", "hdtiep@gmail.com"),
				new Recipient("Trần Thị Kim Kim", "kimkim@gmail.com"),
				new Recipient("Nguyễn Thành Đạt", "thanhdatna2892@gmail.com"),
				new Recipient("Trình Lê Hằng", "Lehang@viettel.com"),
				new Recipient("Nguyễn Chín Triều", "vanxuong125@gmail.com"),
				new Recipient("Nguyễn Nam Quang", "namquang89@gmail.com"),
				new Recipient("Lê Quốc Toàn", "toanle0688@gmail.com"),
				new Recipient("Đàm Thị Ngọc Huyền", "dnhuyen@gmail.com"),
				new Recipient("Đầu Thị Loan", "loanhn07@gmail.com"),
				new Recipient("Nguyễn Huy Hoàng", "lhp.huyhoangnguyen@gmail.com"),
				new Recipient("Châu", "minhchau768@gmail.com"),
				new Recipient("Lê Minh Đức", "thanhcavietnam151094@gmail.com"),
				new Recipient("Phạm Cao Tín", "ms.ef.24@gmail.com"),
				new Recipient("Nguyễn Hồng Phi", "nguyenhongphi9x@gmail.com"),
				new Recipient("Trịnh Văn Hoan", "hoanktvt@gmail.com"),
				new Recipient("Hoàng Minh Tiến", "tienhm@gmail.com.vn"),
				new Recipient("Ngọc Hải", "ngochai241187@gmail.com"),
				new Recipient("Ngọc Hải", "ngochai241187@gmail.com"),
				new Recipient("Ngọc Hải", "ngochai241187@gmail.com"),
				new Recipient("Nguyễn Văn Hiếu", "nguyenhieu59910170@gmail.com"),
				*/
				
				/*
				new Recipient("Trần Khắc Chung", "khacchungbka@gmail.com"),
				new Recipient("Duong Ngoc Luon", "luon.duongngoc@gmail.com"),
				new Recipient("Nguyễn Thị Tâm", "tamntptit@gmail.com"),
				new Recipient("Phạm Ngọc Linh", "phamlinh52v@gmail.com"),
				new Recipient("Phạm Ngọc Linh", "phamlinh52v@gmail.com"),
				new Recipient("Nguyễn Văn Hưởng", "huong.nguyenvan2102@gmail.com"),
				new Recipient("Trần Huy Cường", "loptruongbk1@gmail.com"),
				new Recipient("Trần Huy Cường", "loptruongbk@gmail.com"),
				new Recipient("Mai Phi Hùng", "phihung1@gmail.com"),
				new Recipient("Quốc", "nguyenbaoquoc1209@gmail.com"),
				new Recipient("Lương Khải Hoàn", "abcd@gmail.com"),
				new Recipient("Đào Duy Tuấn", "xepit90@gmail.com"),
				new Recipient("Nguyễn Nho Quốc Việt", "n2qv1994@gmail.com"),
				new Recipient("Phan Thị Thùy Dung", "phanthuydung@gmail.com"),
				new Recipient("Nguyễn Đình Tâm", "dinhtam94@gmail.com"),
				new Recipient("Hà Mến", "hathumen@gmail.com"),
				new Recipient("Phạm Tiến Đạt", "phamhien04051990@gmail.com"),
				new Recipient("Vũ Hùng Cường", "Rausachqn@gmail.com"),
				new Recipient("Trần Văn Dũng", "dungtvk48@gmail.com"),
				new Recipient("Bùi Trung Hiếu", "trunghieu.95.hp@gmail.com"),
				new Recipient("Bùi Thanh Hà", "thanhhabui.ptit@gmail.com"),
				new Recipient("văn", "kevinvan994@gmail.com"),
				new Recipient("Nguyễn Danh Linh", "danhlinhhd@gmail.com"),
				new Recipient("Hà Quang Việt", "havietmta94@gmail.com"),
				new Recipient("Nguyễn Văn Trường", "Vkga2010@gmail.com"),
				new Recipient("nguyễn đức khoa", "khoa8x@gmail.com"),
				new Recipient("Ngô Viết Vũ", "ngovietvu@gmail.com"),
				new Recipient("Đỗ Thị Huệ", "dohueatk@gmail.com"),
				new Recipient("Đỗ Thị Huệ", "dohueatk@gmail.com"),
				new Recipient("Phạm Trung Cảnh", "clohfptc@gmail.com"),
				new Recipient("Phạm Văn Tiến", "123456789@gmail.com"),
				new Recipient("Nguyễn Văn Hải", "nguyen.vanhai145@gmail.com"),
				new Recipient("Mỹ Trinh", "mytrinhnguyet0306@gmail.com"),
				new Recipient("Ninh Thị Hồng Nhung", "ninhthnhung@gmail.com"),
				new Recipient("Trần Trọng Hiếu", "tronghieu.tt2368@gmail.com"),
				new Recipient("Nguyễn Tuấn Cường", "abcdef@gmail.com.vn"),
				new Recipient("Nguyễn Tuấn Cường", "nguyencuong232259@gmail.com"),
				new Recipient("Lê Trọng Thảo", "ltthao2551@gmail.com"),
				new Recipient("Nguyễn Minh Nhựt", "minhnhut030788@gmail.com"),
				new Recipient("PhanVanThang", "thangvnairlines@gmail.com"),
				new Recipient("Nguyễn Ngọc Khánh", "mrngockhanh.bb@gmail.com"),
				new Recipient("Trần Thị Nhung", "nhungtran151192@gmail.com"),
				new Recipient("chim thi thanh", "evythanh@gmail.com"),
				new Recipient("Triệu", "nguyentrongtb@gmail.com"),
				new Recipient("Đỗ Thanh Thúy", "thanhthuy.dhtd@gmail.com"),
				new Recipient("NGUYEN NGOC TIEN", "nntientmtc@gmail.com"),
				new Recipient("Nguyễn Việt Dũng", "vietdung531994@gmail.com"),
				new Recipient("Dương Đình Thuận", "thuan0610@gmail.com"),
				new Recipient("Thanh ha", "thanhha.le0809@gmail.com"),
				new Recipient("Thanh ha", "thanhha.le0809@gmail.com"),
				new Recipient("Phạm Nguyễn Ngọc Biên", "pham.bien10@gmail.com"),
				new Recipient("Nguyễn Văn Hùng", "Namn13@yahoo.com"),
				new Recipient("Trần Văn Khải", "khaikthd@gmail.com"),
				new Recipient("Hapham03", "Hapham3694@gmail.com"),
				new Recipient("Vũ Duy Nhất", "nhatvuduy@gmail.com"),
				new Recipient("Ha Bui Thai", "habui1181987@gmail.com"),
				new Recipient("Nguyễn Thị Thếp", "nguyenthep268@gmail.com"),
				new Recipient("Nguyễn Thanh Trà", "nguyenthanhtra.ptit@gmail.com"),
				new Recipient("Lê Hoàng Hà", "halhktqs@gmail.com"),
				new Recipient("ngô văn dũng", "ngodungdhgtvt@gmail.com"),
				new Recipient("Đỗ Trọng Tuấn", "dotrongtuan@gmail.com"),
				new Recipient("Văn Đình Tùng", "vandinhtung@gmail.com"),
				new Recipient("Nguyễn Thị Lệ", "nguyenthile121195@gmail.com"),
				new Recipient("Nguyễn Ngọc Bảo Châu", "nguyenngocbaochau108@gmail.com"),
				new Recipient("Nguyễn Văn Điệp", "diepnv.hust@gmail.com"),
				new Recipient("Trần Ngọc Sự", "Ngocsu@gmail.com"),
				new Recipient("Tạ  Văn Huy", "tahuy95.th@gmail.com"),
				new Recipient("Vũ Thị Thùy", "thuyvt727@gmail.com"),
				new Recipient("Bùi Văn Kiên", "buikien.dp@gmail.com"),
				new Recipient("Nguyễn Ngọc Hồng", "kimngan.smartcom@gmail.com"),
				new Recipient("Nguyễn Văn Nam", "namcvp230196@gmail.com"),
				new Recipient("Nguyễn Văn Thành", "vanthanht2@gmail.com"),
				new Recipient("ngcaoquang", "nguyencaoquang.95@gmail.com"),
				new Recipient("Ngô Văn Tính", "vantinh.smile.dn94@gmail.com"),
				new Recipient("Nguyễn Văn Hải", "nguyenvanhaiht2907@gmail.com"),
				new Recipient("Nguyễn Hải Yến", "Haiyen.hyn.gg@gmail.com"),
				new Recipient("Lê Tuấn Anh", "ltanh18101993@gmail.com"),
				new Recipient("Vũ Văn Quyết", "quyetvu.auto@gmail.com"),
				new Recipient("Nguyễn Đăng Long", "nguyendanglong198@gmail.com"),
				new Recipient("Nguyễn Đăng Long", "Nguyendanglong198@gmail.com"),
				new Recipient("Vũ Hà Dũng", "vuhadung.vn90@gmail.com"),
				new Recipient("Phạm Văn vinh", "phamvinhit.haui@gmail.com"),
				new Recipient("Nguyễn Thị Thu Phương", "thuphuong.nt96@gmail.com"),
				new Recipient("Hoàng Trọng Hiếu", "tronghieuqhi@gmail.com"),
				*/
				
				/*
				new Recipient("Hoàng Trọng Hiếu", "viettelrd@vietteal.com.vn"),
				new Recipient("Đỗ Minh An", "andm@gmail.com"),
				new Recipient("Nguyễn Văn Chinh", "nguyenchinh88na@gmail.com"),
				new Recipient("Hoàng Ngọc Nhật Anh", "hoangngocnhatanh@gmail.com"),
				new Recipient("Đặng Hữu Thành", "danghuuthanh@gmail.com"),
				new Recipient("Nguyễn Văn Hạnh", "hanh95xx@gmail.com"),
				new Recipient("hoàng thanh hiếu", "htcmupro@gmail.com"),
				new Recipient("Phạm Minh Tuấn", "tuanpm142@gmail.com"),
				new Recipient("Tống Công sơn", "congson.dv10@gmail.com"),
				new Recipient("Hoàng Văn Tùng", "hoangtungmic@gmail.com"),
				new Recipient("Hoàng Văn Tùng", "hoangtungmic@gmail.com"),
				new Recipient("Trần Đức Chính", "chinhtranduc@gmail.com"),
				new Recipient("Đỗ Trung Đức", "ducdotrung@outlook.com"),
				new Recipient("Vũ Minh Chính", "chinhvm.uet.1005@gmail.com"),
				new Recipient("Phạm Anh Tú", "phamanhtu1996@gmail.com"),
				new Recipient("Lê Thanh Sơn", "thanhsonx45@gmail.com"),
				new Recipient("Ngô Thị Đoan Trang", "annango.trang@gmail.com"),
				new Recipient("Phạm Thị Nhung", "phamnhung.94hp@gmail.com"),
				new Recipient("Lê Thảo Huyền", "thaohuyen0895@gmail.com"),
				new Recipient("Dương Đức Đạt", "ducdat2411@live.com"),
				new Recipient("Đỗ Thị Tâm", "tamdt.uet@gmail.com"),
				new Recipient("Võ Quốc Hoài", "hoaivo94@gmail.com"),
				new Recipient("Võ Quốc Hoài", "hoaivo94@gmail.com"),
				new Recipient("Võ Quốc Hoài", "hoaivo94@gmail.com"),
				new Recipient("Nguyễn Vĩnh Khoa", "khoa.uet58@gmail.com"),
				new Recipient("Trần Thị Kim liên", "thuylien1994ptit@gmail.com"),
				new Recipient("Ngô Hoàng Việt", "nhviet3393@gmail.com"),
				new Recipient("Nguyễn Văn Tuyến", "tuyennv100990@gmail.com"),
				new Recipient("Bùi Quang Khiêm", "khiem1910@gmail.com"),
				new Recipient("Nguyễn Quán Quân", "quanquangp@gmail.com"),
				new Recipient("Lê Ngọc Đức", "lengocduc9x@gmail.com"),
				new Recipient("tuananh", "tuananh579959@gmail.com"),
				new Recipient("Lê Hoàng Tùng", "tunghoangwork@gmail.com"),
				new Recipient("Võ Văn Hiếu", "vanhieu1509@gmail.com"),
				new Recipient("Nguyễn Chí Dương", "chiduongdtvt@gmail.com"),
				new Recipient("nguyễn anh tuấn", "nguyenanhtuan381995@gmail.com"),
				new Recipient("Trần Đình Dương", "tranduongthhd@gmail.com"),
				new Recipient("Bùi Văn Linh", "baolinhpt0893@gmail.com"),
				new Recipient("Nguyễn Minh Vương", "minhvuongptit.cntt@gmail.com"),
				new Recipient("Đàm Hoàng Anh", "hoanganh16101995@gmail.com"),
				new Recipient("Nguyễn Khắc Hiếu", "khachieunk@gmail.com"),
				new Recipient("Hứa Thị Ánh", "anhht1@gmail.com"),
				new Recipient("Hoàng Anh Dũng", "had0408@gmail.com"),
				new Recipient("Đinh Ngọc Cường", "ngoccuong6392@gmail.com"),
				new Recipient("Nguyễn Sơn Tùng", "ng.sontung.1995@gmail.com"),
				new Recipient("Tạ Anh Kha", "khata@viettel.com.vn"),
				new Recipient("Nguyễn Đức Dũng", "dungtnut@tnut.edu.vn"),
				new Recipient("Nguyễn Quang Huy", "huynguyenquang3h@gmail.com"),
				new Recipient("Nguyễn Thái Tùng", "thaitung94@gmail.com"),
				new Recipient("Lê Văn Thiêm", "lethiem2205@gmail.com"),
				new Recipient("thu", "ms.thutt95@gmail.com"),
				new Recipient("Phạm Thị Hồng", "hongcoi171293@gmail.com"),
				new Recipient("Phạm Tú Anh", "tuanhpham1991@gmail.com"),
				new Recipient("xuansonvt86", "xuansonvt86@gmail.com"),
				new Recipient("Nguyễn Ngọc Lâm Linh", "nguyenngoclamlinh1993@gmail.com"),
				new Recipient("Nguyễn Viết Hải", "haipro912@gmail.com"),
				new Recipient("Nguyễn Thành Tín", "nguyenthanhtinst93@gmail.com"),
				new Recipient("Phí Xuân Bách", "xuanbach.bk51@gmail.com"),
				new Recipient("Trịnh Đăng Phương", "dangphuong90@gmail.com"),
				new Recipient("Lâm Phát Đạt", "lpdat.kv@gmail.com"),
				new Recipient("Trần Đức Lộc", "Luwaf@outlook.com"),
				new Recipient("Phạm Như Quỳnh", "nhuquynhpham.ruby@gmail.com"),
				new Recipient("Nguyễn Mạnh Tùng", "tungnm@gmail.com"),
				new Recipient("Nguyễn Xuân Phúc", "phucbkfet@gmail.com"),
				new Recipient("Nguyễn Hồng Quân", "quannh.mts@gmail.com"),
				new Recipient("Tuấn", "mrtuansshn@gmail.com"),
				new Recipient("Nguyễn Trọng Tấn", "tannguyen688@gmail.com"),
				new Recipient("Ngô Thị Ba", "ngobautc@gmail.com"),
				new Recipient("Trần Thiện Sang", "sangtranthien@gmail.com"),
				new Recipient("Hao Ngo Van", "ngovanhao@outlook.com"),
				new Recipient("Phạm Đức Mạnh", "phamducmanh223@gmail.com"),
				new Recipient("Dương Tuấn Thông", "tuanthong.duong@gmail.com"),
				new Recipient("Nguyễn Văn Quân", "nguyenquanbn2010@gmail.com"),
				new Recipient("Đặng Ngọc Hào", "haoyobroz@gmail.com"),
				new Recipient("Kiều Minh Đức", "kieuminhduc871995@gmai.com"),
				new Recipient("Phạm Ngọc Linh", "phamngoclinh96th@gmail.com"),
				new Recipient("Nguyễn Văn Việt", "viet.cntt92@gmail.com"),
				new Recipient("Tào Thị Thúy", "taothuy115@gmail.com"),
				new Recipient("Nguyễn Đức Cường", "tokkie.nguyen@gmail.com"),
				new Recipient("Hoàng Quốc Hưng", "ZeusFate@gmail.com"),
				new Recipient("Hoàng Tuấn Anh", "tuananhhg@gmail.com"),
				*/
				
				new Recipient("Ngô Phan Hải", "ngophanhai@gmail.com"),
				new Recipient("nguyễn viết quý", "nguyenvietquy1602@gmail.com"),
				new Recipient("Đinh Văn Nguyện", "nguyentnut@gmail.com"),
				new Recipient("Đoàn Thị Hạnh", "honghanhmk@gmail.com"),
				new Recipient("Nguyễn Như Quỳnh", "nguyennhuquynhktxd@gmail.com"),
				new Recipient("Đỗ Quốc Sự", "quocsu28293@gmail.com"),
				new Recipient("Quỳnh Anh", "quynhanhphan95@gmail.com"),
				new Recipient("Lê Văn Hiện", "vanhien_tphcm@yahoo.com"),
				new Recipient("Nguyễn Công Chiểu", "CongChieubk91@gmail.com"),
				new Recipient("Lê Huy Hoàng", "lhhoang168@gmail.com"),
				new Recipient("Dung Trần", "dungthubt@gmail.com"),
				new Recipient("Nguyễn Mạnh Hòa", "hoanm@tiin.vn"),
				new Recipient("Nguyễn Thị Phương Dung", "nguyenthiphuongdung92@gmail.com"),
				new Recipient("Nguyễn Minh Sơn", "nguyenminhson1110@gmail.com"),
				new Recipient("Nguyễn Đình Thịnh", "thinhnd1902@gmail.com"),
				new Recipient("Nguyễn Đức Trung", "Nguyenhang6689@gmail.com"),
				new Recipient("Nguyễn Đôn", "41300885@hcmut.edu.vn"),
				new Recipient("Nguyễn Như Cường", "nguyennhucuong94@gmail.com"),
				new Recipient("Lương Thế Tâm", "luongthetam09@gmail.com"),
				new Recipient("Nguyễn Văn Lộc", "nguyenlocvt@gmail.com"),
				new Recipient("Phan Văn Thiện", "p.vanthien1993@gmail.com"),
				new Recipient("Lã Thái Minh", "lathaiminh@gmail.com"),
				new Recipient("ĐOÀN THỊ LỤA", "doanthilua.bk@gmail.com"),
				new Recipient("anhcuongdt", "anhcuongdt@gmail.com"),
				new Recipient("Lê Quang Vinh", "levinhxdbk@gmail.com"),
				new Recipient("Nguyễn Nhất Linh", "linhit1.2@gmail.com"),
				new Recipient("Trương Ngọc Tuấn", "ngoctuan.ktmm@gmail.com"),
				new Recipient("Trần Minh Lợi", "tranloi2512@gmail.com"),
				new Recipient("ĐÀO ĐÌNH THIỆN", "daodinhthien91@gmail.com"),
				new Recipient("Phan Thành Nam", "thanhnam2000@gmail.com"),
				new Recipient("Phạm Hải Nam", "namsama310794@gmail.com"),
				new Recipient("Hoàng Đình Hiệu", "hieuhd.ktmt@gmail.com"),
				new Recipient("Nguyễn Đình Hà Đông", "nguyendinhhadonghd@gmail.com"),
				new Recipient("Lê Văn Tuấn", "tuanlv.k57@gmail.com"),
				new Recipient("Chu Nam Anh", "namanh.chu2103@gmail.com"),
				new Recipient("Trần Việt Lâm", "lamtv2208@gmail.com"),
				new Recipient("Trần Bảo Lộc", "baoloc259@gmail.com"),
				new Recipient("Nguyễn Thanh Hoài", "hoaiht92@gmail.com"),
				new Recipient("VÕ ĐÌNH VĂN", "vodinhvan12@gmail.com"),
				new Recipient("Nguyễn Văn Đông", "nguyendong24887@gmail.com"),
				new Recipient("Nguyễn Trí Thành", "nguyentrithanh306@gmail.com"),
				new Recipient("Lê Trung Kiên", "letrungkien179@gmail.com"),
				new Recipient("Nguyễn Phạm Phương Quỳnh", "phuongquynh267@gmail.com"),
				new Recipient("Đông Hải Nam", "hainam19101995@gmail.com"),
				new Recipient("Đông Hải Nam", "hainam19101995@gmail.com"),
				new Recipient("thanhnam", "bekhoebengoan1995@gmail.com"),
				new Recipient("Nguyễn Đăng Tráng", "ndtrang108@gmail.com"),
				new Recipient("Nguyễn Xuân Hòa", "nguyenxuanhoa208@gmail.com"),
				new Recipient("Thanh", "dinhthanh912@gmail.com"),
				new Recipient("Nguyễn Ngọc Xuân Huy", "nguyenngocxuanhuy411@gmail.com"),
				new Recipient("Lê Công Hải", "Leconghai.bk@gmail.com"),
				new Recipient("Nguyễn Thị Thanh Trang", "ngtrang68@gmail.com"),
				new Recipient("Nguyễn Đức Duy", "ducduy.2247@gmail.com"),
				new Recipient("Lâm Tấn Phát", "vltphat@gmail.com"),
				new Recipient("Lê Phương Anh", "lephuonganh21176@gmail.com"),
				new Recipient("Lư Văn Cương", "luvancuong0105@gmail.com"),
				new Recipient("Le Van Nam", "nam.d11.ptit@gmail.com"),
				new Recipient("Trần Quang Nhường", "tranquangnhuong@gmail.com"),
				new Recipient("Trần Ngọc Hanh", "hanhtranngocbcvt@gmail.com"),
				new Recipient("hoai", "hoaiphan1994@gmail.com"),
				new Recipient("Trần Trung Thành", "trantrungthanh1601@gmail.com"),
				new Recipient("Võ Thị Hồng Nhi", "Vothihongnhi2112@gmail.com"),
				new Recipient("Hoàng", "Hoangcanhuy289@gmail.com"),
				new Recipient("Hoàng Khắc Hiếu", "hoangkhachieu96@gmail.com"),
				new Recipient("Nguyễn Minh Anh", "minhanh61191@gmail.com"),
				new Recipient("Tô Minh Thiện", "minhthien162258@gmail.com"),
				new Recipient("Tô Minh Thiện", "minhthien162258@gmail.com"),
				new Recipient("Nguyễn Thị Trang", "trang2uet@gmail.com"),
				new Recipient("Trần Thị Hòa", "tranthihoa@gmail.com"),
				new Recipient("Nguyễn Văn Thắng", "nvthangbkhn@gmail.com"),
				new Recipient("Đặng Bảo Chung", "chungdb90@gmail.com"),
				new Recipient("Nguyễn Thị Mến", "men.nguyen8885@gmail.com"),
				new Recipient("Phạm Văn Nam", "phamgiangnam1989@gmail.com"),
				new Recipient("Trần Thị Ngọc", "ngoctran12395@gmail.com"),
				new Recipient("Vũ Đức Thuận", "ducthuanvu.hd@gmail.com"),
				new Recipient("nguyễn thị kiều oanh", "kieuoanhnguyen9213@gmail.com"),
				new Recipient("Nguyễn Tuấn Anh", "anhnt21@gmail.com"),
				new Recipient("Kiều Thị Giang", "giangkt2304@gmail.com"),
				new Recipient("Vũ Thị Phương", "phuongvu165432@gmail.com"),
				new Recipient("Bùi Việt Đức", "ducpykeanla@gmail.com"),
				new Recipient("Nguyễn Cao Nguyên", "Nguyen38ht@gmail.com"),
				new Recipient("Lê Minh Hợp", "leminhhop95@gmail.com"),
				new Recipient("Nguyễn Quang Huy", "nguyenhuy29588@gmail.com"),
				new Recipient("Lại Duy Tiến", "duytien2406@gmail.com"),
				new Recipient("Nguyễn Trung Đức", "trungduc.utc.k53@gmail.com"),
				new Recipient("Bùi Tuấn Anh", "anh.tbui1502@gmail.com"),
				new Recipient("Trần Thị Cẩm Vân", "tranthicamvan.95@gmail.com"),
				new Recipient("Đỗ Duy Tin", "nhoctinqf92@gmail.com"),
				new Recipient("Pham Tuan Anh", "anh2pt@gmail.com"),
				new Recipient("Nguyễn Thanh Tuấn", "nguyenthanhtuan1202@gmail.com"),
				new Recipient("Nguyễn Trần Minh", "nguyentranminh94bn@gmail.com"),
				new Recipient("Phạm Anh Tuấn", "hidevn@yahoo.com"),
				new Recipient("le tran long", "letranlong24@gmail.com"),
				new Recipient("Nguyễn Đức Mạnh", "ducmanhkthd@gmail.com"),
				new Recipient("Lưu Vĩnh Thịnh", "thinhlv1@gmail.com"),
				new Recipient("Nguyễn Mai Liên", "destiny240190@gmail.com"),
				new Recipient("Hoàng Hải", "hoanghai@yahoo.com.vn"),
				new Recipient("Hương Cao", "huongcao21693@gmail.com"),
				new Recipient("Nguyễn Văn Mạnh", "nguyenvanmanh140295@gmail.com"),
				new Recipient("Nguyễn Quỳnh", "hoaquynh8x@gmail.com"),
				new Recipient("Nguyễn Công Minh", "91minhnguyen@gmail.com"),
				new Recipient("nguyen viet hiep", "hiepbachkhoa@gmail.com"),
				new Recipient("Nguyễn Thị Mỹ Nương", "nuongntm91@gmail.com"),
				new Recipient("Tran Thi Hieu Thuan", "tthieuthuan@gmail.com"),
				new Recipient("Cù Xuân Hùng", "cuxuanhung94@gmail.com"),
				new Recipient("Cao Văn Tiệp", "lanhtudongxanh@gmail.com"),
				new Recipient("Hoàng Tuấn", "11hoangminhtuan11@gmail.com"),
				new Recipient("Vu Thi Ngoc", "ngocvu.uet@gmail.com"),
				new Recipient("VU DUC THUAN", "vuducthuan1994@gmail.com"),
				new Recipient("Nguyễn Thị Thu Hà", "Hangtt678@gmail.com"),
				new Recipient("Phạm Văn Dương", "vanduong0503@gmail.com"),
				new Recipient("Trương Ngọc Anh", "Tngocanh92@icloud.com"),
				new Recipient("Trần Quốc Tùng", "mrtungnt92@gmail.com"),
				new Recipient("Cao Thang", "Kaothang93@gmail.com"),
				new Recipient("Lê Sỹ Hiệp", "syhiep16892@gmail.com"),
				new Recipient("Trịnh Ngọc Ánh", "anh.trinh91@gmail.com"),
				new Recipient("Trần Quang Vinh", "quangvinh08081988@gmail.com"),
				new Recipient("Trần Quang Vinh", "quangvinh08081988@gmail.com"),
				new Recipient("Bùi Văn Nam", "912348776@gmail.com"),
				new Recipient("Nguyễn Thị Ngọc Anh", "Ngocanhvt3pti@gmail.com"),
				new Recipient("Đỗ Anh Tuấn", "doanhtuan80@gmail.com"),
				new Recipient("Phạm Hùng", "hungpham.tg92@gmail.com"),
				new Recipient("Nguyễn Văn Luật", "nguyenvanluat.dhbk@gmail.com"),
				new Recipient("Nguyễn Tùng Lâm", "tunglamktdt@gmail.com"),
				new Recipient("Khuất Thị Hằng", "hangkt175@gmail.com"),
				new Recipient("Nguyễn Thị Trang", "nguyentrang231095@gmail.com"),
				new Recipient("Nguyễn Ngọc Hà", "hannsoftec@gmail.com"),
				new Recipient("Đậu Thành Công", "dtcong.123@gmail.com"),
				new Recipient("Phạm Ngọc Thông", "ThongPN.hut@gmail.com"),
				new Recipient("Phạm Ngọc Thông", "ThongPN.hut@gmail.com"),
				new Recipient("Nguyễn Thế Nam", "nguyenthenam1995@gmail.com"),
				new Recipient("Nguyễn Hà My", "nguyenhamy.bi94@gmail.com"),
				new Recipient("Trần Thị Xuân Hiệp", "redsun.xunahiep@gmail.com"),
				new Recipient("Nguyễn Hồng Quân", "quanbk.94@gmail.com"),
				new Recipient("Vũ Văn Trường", "truong.vv2008@gmail.com"),
				new Recipient("Lê Cảnh Tiến", "lecanhtien16061994@gmail.com"),
				new Recipient("Lê Cảnh Tiến", "lecanhtien16061994@gmail.com"),
				new Recipient("Hai Anh Nguyen", "haianh.bkhn1989@gmail.com"),
				new Recipient("Nguyễn Văn Tiếp", "Hoancoi90tn@gmail.com"),
				new Recipient("Nguyễn Văn Tiếp", "Nguyenvantieptn95@gmail.com"),
				new Recipient("Vũ Văn Toàn", "toanvv1993@gmail.com"),
				new Recipient("Nguyễn Văn Vũ", "vuu.nguyenvan@gmail.com"),
				new Recipient("chauthu.94@gmail.com", "chauthu.94@gmail.com"),
				new Recipient("Minh Quang", "Quang.sctvhn@gmail.com"),
				new Recipient("Hoàng Văn Khanh", "hoangkhanh.ict@gmail.com"),
				new Recipient("Đinh Thị Linh", "linhdt1@gmail.com"),
				new Recipient("Hồ Văn Minh", "hovanminh@gmail.com"),
				new Recipient("Nguyễn Ái Linh", "Ailinh1291@gmail.com"),
				new Recipient("Nguyễn Ái Linh", "Ailinh1291@gmail.com"),
				new Recipient("nguyễn mạnh cường", "nguyenmanhcuong591993@gmail.com"),
				new Recipient("Đoàn Anh Tuấn", "anhtuan18894@gmail.com"),
				new Recipient("Lê Thị Bắc", "Lethibac94@gmail.com"),
				new Recipient("Bùi Lê Hoài Phương", "blhp.auto89@gmail.com"),
				new Recipient("Nguyễn Hùng Cường", "nhcuong84@gmail.com"),
				new Recipient("Nguyễn Hùng Cường", "nhcuong84@gmail.com"),
				new Recipient("Nguyễn Thế Minh", "minhnguyen2106@outlook.com"),
				new Recipient("Nguyễn Văn Hoàng", "hoangnguyen1094@gmail.com"),
				new Recipient("Nguyễn Văn Hoàng", "hoangnguyen1094@gmail.com"),
				new Recipient("Nguyễn Thị Thúy Hằng", "nguyenthuyhang2310@gmail.com"),
				new Recipient("Đặng Trần Minh Đức", "minhduc250991@gmail.com")
		};
		String templateSubject = "Mời bạn [FULL_NAME] tham gia tuyển dụng tại Trung tâm Không gian mạng Viettel";
		String filePath = "/data/new/email_template.txt";
		String templateContent = new String(Files.readAllBytes(Paths.get(filePath)));
        //log.debug(templateContent);
		
		Map<String, Boolean> sentMap = new HashMap<>();

		for (Recipient r : a) {
			String fullName = r.getFullName();
			String email = r.getEmail();
			
			Boolean isSent = sentMap.get(email);
			if (isSent == null) {
				sentMap.put(email, true);

				String realSubject = templateSubject.replace("[FULL_NAME]", fullName);
				String realContent = templateContent.replace("[FULL_NAME]", fullName);
				
				MailSender mailSender = new MailSender(username, password, alias, host, port);
				int status = mailSender.sendMail(email, realSubject, realContent, null);
				mailSender.closeTransport();
				//log.info(r + ": " + status);
				System.out.println(fullName + "," + email + "," + status);
			}
		}

		
		log.info("Sent to " + sentMap.size() + " emails.");
	}

}
