var data = [
	{ id: 1, title: "Tuyệt chiêu đánh lạc hướng phụ huynh", content: "<p>Tèo đi học ở xa, mỗi năm chỉ về vào đúng dịp Tết. Vì thế, mỗi lần Tèo về cả nhà đều rất vui mừng đãi tiệc lớn.</p><p>Trong buổi tiệc một người bác hỏi Tèo:</p><p>- Ở trường điểm số của cháu thế nào?</p><p>Tèo gãi đầu:</p><p>- Dạ, cũng không được tốt lắm bác ạ. Tại lên đại học rồi cháu bận yêu, thành ra không tập trung học được.</p><p>Cô Tèo liền hỏi:</p><p>- Thế giờ sao rồi, sao nghe bố mẹ cháu bảo cháu vẫn còn độc thân.</p><p>Tèo cười:</p><p>- Cháu thấy yêu ảnh hưởng đến học tập quá nên giờ chia tay rồi.</p><p>Mọi người gật gù:</p><p>- Cháu làm thế đúng đấy, đang học đừng nên yêu vội, học tập mới là quan trọng nhất.</p>"
	},
	{ id: 2, title: "Lý do quan tòa sợ cụ già", content: "<p>Tại một phiên tòa ở một thị trấn nhỏ. Luật sư bên nguyên gọi nhân chứng là một bà cụ già.</p><p>Luật sư tiến đến trước bà cụ và hỏi:</p><p>- Bà Jones, bà có biết tôi không?</p><p>- Tất nhiên, tôi lạ gì anh, Williams. Tôi biết anh từ hồi anh còn bé tí. Nói thật, anh là một nỗi thất vọng lớn của tôi. Anh tệ bạc với vợ con, lừa dối mọi người, hay nói xấu sau lưng. Anh cứ tưởng là anh thành đạt, nhưng cả cái thị trấn này ai chẳng biết anh là đồ lừa đảo.</p><p>Choáng váng, luật sư cố trấn tĩnh và hỏi tiếp:</p><p>- Thế thưa bà Jones, bà có biết luật sư bên bị không?</p><p>- Sao tôi không biết cậu Bradley, hồi ông ấy còn bé tôi bế cậu ta suốt. Tôi đến xấu hổ vì cậu ta. Lười biếng, và nghiện rượu. Chằng bao giờ có ai tin cậu ta cả. Cậu ta mà luật sư cái nỗi gì.</p><p>Quan tòa gõ búa lệnh nghỉ giải lao và gọi hai luật sư vào phòng riêng.</p><p>- Nếu một trong hai anh hỏi bà già này rằng bà ấy có biết tôi không, tôi cam đoan bỏ tù các anh trong 5 năm vì tội nhục mạ tòa, rõ chưa?</p>"
	},
	{ id: 3, title: "Ly hôn vì chồng mất trí nhớ tạm thời", content: "<p>Nghe tin cô bạn thân của mình sắp ly hôn, Jane bất ngờ hỏi:</p><p>- Sao đột nhiên cậu lại đòi ly hôn thế?</p><p>- Vì trí nhớ của chồng tớ ngày một kém. Tớ đã quá mệt mỏi về điều đó.</p><p>Jane ngạc nhiên đáp:</p><p>- Cậu nói sao ý chứ. Tớ thấy chồng cậu vẫn khỏe mạnh bình thường mà, làm gì có chuyện sa sút trí nhớ chứ.</p><p>Cô bạn thở dài:</p><p>- Cậu không biết đâu. Cứ lúc nào gặp những cô gái trẻ đẹp là chồng tớ lại quên mất mình đã có vợ.</p><p>- !!!</p>"
	},
	{ id: 4, title: "Lý do bố không tặng quà ngày 8/3", content: "<p>Buổi tối gần tới giờ ngủ, Na nũng nịu nói với bố:</p><p>- Ngày 8/3 không có ai tặng quà cho con đã đành, đằng này đến bố cũng không tặng gì hết.</p><p>Người bố vuốt nhẹ đầu con gái, nhẹ nhàng chỉ về phía vợ và nói:</p><p>- Con nhìn mẹ kìa.</p><p>Na nhìn theo và thấy mẹ đang cặm cụi dọn dẹp nhà cửa, mồ hôi lấm tấm rơi. Na reo lên:</p><p>- A, con hiểu rồi. Ý của bố là ngày 8/3 không phải ngày để đòi quà mà là ngày để chúng ta quan tâm và yêu thương mẹ nhiều hơn, phải không bố.</p><p>Bố Na lắc đầu:</p><p>- Không phải, ý bố là tiền của bố đã giao mẹ con giữ cả rồi, lấy đâu tiền mà mua quà tặng con nữa chứ.</p>"
	},
	{ id: 5, title: "Béo phì vì làm theo lời bác sĩ", content: "<p>John đến gặp bác sĩ than thở về sức khỏe của mình. Sau khi kiểm tra xong, bác sĩ nói:</p><p>- Kết quả cho thấy mức độ béo phì và lượng mỡ trong máu của anh tăng cao hơn so với lần trước đấy. Anh có tuân thủ theo chế độ ăn uống tôi bảo anh lần trước không?</p><p>John quả quyết đáp:</p><p>- Vâng tôi làm đúng theo lời bác sĩ nói mà. Tôi đã ăn các loại thực phẩm sáng màu như xanh, vàng, đỏ…</p><p>Bác sĩ nhướn mày:</p><p>- Thật chứ?</p><p>John càng quả quyết hơn:</p><p>- Thật mà, ngày nào tôi cũng đến siêu thị mua bánh kẹo, nước ngọt đủ màu tươi sáng đấy thôi.</p><p>- !!!</p>"
	},
	{ id: 6, title: "Buồn vì hoàn thành một nửa ước mơ", content: "<p>Họp lớp, mọi người ngồi tán gẫu với nhau về ước mơ thời học trò. Tũn cười nói:</p><p>- Hồi chục năm trước, cái cậu Tèo ngồi cùng bàn với tớ nói rằng ước mơ sau này của cậu ấy là trở thành chú cảnh sát, bây giờ ước mơ của cậu ấy đã thực hiện được một nửa rồi.</p><p>Mọi người trầm trồ:</p><p>- Chắc cậu ấy đang học trường cảnh sát hả?</p><p>Tũn nhún vai:</p><p>- Không, nhưng cậu ta đã được lũ trẻ con gọi là chú rồi.</p><p>- !!!</p>" }
];
